### ISSUE TITLE
add table of different versions to index page

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#10]
refering to #9 I propose to add some information to the index page:

[] link to the DE html version without comments
[] link to the EN html version without comments
[] links to the pdf version(s) without comments (aka the "official production versions")
[] link to the multi-lingual html version WITH comments

Too bad I've currently no idea how to organize the various versions with netlify or a download-option for the pdf versions... creative ideas needed

@p-goetz - as you created the previous index page AND the netlify/Travis integration, you're our prime candidate for such ideas :-)

**Comment by p-goetz** [comment]
I have tried several things but don't seem to be able to find to a viable solution: 

1. I have tried to use a deployment to GitHub Pages with Travis CI. This doesn't work as GitHub Pages publishes a directory of the repository, but our build/ directory is temporary and only for build results. 
2. I have tried to use the Docker build within netlify.com, which would allow more flexibility towards creating the different outputs, but Docker doesn't work with netlify. 
3. I have tried to tweak the asciidoctor gradle plugin to generate several output formats from one input format, which doesn't seem to work as it converts and renders a complete site and not single input files. 
4. I have created a scripted solution in node.js and ruby and worked with the asciidoctor API implemented in these languages to create the files myself. This works in principle, but node.js isn't able to generate PDF and ruby doesn't even recognize my attributes (language, withRemarks, ...). 

Now I am lost and need some help. Do you know something about one of the approaches described above that I have missed? Is there something I have not seen yet? 
I have briefly though about asciidoctor gradle pre- and post processing but couldn't find an angle that looked promising. 

If there are no new ideas I have to admit that with the current tool stack (netlify, travis-ci and even circle-ci) without external hosting I am out of ideas.

**Comment by gernotstarke** [comment]
I'll re-use the approach you (Peter) implemented in the [template-curriculum](https://github.com/isaqb-org/curriculum-template) repository.

**Comment by gernotstarke** [comment]
fixed with 3aeeab52b57ea3451312c75cb822a4c2c2d6f1f2
