### ISSUE TITLE
Umformulieren LZ 1-2 (um auch Funktionalität zu würdigen)

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#102]
Vorschlag von Andreas Rausch:

LZ 1-2: Umformulieren (Bisher: „…im Gegensatz zur reinen Implementierung der Funktionalität“
=> Das klingt so, als wolle man sich um Funktionalität gar nicht kümmern
Vorschlag für Alternative Formulierung: „Funktionale Anforderungen und insbesondere Qualitätsanforderungen, wie Zuverlässigkeit,
Wartbarkeit, Änderbarkeit, Sicherheit zu erreichen.“

**Comment by gernotstarke** [comment]
Anmerkungen Mahbouba + Andreas:

Mahbouba : unter der Qualitätsanforderungen (z.B nach ISO 25010) steht „funktionale Eignung“. Ich glaube, damit ist das Thema „Funktionalität“ adressiert. 
 
ARausch:   Kann ich auch mit leben, aber dann sollte man den Satz „im  Gegensatz zur reinen Implementierung der Funktionalität“ streichen,
weil der ja wieder genau das auseinander dividiert, was eben eigentlich eine Einheit ist: Funktionalität und QS-Eigenschaften

**Comment by gernotstarke** [comment]
Wir sollten im Lehrplan explizit sein - und uns nicht auf ISO 25010 verlassen, finde ich. 
Daher Kompromiss: Beide Begriffe.

DE
* Qualitätsanforderungen wie Zuverlässigkeit, Wartbarkeit, Änderbarkeit, Sicherheit sowie funktionale Anforderungen zu erreichen

EN:
* the achievement of quality requirements such as reliability, maintainability, changeability, security etc. and functional requirements

**Comment by rhoadesre** [comment]
Ich finde es irreführend, dass wir die funktionalen Anforderungen erreichen (implementieren). Vorschlag: zwei Bullet-Points:

- Qualitätsanforderungen wie Zuverlässigkeit, Wartbarkeit, Änderbarkeit, Sicherheit zu erreichen
- Funktionale Anforderungen zu erreichen bzw. deren Erfüllbarkeit sicherzustellen

**Comment by gernotstarke** [comment]
Meinungen dazu?

**Comment by alxlo** [comment]
Anmerkung: Die ISO 25010 beinhaltet als Top-Level-Qualitätsmerkmal auch das Erreichen der geforderten Funktionalität.

**Comment by StefanZoerner** [comment]
Die meinen in der ISO aber Funktionale Eignung. Dazu gehört beispielsweise, wie genau eine Berechnung ist. Englischer in der ISO: "Functional Suitability".

**Comment by alxlo** [comment]
Ich sehe da jetzt keinen Widerspruch:

> Functional Suitability
> This characteristic represents the degree to which a product or system provides functions that meet stated and implied needs when used under specified conditions. This characteristic is composed of the following subcharacteristics:
>  -  Functional completeness. Degree to which the set of functions covers all the specified tasks and user objectives.
>  -  Functional correctness. Degree to which a product or system provides the correct results with the needed degree of precision.
>  -  Functional appropriateness. Degree to which the functions facilitate the accomplishment of specified tasks and objectives.

Das umfasst aus meiner Sicht den Erfüllungsgrad funktionaler Anforderungen ebenso wie die Erfüllung sonstiger "Architecturally significant requirements".

In Ergänzung zu dem was @gernotstarke  sagt sollten wir auch unterscheiden zwischen den Anforderungen an das zu entwickelnde System und Anforderungen an die Architektur des Systems. [Hof07] hat das aus meiner Sicht ziemlich gut systematisiert. Zumindest ist das _die_ wissenschaftliche Arbeit die sich IMHO bisher am besten mit der Schnittmenge der Auffassungen in der FL-WG deckt. Weiterhin sollte die Auffassung nach [Mar17] mit rein: "The goal of software architecture is to minimize the human resources required to build and maintain the required system."

[Hof07] Hofmeister, C., Kruchten, P., Nord, R. L., Obbink, H., Ran, A., & America, P. (2007). A general model of software architecture design derived from five industrial approaches. Journal of Systems and Software, 80(1), 106-126.

[Mar17] Martin, R. C. (2017). Clean architecture: a craftsman's guide to software structure and design. Prentice Hall,  ISBN 978-0134494166

**Comment by gernotstarke** [comment]
see also #111

**Comment by gernotstarke** [comment]
updated LG 1-2 to

==== LG 1-2: Understand and explain the benefits of software architecture (R1)

Software architects can justify the following essential goals of software architecture.

Software architecture aims at:

* supporting design, implementation, maintenance and operation of systems
* achieving quality requirements such as reliability, maintainability, changeability, security
* achieving functional requirements or ensuring that they can be met
* providing an understanding of the system's structures and concepts, with regard to all relevant stakeholders
* systematically reducing complexity 
* specifying architecturally relevant guidelines for implementation and operation
