### ISSUE TITLE
Reduce LG 1-7 to R2

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#103]
Vorschlag von Andreas Rausch:

b)    LZ 1-7: Das würden wir gerne zur Kategorie R2 runter stufen

**Comment by rhoadesre** [comment]
OK

**Comment by gernotstarke** [comment]
ok, da bin ich auch für zu haben.

**Comment by alxlo** [comment]
Hier wäre ich stark dagegen, da ich schon zu oft gesehen habe, was dabei herauskommt, wenn kontinuierlich Architekturziele vernachlässigt werden um Projektziele zu erreichen. Die Architekturziele gegen Projektziele zu verteidigen ist in meinen Augen eine der wichtigsten und schwierigsten Aufgaben eines Architekten und dazu muss man diese auch differenzieren und gegeneinander abwägen können.

**Comment by programming-wolf** [comment]
Das sehe ich ähnlich wie @alxlo, in meinen Augen beschreibt LZ 1-7 Kernaufgaben einer/eines Softwarearchitekt/in.

**Comment by gernotstarke** [comment]
leave as-is.  (as discussed in FLWG-Conference-Aug-8th-2020)
