### ISSUE TITLE
Decide Collection of Architecture and Design Patterns

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#104]
Vorschlag von Andreas Rausch:

LZ 2-5: Die aufgelisteten Architekturmuster sind teilweise in meinen Augen keine Architekturmuster,
und sie werden auch je nach Literaturquelle unterschiedlich Verstanden. Beispiel: Proxy als R1 ?? Wirklich?
Meint ihr den Proxy aus dem Gang of Four Book??? Das ist doch wirklich kein Architekturmuster?
Deshalb mein alternativen Vorschlag:
„N Architekturmuster aus POSA- und PoEAA-Literatur (R1), wie zum Beispiel Schichten (Layer), Pipes and Filters und Blackboard““ 

     N könnte dabei für die Zahl 4 stehen oder 5 oder 6?
 
„M Designmuster aus dem Gang of Four Book (R1), wie zum Beispiel Proxy, Adapter und Facade“

   M könnte dabei für die Zahl 3 stehen

**Comment by alxlo** [comment]
I second Andreas' point and would like to emphasise that it is a serious problem if we list Adapter and Facade as architectural patterns.

**Comment by alxlo** [comment]
As a minimum fix I propose to at least change "architectural patterns" to "architectural and design patterns" in the title and the content of this LG.

**Comment by gernotstarke** [comment]
STRONG objection. Literature (GoF) calls it "design pattern" and ONLY focusses on object-oriented implementation and use in OO systems. We are NOT a OO curriculum!

On architectural level, both adapter and facade are useful "generic patterns" to reduce coupling and allow flexible interaction of systems, regardless of underlying implementation technology.

We should NOT restrict ourselves to books that are hopelessly outdated (GoF imho is outdated!), and better face architectural reality.

**Comment by alxlo** [comment]
My point is not about going into OO details. Design Patterns are not confined to the worls of OO.
I agree, that adapter and facade are generic pattern. My point ist that

1) an Adapter is - in the wide majority of sources - classified as a **software design pattern**. It might be quite confusing to argue that it is an architectural pattern. If we look at the traditional classification of architectural patterns (e.g. Buschmann), no adapter can be spotted in the wild there.

2) Suppose we **would** classify it as an architectural pattern (that is in your own words "... eine Konkretisierung oder Ausprägung von Architekturstilen") that doesnt work out in my opinion. It just doesn't operate at the same abstraction level as e. g. Dependency Injection or MVC. The concept of an Adapter gives structure for some of the elements of an architecture and does not define structure or behaviour for the system (or subsystems) as a whole.

**Comment by gernotstarke** [comment]
then please let me remark that the distinction between architecture and design is an artificial one in my opinion, and it does not help anyone in constructing and building better systems.
I suggest to not waste any more valuable time arguing this distinction. Let's call them patterns, is good enough in my opinion.

**Comment by rhoadesre** [comment]
I prefer to not make the distinction between architecture and design patterns.  I call them all design patterns. Some can be used to improve the system at the architecture level. Some can be used at the class, component and system level.  Class participants are often confused when I try to make the distinction between architecture patterns and design patterns.

**Comment by gernotstarke** [comment]
See also:

#137 (MVC)
#141 (Bridge)
#143 (Blackboard)
#138 (CQRS)
#120 (Cloud native)

**Comment by mikesperber** [comment]
Coming from functional programming, I see the following problems with this list of patterns:

- They are indeed OO-specific. ("Monad pattern", anyone?)
- As they currently stand, these patterns have almost no cohesion with anything else in the curriculum. The constructive aspects of the curriculum are mostly very high-level (LG 2-1), and the how the patterns relate to the organizational principles there is unclear.

So I vote for just removing them or downgrading LG 2-5 as a whole to R-3.  This would also free up some real estate for other topics people have asked for.

**Comment by alxlo** [comment]
If we would classify something as R3 it becomes more or less optional. I would like to differentiate on a per pattern basis.
I believe, most of us agree, that teaching e.g. the Bridge pattern is something that can not be reasonably done without hurting the time budget. But explaining its intention can be done in a 1.5 minute slide. And presenting it along with some other patterns and their uses takes 20% of a slide. The same can be said for some other patterns.

IMHO pattern have quite a place in the flow of the curriculum:
1.) Patterns are are a good way to illustrate how design principles are applied to a specific problem.
2.) Patterns are a way to structure various modes/types of coupling for a given scenario (providing a common knowledge corpus for how to discuss coupling is another construction site here).
These are two major points where patterns tie in with other parts of the curriculum.
3.) Reminding students to think of patterns is something they either can build on (as they already use them) or something that  provides timely return of investment in the training as they will probably be useful for most of the participants (at least the majority of MY students).
So I see practical and pedagogical value in this LG.

To make it blunt: I'm against abandoning patterns. But I'm very much in favor of reducing this LG to defining a small group of "must know" R1 patterns and a modestly sized group of "should know what they are good for" R2 patterns. Patterns for both groups should come from a larger pool than just the GoF and Buschmann categories. I think we will have an interesting discussion about which patterns to include if we should decide to go this way.

I would very much like to introduce patterns as a method for structuring problems and hint people at finding their own set of patterns that fit their needs (e. g. by looking at microservice patterns or whatever else is out there).

As for categorizing patterns: (e.g. care about whether something is a design pattern or an architectural pattern) I'm undecided. From a practical point of view this is not immediately valuable knowledge. The "good enough" from Gernot is good enough for me until we have time to make up our minds about this. On the other hand humans strive for structure. By hinting at existing frameworks for categorizing patterns we might make it easier for quite some people to adopt the use of patterns and some learners already think in theses categories.

**Comment by gernotstarke** [comment]
we should re-locate this discussion into confluence: https://confluence.isaqb.org/display/FOUNDATION/2021+-+Patterns+in+the+Curriculum

**Comment by gernotstarke** [comment]
WE MADE IT... and agreed upon a list, split only in R1 (mandatory) and R3 (optional, no questions in exam)!!

slight wording issues still to be discussed, but content-complete for now...
