### ISSUE TITLE
Relevanz von LZ 3-3: Von R2 nach R1

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#106]
Vorschlag von Andreas Rausch.

**Comment by rhoadesre** [comment]
Sorry. Was genau ist das Thema?

**Comment by gernotstarke** [comment]
Andreas Rausch hat vorgeschlagen, die Priorität von LZ 3-3 auf R1 zu erhöhen.

**Comment by gernotstarke** [comment]
Ich persönlich bin übrigens **deutlich** dagegen, der (imho altbackenen) UML noch mehr Raum zu geben, bzw. deren Priorität zu erhöhen.

**Comment by rhoadesre** [comment]
Ich habe keine starke Meinung. Bin aber eher dagegen. In vielen Projekten haben wir PowerPoint und Flipcharts benutzt und es war ausreichend.

**Comment by alxlo** [comment]
@gernotstarke und @rhoadesre +1
Eigentlich haben wir UML-Kentnisse bereits als Voraussetzung genannt. Faktisch habe ich (und wahrscheinlich auch andere) einen UML-Auffrischungs-Abschnitt im Script drin. Das würde ich ungern weiter aufblähen wollen.

**Comment by programming-wolf** [comment]
Ich finde den Themenbereich nicht unwichtig, bin aber der Meinung, dass R2 vollkommen dafür ausreicht. Ich halte es allerdings auch für wichtig, Alternativen zu behandeln (C4, 4+1, im Grunde "Kästen mit Pfeilen + Legende"), wofür in meinen Augen R2 ebenfalls reicht.  
Wichtig ist es meiner Meinung nach, dass die Möglichkeiten bekannt sind, die es gibt, und die Geschulten dann das Richtige in ihrem Umfeld umsetzen können.

**Comment by gernotstarke** [comment]
please see #140, which proposes the opposite (downgrade UML to R3)

**Comment by gernotstarke** [comment]
leave R2 as it already is  (as discussed in FLWG-Conference-Aug-8th-2020)
