### ISSUE TITLE
Hyperlink to bi-lingual (html) version is broken

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#109]
related to #108 (download artifacts had bad hyperlinks)

But: even though I included the following in travis.yml, the link to `foundation-curriculum-remarks-de-en.html` does not work:

```
file:
  - build/foundation-curriculum-*.pdf
  - build/foundation-curriculum-*.html
  - build/foundation-curriculum-remarks-de-en.html
  - build/images/*
```

This artifact is successfully generated during (local) build.

Suggestions welcome.

**Comment by aheusingfeld** [comment]
Maybe I'm a bit slow here but could you elaborate a bit on the problem vs. expected outcome?

**Comment by gernotstarke** [comment]
From an end-user perspective: The hyperlink to the bilingual version leads to 404, whereas the others are (now) ok:

From the page https://isaqb-org.github.io/curriculum-foundation/:

- [ ok] German without Comments (online, html)
- [ ok] English without Comments (online, html)
- [ BROKEN] **German/English with Comments (online, html)**
- [ ok] German without Comments (PDF)
- [ ok] English without Comments (PDF)

Culprit surely is the missing build goal in travis.yml. Thx for pointing that out.

**Comment by programming-wolf** [comment]
But is it necessary to have the bilingual html? That’s something I removed from the advanced template because I thought it was not helpful.

**Comment by gernotstarke** [comment]
My use-case for the bi-lingual version is "review", both "translation review" and "content review".

As it doesn't hinder anybody to read a single-language version, we can imho keep it.

**Comment by gernotstarke** [comment]
fixed - thanx @aheusingfeld for the suggestion!
