### ISSUE TITLE
LG 1-7: Was sind Architekturziele?

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#11]

**Comment by gernotstarke** [comment]
what LG are you referring to?

In DE version, Carola and me started replacing "Architekturziele" by "Qualitätsanforderungen und -ziele"... better for you?

**Comment by rhoadesre** [comment]
Sorry. LZ 1-7.  Laut Stefan Toth (und ich stimme zu), Architekturziele sind Qualitätsanforderungen. Sonst, was für Architekturziele gibt es, die nicht von den Qualitätsanforderungen abgedeckt sind?

**Comment by gernotstarke** [comment]
ich stimme Dir nur partiell zu:

* Betriebskosten in den nächsten Monaten um 10% senken
* Zukünftig nur noch Open-Source Lizenzen OHNE GPL verwenden

da können wir lange drüber diskutieren, ob das Architekturziele sind - aber i.d.R. haben solche
Ziele eine längere Lebensdauer. Lass' uns doch ruhig beide Begriffe verwenden - und im Glossary
könnten wir Begriffsdefinitionen versuchen...

**Comment by gernotstarke** [comment]
siehe auch #33 (von Phillip Ghadir).

**Comment by gernotstarke** [comment]
Ich bin auch dafür, den Begriff "Architekturziel" aus dem LZ zu streichen, und nur Qualitätsanforderung zu belassen....
