### ISSUE TITLE
LZ 1-2: Ziele von Softwarearchitektur: SW-Architektur als Vorgabe

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#111]
[Enter feedback here]
Ich möchte die Ziele ergänzen. IMHO dient die Software-Architektur auch als Vorgabe für die Implementierung und Betrieb des Systems.

---
#page:01-basics/LZ-1-02.adoc

**Comment by gernotstarke** [comment]
meiner Ansicht nach eine gute Idee. Bitte um Meinungen dazu.

Vorschlag: NICHT mehr in V5.0, sondern erst in 5.2

(ich habe den commit

**Comment by gernotstarke** [comment]
ich finde den Vorschlag gut, könnten wir imho so übernehmen.

**Comment by alxlo** [comment]
Aus meiner Sicht auch erst in > 5.0. Was mir noch fehlt ist die Aussage: "Softwarearchitektur ist ein wesentliches Mittel um Komplexität in IT-Systemen zu reduzieren." Im Sinne von "Komplexität = human effort to use, understand, maintain, and extend a software system."

**Comment by gernotstarke** [comment]
operations shall be added.  (as discussed in FLWG-Conference-Aug-8th-2020)

**Comment by gernotstarke** [comment]
updated LG to:
==== LZ 1-2: Ziele von Softwarearchitektur verstehen und erläutern (R1)

Softwarearchitekt:innen können folgende wesentlichen Ziele von Softwarearchitektur begründen.

Softwarearchitektur zielt darauf ab: 

* Entwurf, Implementierung, Pflege und Betrieb von Systemen zu unterstützen,
* Qualitätsanforderungen wie Zuverlässigkeit, Wartbarkeit, Änderbarkeit, Sicherheit zu erreichen,
* funktionale Anforderungen zu erreichen bzw. deren Erfüllbarkeit sicherzustellen,
* Verständnis für Strukturen und Konzepte des Systems zu vermitteln, bezogen auf sämtliche relevanten Stakeholder,
* systematisch Komplexität zu reduzieren 
* architekturrelevante Richtlinien für Implementierung und Betrieb zu spezifizieren

// end::DE[]

// tag::EN[]
[[LG-1-2]]

==== LG 1-2: Understand and explain the benefits of software architecture (R1)

Software architects can justify the following essential goals of software architecture.

Software architecture aims at:

* supporting design, implementation, maintenance and operation of systems
* achieving quality requirements such as reliability, maintainability, changeability, security
* achieving functional requirements or ensuring that they can be met
* providing an understanding of the system's structures and concepts, with regard to all relevant stakeholders
* systematically reducing complexity 
* specifying architecturally relevant guidelines for implementation and operation
