### ISSUE TITLE
Formating in (generated) footer is broken

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#112]
currently it reads `Version V5.0 -DE (28. Aug 2019)`,
the hyphen between 5.0 and DE should be evenly spaced...

(trivial fix, just as a reminder)

**Comment by programming-wolf** [comment]
Spaces before and after the dash? -> `V5.0 - DE`

Or no spaces at all? -> `V5.0-DE`

I prefer the version with spaces

**Comment by programming-wolf** [comment]
There you go, @alxlo : https://github.com/isaqb-org/curriculum-foundation/pull/113

I just _did_ ;-)

**Comment by programming-wolf** [comment]
Fixed with #113.
