### ISSUE TITLE
Release contains only bilingual html artifact

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#114]
Our releases SHOULD contain all available PDF versions (without comments).

**Comment by programming-wolf** [comment]
I fixed that as well, with commit [531f995](https://github.com/isaqb-org/curriculum-foundation/commit/531f99595b9c5fca7039f7c48bca91eab577dafa).

**Comment by programming-wolf** [comment]
Or so I thought, I missed something. 😒

**Comment by programming-wolf** [comment]
Is it ok to _only_ have PDF and HTML files _without_ remarks/comments for a release?

**Comment by gernotstarke** [comment]
for a release, yes! Commented-versions are for iSAQB-Working-Group internal use only!

**Comment by programming-wolf** [comment]
Alright. Fixed. :)
