### ISSUE TITLE
too many DRAFT releases

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#115]
The (fairly large) number or "DRAFT" releases looks "disturbing" - is it possible to "release" only "tagged" commits?

**Comment by programming-wolf** [comment]
We could add the following to our travis config:
`if: tag IS present`
[According to this discussion](https://github.com/travis-ci/travis-ci/issues/6893#issuecomment-354967391), it should work.

**Comment by gernotstarke** [comment]
I'm currently in customer workshops - you have time to fix it?

**Comment by programming-wolf** [comment]
I can try, of course. :)

**Comment by programming-wolf** [comment]
Now I do understand the issue. It's not that GitHub Pages is updated with every master commit (direct commit or PR merge) but that a DRAFT-Release is created in GitHub as Release. 
I now know how to tackle that. In addition, only one file was released so far, as the wildcard flag has to be activated.
