### ISSUE TITLE
Error message on page 2

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/curriculum-foundation#116]
The final document contains the following error message on page 2:

```
Unresolved directive in foundation-curriculum.adoc - include::/home/travis/build/isaqb-org/curriculum- foundation/build/learning-objectives.adoc[tags=FEEDBACK;DE;]
```

I guess this page should contain the table of learning objectives.

**Comment by gernotstarke** [comment]
aargh - which download did you check? The github-pages version, or the download from isaqb.org?

**Comment by programming-wolf** [comment]
Download from isaqb.org: https://www.isaqb.org/wp-content/uploads/2019/09/iSAQB_CPSA_Foundation_Level_Curriculum_DE_V5.0_2019_08_31.pdf

**Comment by programming-wolf** [comment]
Travis also spits out `SEVERE` warnings:
```
Sep 04, 2019 2:22:17 PM uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/reader.rb resolve_include_path
257SEVERE: foundation-curriculum.adoc: line 33: include file not found: /home/travis/build/isaqb-org/curriculum-foundation/build/learning-objectives.adoc
258Sep 04, 2019 2:22:36 PM uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb content
259WARNING: could not embed image: /tmp/image-20190904-4603-ibosws.svg?branch=master; image file is an unrecognised format
260Sep 04, 2019 2:22:37 PM uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb parse
261SEVERE: foundation-curriculum.adoc: line 33: include file not found: /home/travis/build/isaqb-org/curriculum-foundation/build/learning-objectives.adoc
```

**Comment by gernotstarke** [comment]
in local builds, this happens only the first time (after gradle clean)...

One idea (bad, but pragmatic): currently exclude learning-goal-table until we can resolve the issue on travis.

Second idea: I build locally and send the new docs to Bettina :-)

(and shouldn't it be asciidoctor 1.6.0?)

**Comment by programming-wolf** [comment]
Local Build should be fine for now, until we figure out how to properly fix it. 

Asciidoctor is 1.6.0, but asciidoctor-pdf is 1.5.0.beta2 (update to beta3 will be a separate issue).

**Comment by programming-wolf** [comment]
Fixed with the last commit.
