### ISSUE TITLE
LZ 1-10: Typen von IT-Systemen unterscheiden (R3)

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#12]
Vorschlag: LZ 1-10 löschen oder auf bspw. "Zusammenhang mit Hardware-Systemen" unbennen

**Comment by gernotstarke** [comment]
Ich finde dieses LZ ok - ist R3 (damit muss es in einer Schulung auch nicht behandelt werden).

Wir könnten darüber abstimmen, ob wir das streichen sollen. Ich nehme diese Frage mal in den Kommentar zum LZ auf.

**Comment by gernotstarke** [comment]
persönlich finde ich das LZ ok - denn die verschiedenen Typen von Systemen sollte doch wirklich jeder kennen...

**Comment by alxlo** [comment]
@gernotstarke +1 Warum ist das eigentlich R3? Gerade die Systemklasse bildet doch den Rahmen für oft fundamentale Architekturentscheidungen.
Hier sollten wir uns vielleicht einmal in der Gruppe auf der Fachebene verständigen, was denn der State-of-the-Art bei der Klassifizierung von Systemen ist. Dann können wir das auch gern auf R2 anheben.
Ich finde es wichtig, grobe Systemkategorien zu unterscheiden.  Dabei sind in den letzten Jahren die Grenzen zwischen den klassischen Kategorien "Embedded, Mobil, Informationssytem" stark verwischt und wir haben z. B. mit dem typischen IoT-Stack und "Cloud-Connected-Mobilsystemen" (sorry, dafür fällt mir ohne Recherche gerade keine treffendere Bezeichnung ein) fast so etwas wie eine neue Klasse von Systemen.

**Comment by gernotstarke** [comment]
close,  (as discussed in FLWG-Conference-Aug-8th-2020)
