### ISSUE TITLE
Fehlende Referenzen

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/curriculum-foundation#123]
Aktuell fehlt folgende Referenz (sie wird in einem Kapitel angegeben, ist aber nicht im Verzeichnis am Ende):

- Bass2003

**Comment by ulibecker** [comment]
Ich denke das sollten wir durch [Bass+ 2012] ersetzen (Software Architecture in Practice, 3. Auflage - Bass2003 ist die 2. Auflage)

**Comment by gernotstarke** [comment]
gerne einen PR :-)
