### ISSUE TITLE
Erweiterung der Voraussetzung.

### ISSUE THREAD

**Issue by LaszloLueck** [isaqb-org/curriculum-foundation#127]
Hallo,
ich würde gerne diesen Aspekt diskutieren:

Grundlegende Kenntnisse von:
- Algorithmen und Datenstrukturen (etwa Listen, Bäume, HashTable, Dictionary/Map)

Hier sollte bspw. auf Enumerable / Enumeratoren / Iteratoren und deren Unterschiede zu Listen oder Assoziativspeichern eingegangen werden.

Bei der Gestaltung eines Softwaresystems in Bezug auf die verfügbaren Ressourcen und der Kommunikation zwischen Softwarekomponenten bzw. innerhalb einer Software ist die Kenntnis hierüber essentiell.

---
#page:00-preamble/03-prerequisites.adoc

**Comment by gernotstarke** [comment]
good enough as-is  (as discussed in FLWG-Conference-Aug-8th-2020)
