### ISSUE TITLE
LZ 2-1: Vorgehen und Heuristiken zur Architekturentwicklung

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#13]
Erwarten wir, dass die Architekten sowohl DDD als auch modellgetriebene Architektur auch _anwenden_ können oder nur kennen und erklären können? 
Vorshlag: LZ 2-1 ist ein R1.  Machen wir die zwei Themen DDD und MDA als R3.

**Comment by gernotstarke** [comment]
ja, sehe ich auch so. in Lehrplan eingearbeitet.
