### ISSUE TITLE
LG 3-7 missing from list-of-LGs

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#132]
somehow it's not included in the (auto-generated) list of lg's, at least it's missing from the currently published version https://isaqb-org.github.io/curriculum-foundation/foundation-curriculum-en.html#_list_of_learning_goals

@p-goetz you have some spare minutes to look into it?

**Comment by programming-wolf** [comment]
I think that's already fixed, @alxlo committed the fix 2 months ago: 5ce15e7d83e317f389e63a54b56674ea9bb69ec0

**Comment by programming-wolf** [comment]
Fixed with [Release 2019.2-rev1](https://github.com/isaqb-org/curriculum-foundation/releases/tag/2019.2-rev1) 😃 

https://isaqb-org.github.io/curriculum-foundation/
