### ISSUE TITLE
LG 1-5: fix translation of "Fachbereich"

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#133]
currently "specialist field" (which imho is pure nonsense)

should be "business department" or "subject matter experts"

**Comment by alxlo** [comment]
"domain experts"? "subject matter experts" looks fine by me but sounds strangely 'synthetic'

**Comment by lilienth** [comment]
domain expert is always my choice too!

**Comment by lilienth** [comment]
but now, its not about the person but the organisational part. hm....

**Comment by lilienth** [comment]
dann würde ich business department nehmen. Aber ich bin keine native speakerin.... ich höre mich nochmal um.

**Comment by rhoadesre** [comment]
Hi everyone,
my two cents worth: 
"subject matter expert" in the customary term for "Fachexperte" in general. I prefer "domain expert" or, clearer, "business domain expert" like Carola suggested when talking about the software world. (You can also have technical domain experts).

"Fachbereich" will typically be translated as "business department" (again as Carola suggested) if you're talking about an organisational unit.

"Fachbereich" will also be translated to "subject area" when talking about a specific area of expertise that is not necessarily related to a business department.

**Comment by gernotstarke** [comment]
fixed, replaced with "business department and subject-matter experts"
