### ISSUE TITLE
In spirit of "inclusive language" - remove ALL dubious terminology

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#136]
see https://www.dictionary.com/browse/inclusive-language#:~:text=noun,be%20considered%20to%20exclude%20women

We should imho find appropriate terms, but keep (historical) references
* client/Server
* male-only terminology (especially in DE "Softwarearchitekt"

**Comment by p-goetz** [comment]
This is a good idea. I think replacing words like client/server or master/slave when we use them should be pretty straightforward. 
What about "Softwarearchitekt"? In German there are several ways to address all genders. As far as I have found in my search just now the Duden describes the gender gap (Softwarearchitekt_innen) or the asterisk (Softwarearchitekt*innen). I have also found Softwarearchitekt:innen, but not described by either Wikipedia or Duden. 
The advantage of the "official" recommendations is that there is also a way to pronounce it properly, the glottal stop (for when we orally quote the curriculum): https://de.wikipedia.org/wiki/Stimmloser_glottaler_Plosiv

What form do you prefer? I personally tend towards using the asterisk, but can't say why.

**Comment by programming-wolf** [comment]
I grew fond of the `:`. Compared to the asterisk, it doesn't break the reading flow. The asterisk is higher than the usual characters in the middle of a word, the `:` blends in. 
But that's just my opinion. 🙂

**Comment by gernotstarke** [comment]
We currently don't have "master-slave" or "blacklist-whitelist" mentioned, therefore we might just go for "purely male" terms in the German version.

Wikipedia explains the ":":
https://de.wikipedia.org/wiki/Gender_Gap_(Linguistik)#:~:text=Der%20Duden%20online%20f%C3%BChrt%20den,der%20der%20sprachlichen%20Gleichbehandlung%20aller

(see "Varianten").

I tried all three variants and like the ":" best, as Ben suggested, it blends in the reading flow.

**Comment by p-goetz** [comment]
Today I started to replace terms with more gender-inclusive versions. I have replaced the following terms: 

- "Softwarearchitekten" -> "Softwarearchitekt:innen"
- "Teilnehmer" -> "Teilnehmende" (this has already been done in parts, I completed it). 
- "Trainer" -> "Trainer:in"
- "Nutzer" -> "Nutzer:innen"

What about the following terms: 

- Anbieter / Schulungsanbieter (I personally envision the organization, not an individual, what do you think?)
- Stakeholder (this is an English term, I am unsure if we should change it to Stakeholder:in, what is your opinion?)
- Autorengruppe (does Autor:innengruppe go too far?)

I have created a new branch "issue-136" and ask you for your review.

**Comment by gernotstarke** [comment]
concerning:


* "Anbieter":  it's an organization, therefore nothing todo for us.
* "Autor:innengruppe" goes to far imho
* we leave the English "Stakeholder" as-is
