### ISSUE TITLE
add ArchiMate (as R3)

### ISSUE THREAD

**Issue by pgh** [isaqb-org/curriculum-foundation#147]
We should treat UML as an example for graphical notations and graphical modeling languages
In that case we should have some other examples. ArchiMate might be a good example

**Comment by gernotstarke** [comment]
changed title

**Comment by gernotstarke** [comment]
refers to LG 3-3.

We need to add a reference to our reference list

**Comment by gernotstarke** [comment]
added https://www.opengroup.org/archimate-forum/archimate-overview to references
