### ISSUE TITLE
Cover distributed systems

### ISSUE THREAD

**Issue by mikesperber** [isaqb-org/curriculum-foundation#148]
I know the curriculum is strained for space, but in every architecture we deal with, there are two central themes:

- coupling
- distributed systems

The latter isn't currently covered, and many developers don't know the central architectural issues with distributed systems. Consequently, they make bad architectural decisions that are hard to reverse.

Thus, we consider this more important than some of the other subjects in the curriculum.

**Comment by gernotstarke** [comment]
FLWG has to decide how to proceed:
either:

* mention consequences of distribution in any LG
* create a new LG for distribution

**Comment by gernotstarke** [comment]
Can you (@mikesperber ) please come up with a proposal for a learning goal that describes the fundamental topics of distributed systems that could be relevant for the foundation curriculum?

Having a single LG for distribution could imho resolve this issue quite nicely - we can decide exam-relevance later on.

**Comment by mikesperber** [comment]
Here's a first stab at it:

Software architects are able to:

- identify distribution in a given software architecture
- analyze consistency criteria for a given business problem
- explain causality of events in a distributed system

Software architects know:

- communication may fail in a distributed system
- limitations regarding consistency in real-world databases 
- what the "split-brain" problem is and why it is difficult
- that it is impossible to determine the temporal order of events in a
  distributed system

**Comment by gernotstarke** [comment]
Nice, I suggest we make this LG-2-10 or LG-1-11... currently I've no opinion WHERE to better locate it.

**Comment by mikesperber** [comment]
I like LG-1-11 better, as it's mainly descriptive, not constructive.

(I see that our material has it near the end, but I think that was mainly because it wasn't part of the curriculum and was added after the stuff in the curriculum.)

**Comment by aheusingfeld** [comment]
Consistency in distributed systems, the (business) decisions around this and their consequences is a larger topic inside the FLEX curriculum of CPSA-A. Even though we don't go into the very detail, it takes about 2-3 hours. 
If we decide that a CPSA-F training has to "briefly mention" this, it'd have to be a very good condensate otherwise I'm not sure that we do ourselves nor the participants any favor. :/

**Comment by gernotstarke** [comment]
+1, @aheusingfeld . 

But: For coupling, dependencies and some other aspects we also mention that and why they impose problems when done wrong... without giving people a complete portfolio of help...

Therefore I can imagine to ensure that participants know about risks and problems within distributed systems, without knowing (many) options "out of this mess".

Currently we mention "distributed systems" only in the prerequisites. See #135

**Comment by gernotstarke** [comment]
in discussion with @alxlo we agreed to change "Software architects know:" into "Software architects can explain why or how..."

**Comment by mikesperber** [comment]
> I like LG-1-11 better, as it's mainly descriptive, not constructive.

I should have said what I mean by these terms:

By "descriptive" I mean material that describes what (good) software architecture. By "constructive" I mean material that describes *how* to construct (good) software architecture.

The curriculum overall has significantly more descriptive material, and I suggest going with that approach here, too. (Covering how to construct distributed systems is way outside of what can be covereed in a typical foundation training.)

**Comment by alxlo** [comment]
Constructive aspects are to a small extent covered by LG 2-6 (Design Principles) LG 2-1 (Select and use approaches and heuristics for architecture development) and LG 2-2 (Design software architectures). The reference slide deck will cover design methodologies (onion, hexagonal, clean architecture) which yet have to find a place in the curriculum (but not for the 2020.1 release), see new issue #167.

Furthermore I propose (outside the responsibility of the FL group) to cover the constructive aspect by providing at least one good and consistent example scenario that complements the reference slide deck and the trainer manual. Both are one the home stretch, but what they actually lack is a well designed example to illustrate the descriptive material. Currently some trainers apply the CoCoMe example, which works but is some kind of cumbersome and awkward to put it politely.

This is no small endeavor. I talked about this several times with others and we came up with proposing the following idea: Going through the reference slides, identify the points you want to illustrate by the example. E.g. finding good trade-offs for some quality criteria, deciding how to separate certain concerns, or selecting candidates for libraries and frameworks to use, etc. Then use these as selection criteria to find an application domain and a sample system that can be sufficiently stretched without becoming too distorted to cover those points.

We have at least a coarse idea what domain to use, but we should start work out the details when we decide whether this would be a good way to incorporate the constructive aspects. It would lead to a "companion guide" complementing the reference slide deck.

**Comment by gernotstarke** [comment]
@alxlo your comment imho does NOT refer to the FL curriculum and should be located elsewhere. Please relocate it to advanced-level or any other appropriate github project. I'd like to close this issue, as we have the LG included and the original issue seems resolved to me.

**Comment by alxlo** [comment]
@gernotstarke I removed the parts concerning the example scenario(s).
