### ISSUE TITLE
more precise wording of LG 2-3

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#149]
the formulation "stakeholder concerns" is overly vague and diffuse.

Let's make clear what we really mean:

Which factors influence architectural decisions:

* time and money
* quality requirements and goals
* organizational and legal constraints
* functional reqs
* participating stakeholders

**Comment by gernotstarke** [comment]
Alexander formulates a new version of this LG...

**Comment by alxlo** [comment]
A proposal for a more detailed description can be found here https://confluence.isaqb.org/pages/viewpage.action?pageId=47356315. I took the liberty to align this with Hofmeisters Global Analysis.

**Comment by gernotstarke** [comment]
After a lengthy discussion between @rhoadesre @alxlo @ulibecker @mikesperber and myself we agreed upon a long list of influencing factors to be more concrete with our intention for this LG:

LG 2-3: Identify and consider factors influencing software architecture (R1-R3)
Software architects are able to gather and consider constraints and influencing factors that restrict their decisions.

They understand that their decisions may imply further requirements and constraints on the system being designed, its architecture, or the development process. (R1-R2)

They should recognize and account for the impact of:

product-related factors such as (R1)
functional requirements 
quality requirements and quality goals
additional factors such as product cost, intended licensing model, or business model of the system
technological factors such as (R1-R3)

externally mandated technical decisions and concepts (R1)

existing or planned hardware and software infrastructure (R1)
technological constraints on data structures and interfaces (R2)
reference architectures, libraries, components, and frameworks (R1)
programming languages (R3)
organizational factors such as

organizational structure of the development team and of the customer (R1)
company and team cultures (R3)
partnerships and cooperation agreements (R2)
standards, guidelines, and process models (e.g. approval and release processes) (R2)

available resources like budget, time, and staff (R1)
availability, skill set, and commitment of staff (R1)
regulatory factors such as (R2)
local and international legal constraints

contract and liability issues

data protection​ and privacy laws

compliance issues or obligations to provide burden of proof​

trends such as (R3)
market trends
technology trends (e.g. blockchain, microservices)
methodology trends (e.g. agile)
(potential) impact of further stakeholder concerns and mandated design decisions (R3)

Software architects are able to describe how those factors can influence design decisions and can elaborate on the consequences of changing influencing factors by providing examples for some of them (R2).

**Comment by gernotstarke** [comment]
thanx to all contributors to this discussion!!
