### ISSUE TITLE
update "examination guide", remove questions referencing "US-American presidents"

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#153]
We currently have various versions of the examination guide, most of these use American presidents to illustrate the types of examination questions.

We should replace these by culture-, gender- and person-neutral questions (e.g. math-questions).

**Comment by gernotstarke** [comment]
wrong repo, will be handled elsewhere

**Comment by alxlo** [comment]
That has already beenfixed. Closing the Issue.
