### ISSUE TITLE
replace questions-types (A,K,P) by internationally understandable abbreviations

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#154]
Auswahl: -> Selection or Single

Klärung: besser "Zuordnung"

Mehrfachauswahl: bisher Pick, besser "best-of"

**Comment by rhoadesre** [comment]
My proposal with consideration of Gernot's proposal:

Current (A): Einfachauswahlfragen / Assortment
Proposed: Einfachauswahlfragen / Single-Choice Question

Current (P): Mehrfachauswahlfragen / Multiple Selection
Proposed: Mehrfachauswahlfragen/ Mulitple-Choice Question

Current (K): Klärungsfragen / Allocation
Proposed: Zuordnung / Assignment

**Comment by alxlo** [comment]
One important goal of this issue - as I understand it - is to find an abbreviation that works in English and German (A, P, K doesn't.) That is, we would have to find a descriptive name for question types that starts with the same letter. After several tries I seriously doubt that this is possible and it would not work for all other languages anyway.
Therefore we should settle with abbreviations that make sense to English readers. It would be a good thing when they would NOT apply a currently used abbreviation to a different question type than before. That would spell trouble for the transition period. 

e.g.  to use "A-Question" for Assignment/Zuordnung might not be a good idea as it is currently used for Einfachauswahl.

Apart from this: I do not see the point in distinguishing between Single-Choice and Multiple Choice as the first is a specialization of the latter. As this is a different problem, I opened an issue in the Exam Jira. However, we should not be unprepared when this happens in the future and we only have "select answers" and "assign categories" questions. Maybe we can already name them appropriately. (e.g. S-Question and C-Question).

**Comment by gernotstarke** [comment]
wont fix due to meeting decision, its simply too much effort.
