### ISSUE TITLE
uniform spelling of blackbox, black-box and black box (similar white box, whitebox)

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#155]
for EN:
It seems the two-word version is correct - see the discussion on https://en.wikipedia.org/wiki/Black_box

Therefore, we change all occurrences to:

- black box
- white box

for DE:
verwenden wir  "Blackbox", siehe https://www.duden.de/suchen/dudenonline/Blackbox

**Comment by rhoadesre** [comment]
FYI. I personally don't care if we use "blackbox" or "black box"; however, if it is used as an adjective, it should be used with a hyphen. 
For example:

"The system being designed is depicted as a black box in the context diagram."
"The use of black-box components in the component diagram is allowed"

I just checked the curriculum. The term "black box" is not used as an adjective in the curriculum.
There went 10 minutes of my life.
