### ISSUE TITLE
consistent spelling of "building block"

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#157]
we have several occurences written with hyphen: "building-block",
let's stick to "building block" consistently.

**Comment by gernotstarke** [comment]
fixed

**Comment by rhoadesre** [comment]
Yeah. I can reuse my useless comment from issue #155 .

If "black box" will be used as an adjective, it should be used with a hyphen. For example:

LG 2-2: Design software architectures (R1)
Software architects are able to:
.......
- apply stepwise refinement and specify building blocks
- design architecture views, especially building-block view, runtime view, and deployment view

**Comment by rhoadesre** [comment]
Fixed
