### ISSUE TITLE
Add to LG 3-2 (Describe and communicate)

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#158]
We should add the following section to LG 3-2:

"Software architects know that various properties of documentation depend on specifics of the system, its requirements, risks, development, organization or other factors."

As always, it depends: 

* wether written or verbal communication should be prioritized
* the amount of documentation needed at what stage of development
* formats and accessibility of documentation
* formality of documentation (e.g. diagrams compliant to a meta model or simple drawings)
* formal reviews and sign-offs for documentation

**Comment by rhoadesre** [comment]
How about .....
------------------
Software architects understand that various attributes of documentation are dependent on a number of different factors, such as system requirements, project and technical risks, development approach, organizational aspects, etc.

These factors impact:
- whether written or verbal communication should be prioritized
- the amount and level of detail of documentation needed at each stage of development
- the documentation format
- the accessibility to the documentation
- formality of documentation (e.g. diagrams compliant to a meta model or simple drawings)
- formal reviews and sign-off processes for documentation

Each system and organization is different and there are no right or wrong answers. The architect is aware of these factors and will modify the documentation characteristics according to the situation.

**Comment by gernotstarke** [comment]
thanx Roger for this proposal.

I just slightly adjusted it, translated it to 

commited in eb745a4c1f1799f22b48221dab2a93db6fc9a34b
