### ISSUE TITLE
Add "explain the need for technical documentation" to LG-3-2

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#159]
In addition to #158, add the following parts to LG 3-2:

- Software architects are able to explain the need for technical documentation.

- For a given system or development situation, they can chose an appropriate format, structure, level-of-detail.

**Comment by mikesperber** [comment]
I like it.

**Comment by rhoadesre** [comment]
I like, "Software architects are able to explain the need for technical documentation.".

The line, "For a given system or development situation, they can CHOOSE an appropriate format, structure, level-of-detail." is a summary of #158 . Either use the summary or the extended version in #158 . Although I like the longer formulation, the summary formulation says pretty much the same thing without losing much meaning. Maybe a compromise between the two....
"For a given system or development situation, they can modify the documentation or its characteristics and choose an appropriate means (e.g. verbal or written), formality, format, structure, level-of-detail, accessibility, etc."

**Comment by gernotstarke** [comment]
Roger, you're right: #158 and #159 (this one) refer to the same LG and are a bit similar in content.

The resulting text of LG 3-2:

----
    ==== LG 3-2: Describe and communicate software architectures (R1,R3)
    Software architects are able to:

    * document and communicate architectures for corresponding stakeholders, thereby addressing different target groups, e.g. management, development teams, QA, other software architects, and possibly additional stakeholders
    * consolidate and harmonise the style and content of contributions from different groups of authors
    * know the benefits of template-based documentation.

    Software architects know that various properties of documentation depend on specifics of the system, its requirements,     risks, development process, organization or other factors.

    These factors impact:

    * whether written or verbal communication should be prioritized
    * the amount and level of detail of documentation needed at each stage of development
    * the documentation format
    * the accessibility to the documentation
    * formality of documentation (e.g. diagrams compliant to a meta model or simple drawings)
    * formal reviews and sign-off processes for documentation

    Software architects are aware of these factors and can adjust the documentation characteristics according to the situation.

----
