### ISSUE TITLE
change translation of "functional context" in LG 3-5

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#163]
I suggest to change it to "business or logical context"

(in German its "fachlicher Kontext")

**Comment by alxlo** [comment]
business context sounds fine by me. @rhoadesre What do you think?

**Comment by gernotstarke** [comment]
duplicate to #151

**Comment by gernotstarke** [comment]
resolved in LG 3-5

**Comment by rhoadesre** [comment]
business context is good.
