### ISSUE TITLE
finalize and DOCUMENT versioning schema for curriculum + exam-questions

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#165]
After discussion between @programming-wolf @alxlo and @gernotstarke we decided upon the following schema: 

    for "production releases": 2021.1-EN-20201005

    for release candidates:  2021.1-rc1-EN-20201005

proposal
    <year>.<major>-{candidate-}<lang>-<date>

where 

* <year> denotes the year the curriculum is planned to become **productive**
* <major> is an integer starting from 1. It will be incremented in **important** cases, e.g. 
    * a semantic change in a learning goal (e.g. add a new pattern to the existing list)
    * change of relevance level of any LG
    * a change that needs to be updated in translations (e.g. ES, RU)
    * 
* (optional) {candidate} denotes release-candidates, that will be issued for review-purposes only.
Candidate versions are labelled e.g. 2021.1.rc1-EN-20201005.

* <date> is added automatically by the build and deployment process! 
* <lang> is added by the build and deployment process

We maintain a file ("document.version") which contains <year>, <major> and {candidate}.

     2021.1 or
     2021.1-rc1

**Comment by gernotstarke** [comment]
I am currently not sure, if the order of elements in the proposal is well-suited for the automatic-build,
maybe we need to switch to 2021.1.rc1-EN, as it might be easier to implement...

**Comment by programming-wolf** [comment]
Languages have no effect on the tag name, they are incorporated automatically. The tag would be `2020.1-RC1` etc. for pre-releases. When you want to release the first "real" version, you simply switch to `2020.1-rev0` and get a proper release. I'll adjust the GitHub script today.

**Comment by programming-wolf** [comment]
Tags/Builds always create both English and German versions of the curriculum.

**Comment by alxlo** [comment]
> as it might be easier to implement...

We should decide which is a more important goal:
* easy to implement , low technical complexity
* understandable and easy to use representation of business process

I think, this is one of the main conflicts here.

**Comment by alxlo** [comment]
> ```
> 2021.1.EN-rev1
> ```

According to your proposal  {year}.{major}-{lang}-{revision} that would be

```
2021.1-EN-rev1
```
I' think you meant that ;-)

**Comment by alxlo** [comment]
> where
> 
>     * {revision} is either

I might be wrong, but I think we mix up the following two concerns, which is not good.
* Communicating changes to external stakeholders for dissemination
* Keeping track of the internal review process

**Comment by gernotstarke** [comment]
Benjamin implemented the required changes, starting with the advanced-template... so I can close this issue here.
