### ISSUE TITLE
Add a LG for design methodologies (or find place for it in other LGs, e.g. LG 2-1)

### ISSUE THREAD

**Issue by alxlo** [isaqb-org/curriculum-foundation#167]
We should at least mention not only DDD and MDA, but find a place for the following, even if it is only R3:

Architecture Design Methods
- Model Driven Architecture
- Hexagonal Architecture
- Onion Architecture
- Clean Architecture
- Evolutionary Architecture - guided change

This will ~~for sure~~ possibly not happen in the current release, but we should make room for it in the long run. This will also add more constructive aspects to the training to complement the descriptive material that makes up the majority of the training as correctly mentioned by @mikesperber

**Comment by alxlo** [comment]
Or maybe, just maybe, if we find enough supporters we could add this as R3 to LG 2-1 for the upcoming release?

**Comment by gernotstarke** [comment]
* Hexagonal/Onion/Clean Architecture imho clearly belong to the Pattern-LG.

* Model-Driven imho is more a systeamatic approach to convert abstractions into code, but does NOT aid people in design decisions 

* I suggest to add "Evolutionary Architecture" to LG 1.2 together with "global analysis", although it's just a slight renaming/tweak of the original "global analysis" approach from Hofmeister et al (which I personally renamed to "Quality driven architecture" for my courses. The name "Evolutionary Architecture" is modern and they published a nice book about it... let's make it R3. See #169

**Comment by alxlo** [comment]
I would like to have something in the curriculum
* that describes design methods (= how to design an architecture),
* is not as specific as lecturing about ADD, S4V, RUP 4+1, BAPO, ASC, etc.,
* but is still one level ob abstraction above architectural patterns.

DDD and MDA currently already are mentioned in LG 2-1 as R3 and fit that bill IMHO quite well.

I can't argue with Onion and Hexagonal being patterns. They obviously are. On the other hand they are "something more" than the Buschmann patterns. Onion is much more than a modern way to describe layers. It applies several architectural patterns and is (lacking a better description) something like a "design philosophy". In that way it bridges a gap between architectural patterns and design methods. 

IMHO we have at least three aspects here:
* Patterns that describe the structure and interaction of components that make up a systems architecture.
* Patterns that in addition give structure to the design process.
* Primarily process oriented design methods.

**Comment by gernotstarke** [comment]
we updated LG 2-1 to include evolutionary architecture and global analysis.
What else do you propose as "lightweight" changes that we should include in V2021?

**Comment by gernotstarke** [comment]
I consider this solved - LG-2-1 seems an appropriate cluster for methods.
