### ISSUE TITLE
LG-3-6 Inconsistency between English and German

### ISSUE THREAD

**Issue by ulibecker** [isaqb-org/curriculum-foundation#171]
**Current curriculum:**

German:
Softwarearchitekt:innen können typische Querschnittskonzepte (auch genannt _Prinzipien_ oder _Aspekte_) adäquat dokumentieren und kommunizieren, z. B. Persistenz, Ablaufsteuerung, UI, Verteilung/Integration, Protokollierung.

English:
Software architects are able to adequately document and communicate typical cross-cutting concerns, e. g., persistence, workflow management, UI, deployment/integration, logging.

"(auch genannt Prinzipien oder Aspekte)" is only contained in German. IMO these are not really synonyms for "Querschnittskonzepte", therefore should be removed.

**Proposal:**

Softwarearchitekt:innen können Querschnittskonzepte für typische Aspekte wie z. B. Persistenz, Ablaufsteuerung, UI, Verteilung/Integration, Protokollierung adäquat dokumentieren und kommunizieren.

Software architects are able to adequately document and communicate cross-cutting concepts for aspects such as persistence, workflow management, UI, deployment/integration, logging.

**Comment by gernotstarke** [comment]
In arc42 we translate "cross-cutting concepts" to "Querschnittliche Konzepte oder Prinzipien", therefore I'm biased towards throwing all these terms into the same pit.

To quote from the iSAQB glossary:

https://leanpub.com/isaqbglossary/read#term-crosscutting-concept

Crosscutting concept
See concept.

Synonym: principle, rule.

**Comment by ulibecker** [comment]
I find it confusing in the context of this curriculum, where "principle" primarily refers to "design principles"

**Comment by gernotstarke** [comment]
slight objection: quote from IEEE 1471 https://en.wikipedia.org/wiki/IEEE_1471, one of the "definitions of software architecture":

    architecture: The fundamental organization of a system embodied in its components, 
    their relationships to each other, and to the environment, and the 
    **principles** guiding its design and evolution.

**Comment by gernotstarke** [comment]
proposal:

* better align DE and EN version
* add a number of synonyms in parenthesis after "cross-cutting concepts" (syn: aspects, principles)

ok for you?

**Comment by ulibecker** [comment]
As IEEE 1471 / ISO 42010 does specify what it means by *principle*, that does not much clarification :wink:

I disagree that cross-cutting concepts, aspects, principles are synonyms. No strong objections from my side however - can live with the version above.

**Comment by Hruschka** [comment]
Ok for me
Peter

Von meinem iPhone gesendet

**Comment by gernotstarke** [comment]
I researched in ISO 42010 and could NOT come up with a definition of "principle", therefore I can only stick with my "gut feeling" which tells me "don't nitpick"... one day we'll sort that out in person... until then, I close this issue.

**Comment by ulibecker** [comment]
> I researched in ISO 42010 and could NOT come up with a definition of "principle", therefore I can only stick with my "gut feeling" which tells me "don't nitpick"... one day we'll sort that out in person... until then, I close this issue.

Yeah, there was a *not* missing in my reply above, which was exactly the point I wanted to make...

**Comment by gernotstarke** [comment]
you just wanted to make sure I re-read your comment by missing out the important keyword...

**Comment by rhoadesre** [comment]
> slight objection: quote from IEEE 1471 https://en.wikipedia.org/wiki/IEEE_1471, one of the "definitions of software architecture":
> 
> ```
> architecture: The fundamental organization of a system embodied in its components, 
> their relationships to each other, and to the environment, and the 
> **principles** guiding its design and evolution.
> ```

As I understand the term "principles" from this sentence, they are referring to the _design principles_ as we refer to them, not to cross-cutting concerns.

I strongly disagree that cross-cutting concerns and principles are synonyms. I've never heard them as referring to the same thing. If we use principles in this context, it will only lead to confusion.

I have, however, heard of the term "aspects" as a synonym for cross-cutting concerns.

P.S. I would like to be consistent with "cross-cutting concerns" and not "cross-cutting concepts".

**Comment by rhoadesre** [comment]
Any chance to reopen this issue?

**Comment by gernotstarke** [comment]
as this is a public repo, and you are active committer... of course we can reopen the issue... (alas, it'd make things somewhat simpler if we replaced open discussion by dictatorship). Thanx for investing time here...

**Comment by gernotstarke** [comment]
contentwise I have a rather strong opinion on this "principles" and "concepts" stuff ("it's all the same")

- both terms are practically useless, unless specialized or somewhat "instantiated" with additional semantic
- let's try an example: "persistence by using the Hibernate library as OR-mapper and Postgres as relational DB". I'd call that a "concept" or "cross-cutting concept", as we apply this concept throughout the system. What's the difference to "in principle, we implement persistence that way"? In my opinion it's the same. More synomym: It's our own persistence pattern, our own persistence tactic/strategy or we have implemented our own persistence aspect.
- arc42 uses the term "concept" as the most general term for "stuff" (strategies, tactics, patterns, approaches, principles) that's used/done/applied at/to/with several architectural elements. It's practically useless to try to distinguish between these terms, as they all try to solve the same kinds of problems, and nobody would care for the distinction.

**Comment by rhoadesre** [comment]
> contentwise I have a rather strong opinion on this "principles" and "concepts" stuff ("it's all the same")
> 
> * both terms are practically useless, unless specialized or somewhat "instantiated" with additional semantic
> * let's try an example: "persistence by using the Hibernate library as OR-mapper and Postgres as relational DB". I'd call that a "concept" or "cross-cutting concept", as we apply this concept throughout the system. What's the difference to "in principle, we implement persistence that way"? In my opinion it's the same. More synomym: It's our own persistence pattern, our own persistence tactic/strategy or we have implemented our own persistence aspect.
> * arc42 uses the term "concept" as the most general term for "stuff" (strategies, tactics, patterns, approaches, principles) that's used/done/applied at/to/with several architectural elements. It's practically useless to try to distinguish between these terms, as they all try to solve the same kinds of problems, and nobody would care for the distinction.

I agree partially with you. When talking about a solution, it is difficult and IMHO unnecessary) to differentiate between strategies, tactics, patterns, and (solution) approaches. However, I think it is necessary to differentiate between "concepts"  (using your term) and "principles":

I agree that the strategies, tactics, patterns, and solution approaches are all referring to solving a problem. However, a principle is a axiom/policy/convention/maxim that is stated as a general statement and used to make quick decisions. Principles are there to help you make decisions and don't necessary provide a direct solution. 
- Should I buy or build? According to my principles, I should choose buy.
- Should I use interfaces or not in this situation?
- Should I separate these two building blocks or not?

P.S. By the way, I assume you are using the term "approach" in terms of how to solve a problem and not "approach" in terms of how to perform the architectural work.

**Comment by rhoadesre** [comment]
To be clear, I can live with "cross-cutting concepts" rather than "cross-cutting concerns" (although it's not my preference). However, I would like to see the term "principles" removed from this section.

**Comment by rhoadesre** [comment]
We've started down a different path now, but my two cents regarding the concepts and cross-cutting concerns.

I think you're comparing apples and oranges. 

Tactics, strategies, patterns, etc. are referring to implementation solutions to problems.
Cross-cutting concerns are referring to implementation aspects in the system that impact the entire system (or most of it).

If I refer to the "layers" pattern, I am referring to a specific implementation approach. If I refer to "persistence" cross-cutting concern, I'm talking about a specific aspect, that can be implemented in a number of different ways.

**Comment by gernotstarke** [comment]
duplicate to #168
