### ISSUE TITLE
make the glossary available online as github-page, or leave it "as-is" on Leanpub?

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#176]
@alxlo proposed to have the iSAQB glossary available online (via Github).

Current state:

* Source of glossary is maintained on Github
* Rendering of glossary is performed via Leanpub
* HTML-version can be viewed online [here](https://leanpub.com/isaqbglossary/read)
* all terms can be directly adressed by adding a.g. `#term-crosscutting-concept` to the url

Alternative or enhancement:

* publish the glossary-repo via github-pages (needs some scripting magic, and a few Leanpub-specific markdown clauses won't work)

Or leave it "as-is".

Opinions?

**Comment by alxlo** [comment]
This is highly desirable. But. 

Either we find someone to set up the infrastructure for this or we have to postpone it.

**Comment by gernotstarke** [comment]
in my personal opinion, having the Leanpub online version is good enough:

* the URL is stable
* we have NO hassle with setting up anything
* we don't need to modify the existing markup sources

currently, we don't release/change the glossary often enough. But that's easy to change - one author has to push the "publish" button on Leanpub... rest works like a charm.

**Comment by programming-wolf** [comment]
Good idea to reflect on this in a year or two. 😀

**Comment by gernotstarke** [comment]
note to self: remember issue #176 October 3rd 2022

**Comment by gernotstarke** [comment]
close issue, so we can focus on more urgent issues...

**Comment by gernotstarke** [comment]
re-openend, as we discussed to move forward with the online glossary

**Comment by programming-wolf** [comment]
As all of the Leanpub specific markdown was converted and the pipeline works as expected, can we close this issue (again)?

**Comment by gernotstarke** [comment]
I suggest to upload a pdf'd version to leanpub - but that HAS to be done manually...
And I suggest to add an "about-leanpub" and "about-our-cause" page, specifically for this leanpub
version...

Therefore, we would need to upgrade the build process with another target, `buildLeanpubPDF`,
which includes a few more pages...
