### ISSUE TITLE
add foreign translations of 2021.1 to Github-Repo and build 

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#177]
in directory docs-ext we can add foreign languages (e.g. ES for Spanish) which should be included in the generated download.

Let's obtain an example doc from iSAQB GmbH and try out this mechanism.

**Comment by programming-wolf** [comment]
That already works :) Spanish is available. We can simply drop them in docs-ext, create a new release (revX) and BOOM, there it is 🙂

**Comment by gernotstarke** [comment]
whow, thanx
