### ISSUE TITLE
Question: Shall we use **boldface** within learning goals to highlight important terms?

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#178]
do you have an opinion on this (typesetting) option?

Currently we have:

----
They should recognize and account for the impact of:

 * product-related factors such as (R1)
----

We could emphasize toe "product-related" by adding boldface:

----
They should recognize and account for the impact of:

* **product-related** factors such as (R1)
----

I suggest to use it in LG 2-3 (influencing factors), LG 2-5 (patterns) and LG 2-6 (design principles),
maybe we find other appropriate usages for it.

please vote +1 or -1

majority wins.

**Comment by gernotstarke** [comment]
+1

**Comment by rhoadesre** [comment]
-1.
I think this will lead to too many discussions about what should be emphasized and what not. 
If the main points are lost in the text, I think we should rethink the text and simplify or shorten the text.

**Comment by Hruschka** [comment]
-1
Ich bin bei Roger.

Peter

Von meinem iPhone gesendet

**Comment by mikesperber** [comment]
-1

**Comment by gernotstarke** [comment]
ok - majority agains boldface... Only exception is LG 2-6, as I found no other way to layout it...
