### ISSUE TITLE
add additional references/sources for patterns

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#185]
as we included numerous additional patterns, it will be helpful if we include additional references/sources too...

I'll start with the O'Reilly https://www.oreilly.com/content/software-architecture-patterns/,
but others (for e.g. Microservices, SOA, Combinator etc) should follow

Please add your favorites to references-adoc

**Comment by mikesperber** [comment]
For the "combinator pattern", I suggest Evans's "Domain-Driven Design" and, if there's room:

Monoids: theme and variations
Brent A. Yorgey
Proceedings of the 2012 Haskell Symposium, September 2012 Pages 105–116
https://doi.org/10.1145/2364506.2364520

**Comment by gernotstarke** [comment]
thx

Dr. Gernot Starke
+49-177-7282570
gs@gernotstarke.de
www.gernotstarke.de

Von einem mobilen Geraet gesendet - bitte verzeihen Sie eventuelle Tippfehler.

**Comment by rhoadesre** [comment]
I added a couple of references

**Comment by mikesperber** [comment]
Suggestion for "microservices":

Sam Newman: Building Microservices: Designing Fine-Grained Systems 
O'Reilly UK Ltd.; 2nd edition (21. September 2021)

**Comment by mikesperber** [comment]
Also notably missing: "ports-and-adapters", "CQRS", "event sourcing", "MVC" et al.

**Comment by mikesperber** [comment]
Suggestion for "ports-and-adapters":

Martin, Robert C. (2017). Clean architecture : a craftsman's guide to software structure and design. Prentice Hall.

**Comment by mikesperber** [comment]
I just saw that we have both Newman and Martin in the references list already, so I just added links.

**Comment by mikesperber** [comment]
> 


> I added a couple of references

Just to note the connection: @rhoadesre's commit is https://github.com/isaqb-org/curriculum-foundation/commit/3f920126aa71f5616f9a54129672f86f13aa5e9b

**Comment by mikesperber** [comment]
@gernotstarke So I think all concrete suggestions in this ticket are implemented. (#265 has more.) So I suggest just closing it.
