### ISSUE TITLE
demote "Querschnittskonzepte dokumentieren" to R2, LG 3-6

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#186]
LG 3-6, it's documentation-only, not "designing cross-cutting concepts"... R2 would suffice imho.

**Comment by mikesperber** [comment]
I'm not sure I follow: Section 3 is on documentation, and LG 3-6 does not mention "designing". Am I misunderstanding?

**Comment by mikesperber** [comment]
Just saw the mention in #187, and agree with the rationale for this one.

**Comment by gernotstarke** [comment]
done for rc2
