### ISSUE TITLE
promote LG 3-8 (architecture decisions) to R1

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#187]
likely one of the most important aspects of documentation.

I suggest to at least add "Architecture Decision Records" (ADR) as an example of a methodical approach to it.

To keep timing balanced, I suggest to demote LG 3-6 to R2. See #186

**Comment by mikesperber** [comment]
Ah, here's the rationale for #186. I agree.

**Comment by gernotstarke** [comment]
done.
