### ISSUE TITLE
fix references to online glossary

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#189]
since the latest update to the PDF-conversion, the required "#" character is replaced by "%23".

The resulting links look like:

`https://leanpub.com/isaqbglossary/read%23term-interface`

instead of the correct:

`https://leanpub.com/isaqbglossary/read#term-interface`

**Comment by gernotstarke** [comment]
just checked: Even in the V5 PDF versions those links are broken. Only in the HTML versions they work!!

So the culprit must be the PDF generation...

**Comment by programming-wolf** [comment]
This seems to be a macOS Catalina issue. See the discussions [here](https://discussions.apple.com/thread/251041261) and [here](https://apple.stackexchange.com/questions/377869/apple-preview-encoding). 
Apparently, Apple's Preview in version 11 escapes the `#` and creates the wrong URL. Mojave seems to work perfectly fine. Can anyone test with Big Sur? Acrobat Reader and Firefox render the URL correctly.

**Comment by gernotstarke** [comment]
so we close this issue, cannot currently be resolved.

**Comment by programming-wolf** [comment]
Big Sur seems to have fixed the issue. 🙂
