### ISSUE TITLE
LG 3-5: add brief explanation of business- and technical context

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#190]
a question I receive quite often is "what's the difference between technical and business context?"

maybe we should give a brief explanation here.

**Comment by rhoadesre** [comment]
Good point. I'm not sure myself what this is referring to. 

- Business context: Relation of the system to business domains, processes, information objects, and organizational structure
- Technical context: Relation of the system to other systems, interfaces, and technologies

??????

**Comment by gernotstarke** [comment]
explanation should be in glossary and/or references.

**Comment by gernotstarke** [comment]
@alxlo creates glossary entries

**Comment by programming-wolf** [comment]
Is this still relevant? Or superseded by #264 ?

**Comment by rhoadesre** [comment]
Frankly, this opens a big discussion around whether a software architect is responsible for the business context / architecture. 

I would like to officially remove the line "differentiate business and technical context" from the upcoming version. 

I am completely in agreement, that it is very important to differentiate the two, but this statement leads to confusion as to what the terms really mean as well as to who is responsible for the two topics.

**Comment by rhoadesre** [comment]
Related issues that were already closed, but address the same thing:  #263 and #264

**Comment by gernotstarke** [comment]
Both terms are imho important - and within arc42 we give several examples of what they _could_ mean.

Hopefully these will make it into the glossary one day:-)

My opinion on their meaning differs from yours, @rhoadesre 

* technical context: specific technologies, technical protocols, involved hardware (basically a higher-level diagram of the technical infrastructure, including hardware, networks etc)
* business context (or domain context): external systems and actors, without going into technical details. 

In both cases, our systems is a black-box, therefore no internal details are visible (esp. no internal domain structure)

**Comment by gernotstarke** [comment]
as written above, @alxlo will create the glossary entries, and @gernotstarke volunteers to support

**Comment by alxlo** [comment]
crossref https://github.com/isaqb-org/glossary/issues/125

**Comment by alxlo** [comment]
Habemus pull request https://github.com/isaqb-org/glossary/pull/126

**Comment by alxlo** [comment]
After the additions to the translation tables https://github.com/isaqb-org/glossary/pull/127 have been approved, those changes to the glossary can be published.

@gernotstarke Could you .. ? :-)

@rhoadesre Is this sufficient to satisfy this issue?

**Comment by programming-wolf** [comment]
https://github.com/isaqb-org/glossary/pull/126 and https://github.com/isaqb-org/glossary/pull/127 have been merged. 
Is this issue considered complete? Or does it require an update to Leanpub to be complete?

**Comment by gernotstarke** [comment]
we close it here, as the definitions have been moved to the glossary.
