### ISSUE TITLE
unify wording of LG 1-2 "objectives, goals and benefits"

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#192]
the LG 1-2 currently reads:

----
==== LG 1-2: Understand and explain the benefits of software architecture (R1)

Software architects can justify the following essential goals of software architecture.

The objectives of software architecture are:

----

even in these three sentences we use THREE different terms. We should align this to "goals and benefits" (in DE: Ziele und Nutzen)

**Comment by gernotstarke** [comment]
proposal:

## LG 1-2: Goals and Benefits of Software Architecture (R1)

Software architects can justify the following essential goals and benefits of software architecture:
 
* support the design, implementation, maintenance, and operation of systems
* achieve quality requirements such as reliability, maintainability, changeability, security, etc.
* achieve functional requirements or ensure that they can be met
* ensure that the the system's structures and concepts are understood by all relevant stakeholders
* systematically reduce complexity
* specify architecturally relevant guidelines for implementation and operation

**Comment by ulibecker** [comment]
+1 looks good to me

**Comment by gernotstarke** [comment]
done.

**Comment by rhoadesre** [comment]
This issue has already been closed, but I wonder if we missed an important goal.
- Identify and managed architecturally relevant risks

One of the reasons to design the system before it's implemented is to reduce the risks such as:
- wasting time and effort
- using inappropriate technologies or approaches
- etc.
