### ISSUE TITLE
rename LG 2-7 (from "planning" to "designing" or "designing and managing"

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#195]
imho "planning" does not sound right...

From my perspective it's about designing and managing dependencies

votes or opinions please...

**Comment by rhoadesre** [comment]
We don't plan dependencies, which implies that we increase dependencies. We would "account for dependencies" ("Abhängigkeiten betrachten / berücksichtigen". 

How about:
- Determine dependencies between building blocks and account for them in the architecture design (e.g. document or reduce)
- Abhängigkeiten zwischen Bausteinen ermitteln und diese im Architekturentwurf berücksichtigen (z.B. dokumentieren oder reduzieren)

**Comment by mikesperber** [comment]
I agree it doesn't sound right.

I'm not sure I follow @rhoadesre , who seems to imply that the architecture is designed after the dependencies of the building blocks have been established. Like @rhoadesre , I found the wording "can use such types of coupling ..." a bit jarring. I don't think we "use coupling" as much as we perform activities which either result in or reduce coupling.

It's also a bit strange that bullet #1 says "dependencies" before the parens, and "coupling" inside - especially as coupling is not just between building blocks.

The problem with "design" is that it's poorly specified what that means in the context of architecture. (At least without words around it like "Domain-Driven Design".)



So my suggestion would be:

- replace "Planning dependencies" -> "Manage dependencies between building block"

Then:

- know different types of dependencies of building blocks (use/delegration, nesting, ownership, generation, inheritance, shared data types, etc.)
- understand different types of coupling (shared knowledge, temporal, technological, etc.) and how dependencies create coupling
- know and apply ... [same as before)

**Comment by ulibecker** [comment]
+1 for @mikesperber's suggestion

I would replace "dependencies create coupling" with "dependencies increase coupling"

**Comment by gernotstarke** [comment]
will include your comments, thanx

**Comment by rhoadesre** [comment]
"understand how dependencies increase coupling"
Aren't "dependencies" and "coupling" synonyms? Can you have a coupling without a dependency?

According to Wikipedia (I know, not the best source, just an example):
Coupling is:
- the degree of interdependence between software modules;
- a measure of how closely connected two routines or modules are;
- the strength of the relationships between modules.
