### ISSUE TITLE
LZ 1-5: Inconsistency in Wording

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#196]
I just rechecked the wording. This may be nit-picking, but it could lead to confusion.  The learning goal refers to roles and stakeholders, but the terms used are not always roles or stakeholders (e.g. implementation, data centers).

=================
Proposed Text EN
=================
LG 1-5: Relate the role of software architects to other stakeholders (R1)
Software architects are able to explain their role. They should adapt their contribution to a software
development in a specific context and in relation to other stakeholders, in particular to:
• product management and product owners
• project managers
• requirement engineers (requirements analyst, requirements manager, system analyst, business owners, subject-matter experts, etc.)
• developers
• quality assurance and testers
• IT operators and administrators (applies primarily to production environment or data centers for information systems), 
• hardware developers
• enterprise architects and architecture board members

=================
Original Text EN
=================
LG 1-5: Relate the role of software architects to other stakeholders (R1)
Software architects are able to explain their role. They should adapt their contribution to a software
development in a specific context and in relation to other stakeholders, in particular to:
• requirements analysis (system analysis, requirements management, business department and
subject-matter experts)
• implementation
• project lead and management
• product management, product owner
• quality assurance
• IT operations (production, data centers), applies primarily to information systems
• hardware development
• enterprise architecture, architecture board

=================
Original Text DE
=================
LZ 1-5: Rolle von Softwarearchitekt:innen in Beziehung zu anderen Stakeholdern setzen (R1)
Softwarearchitekt:innen können ihre Rolle erklären und ihren Beitrag zur Systementwicklung in Verbindung
mit anderen Stakeholdern kontextspezifisch ausgestalten, insbesondere zu:
• Anforderungsanalyse (Systemanalyse, Anforderungsmanagement, Fachbereich)
• Implementierung
• Projektleitung und -management
• Produktmanagement, Product-Owner
• Qualitätssicherung
• IT-Betrieb (Produktion, Rechenzentren), zutreffend primär für Informationssysteme
• Hardwareentwicklung
• Unternehmensarchitektur, Architekturboard

**Comment by gernotstarke** [comment]
+1, updated the LG accordingly. Thanx for your contribution, again.

**Comment by gernotstarke** [comment]
I added "organizational units" - as the gendered terms sounded somewhat awkward in German... please have a second look at the result
