### ISSUE TITLE
rework list of "types of dependencies" in LG 2-7

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#197]
we currently enumerate:

`(e.g. structural coupling via use/delegation, nesting, ownership, generation, inheritance, temporal coupling, coupling via data types or via hardware)`

I'm not sure what we mean by the following:

[ ] nesting (is it aggregation/composition?)
[ ] generation

**Comment by alxlo** [comment]
Yes, IMHO nesting is aggregation/composition = must be contained in another component.
generation = creation 

Unfortunately we currently do not have a clear line on how to teach coupling. Most material I have seen only conveys a very basic approach (=there are several modes of coupling that we name, but we will not go into details). Even wikipedia has more details on this https://en.wikipedia.org/wiki/Coupling_(computer_programming) and there are for sure some competing approaches to classify coupling out there.

**Comment by lilienth** [comment]
I did not create this list, but I would gues the following:
- nesting refers to inner classes 
- generation refers to dependencies that the programmer of a class did not write him/herself but that came in by some generated code that belongs to the class or another class that refers to this one.

**Comment by alxlo** [comment]
As this is beyond the scope of this issue we should track this in Jira: https://jira.isaqb.org/browse/FL-38

**Comment by gernotstarke** [comment]
@alxlo I don't understand why we don't discuss it here, as curriculum content is public.
