### ISSUE TITLE
add "coupling via messages/events" to LG 2-7

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#201]
I just noticed that we currently don't explicitly mention (async) coupling via messages/events...

or is out "temporal coupling" good enough?

Architects should imho know about differences between sync calls and async messages with respect to coupling,
what do you think?

**Comment by Hruschka** [comment]
Yes, add it.

Temporal coupling has a different meaning. It is too far fetched to summarize async events and messaging under this term.

Yes, architects should know the difference between sync and async communication.

Peter

**Comment by alxlo** [comment]
+1 I have seen some slides from different trainers mentioning messaging as one mode of coupling and IMHO it can be a category of its own as it implies a mix-up of many constraints: temporal, communication mode (sync/async), location/addressing/routing, data/naming, service levels (don't care, at least once, exactly once), ...

ceterum censeo: classification of coupling is one of the things where we lack a clear and common understanding in our "architecture knowledge canon", see my comment https://github.com/isaqb-org/curriculum-foundation/issues/197#issuecomment-709937740 and @gernotstarke's follow-up.

For know "good enough" is good enough. And as this is beyond the scope of this issue I created https://jira.isaqb.org/browse/FL-38 to keep track of theses problems.

**Comment by gernotstarke** [comment]
thanx - I enhanced the list as follows:


>know and understand different types of dependencies of building blocks (e.g. coupling via use/delegation, **messaging/events**, composition, creation, inheritance, temporal coupling, coupling via data, data types or hardware)

**Comment by ulibecker** [comment]
The change is fine for me. Open question for me: What exactly is then our definition of temporal coupling? There are lots of conflicting definitions:

* Referring to the distinction between sync / async communication (e.g. Gregor Hohpe names "temporal decoupling" as one of the properties of messaging), also van Steen and Tanenbaum define "Temporal coupling means that processes that are communicating will both have to be up and running"
* "Your code as a crime scene": Temporal coupling: when you often commit some modules/classes at the same time
* Mark Seemann: "temporal coupling, which occurs when there's an implicit relationship between two, or more, members of a class requiring clients to invoke one member before the other
* ...

**Comment by gernotstarke** [comment]
whow, impressive research. Can you give a reference to Mark Seemann please?

And to add my own:

Things that have to be done in a specific order by different modules - then these modules can have temporal coupling...

**Comment by gernotstarke** [comment]
the curriculum does not contain such definitions, but our glossary does.
Uli, could you please open a PR in the glossary with these definitions??
(or shall I do that for you?)

https://github.com/isaqb-org/glossary

**Comment by ulibecker** [comment]
https://blog.ploeh.dk/2011/05/24/DesignSmellTemporalCoupling/
