### ISSUE TITLE
LG 2-6: "Conceptual integrity" problematic

### ISSUE THREAD

**Issue by mikesperber** [isaqb-org/curriculum-foundation#202]
Currently, the curriculum has:

Conceptual integrity (R2)
• to achieve uniformity (homogeneity, consistency) of solutions for similar problems (R2)
• as a means to implement the principle of least surprise (R3)

The wording suggests that conceptual integrity is a technique rather than a goal. The causality is backwards.

Even as an unqualified goal, it's problematic. Don't we teach in FLEX that we should purposely throw conceptual integrity out the window to reduce coupling?

I'd personally just throw this point out.

If that's not an option, maybe:

Conceptual integrity (R2)
• meaning uniformity (homogeneity, consistency) of solutions for similar problems (R2)
• can help achieve the principle of least surprise (R3)

**Comment by mikesperber** [comment]
@alxlo Sure.

I should have referred to Brooks: The problem is that Brooks reports from his personal experience with one particular project - and that project happens to be an OS. In that domain (I'd argue), you really want conceptual integrity. But in the general sense, I'd say that statement is simply false. (Despite the fact that it's from a Turing-award winner.)

**Comment by gernotstarke** [comment]
I'm a great friend of conceptual integrity, I see that a primary goal for architecture... as it helps improve understandability, facilitates knowledge transfer etc...

Therefore I oppose "dropping" it - but really like the option of making it a goal (which was originally intended anyway)...
