### ISSUE TITLE
LG 2-5: The term Self-Contained-Systems cannot be used interchangeably with the term Microservices

### ISSUE THREAD

**Issue by svenjohann** [isaqb-org/curriculum-foundation#204]
LG 2-5 states the following:

* DE: Microservices (auch bekannt als Self-Contained-Systems)...
* EN: Microservices (aka Self-Contained-Systems) ...

It is true that Self-Contained Systems can be decomposed into Microservices (https://scs-architecture.org/vs-ms.html). But there are also other approaches (e.g. "Netflix-Style" or the message-based style proposed by Fred George, where services are not necessarily self-contained, e.g. they have no GUI). Also Google talks sometimes about "the frontend application" and "backend services" (overheard in a presentation).

I would just write _Microservices_

**Comment by gernotstarke** [comment]
fixed with PR #205
