### ISSUE TITLE
LZ 1-2 Qualitätanforderungen

### ISSUE THREAD

**Issue by mahduse** [isaqb-org/curriculum-foundation#207]
Qualitätsanforderungen nach ISO 25010 sind auch funktionale Anforderungen. 
Vorschlag:
Qualitätsanforderungen nicht funktionaler Art wie Zuverlässigkeit ...
Reine funktionale Qualitätsanforderungen zu erreichen ...

**Comment by ichsteffen** [comment]
Meiner bescheidenen Meinung nach, sollten die Formulierung "nicht funktional" soweit es geht vermieden werden. Der Begriff "nicht funktional" verursacht immer wieder Missverständnisse und Unklarheiten.

**Comment by gernotstarke** [comment]
genau genommen lautet die Formulierung in ISO 25010 auch "functional suitability" (funktionale Eignung) - und nicht "functional requirement".
Darüber streitet das Requirements-Engineering ja schon lange.

persönlich finde ich die aktuelle Formulierung:

````
* Qualitätsanforderungen wie Zuverlässigkeit, Wartbarkeit, Änderbarkeit, Sicherheit zu erreichen
* funktionale Anforderungen zu erreichen bzw. deren Erfüllbarkeit sicherzustellen
````

gut genug - es kommt ja klar heraus, dass sowohl die "ilities" wie auch die Funktion gemeint ist.

andere Meinungen?

**Comment by gernotstarke** [comment]
closing this issue, as no further comments have been made. Current LG seems clear enough. Thanx for the open discussion, @ichsteffen @mahduse
