### ISSUE TITLE
LZ 1-8 implizit

### ISSUE THREAD

**Issue by mahduse** [isaqb-org/curriculum-foundation#208]
generell einverstanden, sehe aber auch Vorteile manchmal implizite Aussagen zu treffen, um "nicht mit der Tür ins Haus zu fallen." Ist in der Schweiz zumindest bei der Findungsphase weit verbreitet und eher üblich. Schlussendlich ist aber immer explizit angesagt.
War auch u.a.  Feedback meiner schweizerischen Kursteilnehmer

**Comment by gernotstarke** [comment]
Hast Du einen Vorschlag, der die aktuellen 2 Unterpunkte entsprechend ergänzt, ohne ihre Aussage abzuschwächen?

**Comment by mahduse** [comment]
sind aber auch in der Lage, implizit zu formulieren wenn es im gegebenen Kontext angebracht ist.

**Comment by gernotstarke** [comment]
nice... like that.

**Comment by gernotstarke** [comment]
done
