### ISSUE TITLE
feedback from training provider: include validity date in curriculum (footer)

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#212]
It seems that the current version number (2019.2) leads people to think "valid from February 2019"...

Therefore, various (experienced) trainers suggested in a private conversation within INNOQ to explicitely include the
validity date in the footer of the new curriculum:

current text: 2021.1-rc4-EN-20201106

proposed enhancement: 2021.1-rc4-EN-20201106 - mandatory and binding from April 1st 2021

**Comment by programming-wolf** [comment]
Would it suffice to have a single page dedicated to the version and its validity, at the beginning of the document? Otherwise, the footer will get very bloated...

**Comment by programming-wolf** [comment]
Also: if we only change minor stuff that doesn't require an adjustment (like fixed typos), would that require an update to the validity date? I don't think so, as the date is connected to the year or major version, right?

**Comment by gernotstarke** [comment]
problem might be that people DONT READ the beginning of the doc, but only the learning goals...

I think it would be a good first approach to have these dates prominently on the title page...

**Comment by gernotstarke** [comment]
your question regarding validity: for the 2021-version, validity remains April 1st 2021, UNLESS R1 learning goals are heavily changed

**Comment by alxlo** [comment]
I agree with @programming-wolf that we will get some footer bloat. However, wee need the valid from and the fine grained version.  So let's keep it a bit shorter?

` 2021.1-rc4-EN-20201106 - valid from 2020-04-01`

**Comment by gernotstarke** [comment]
fine for me... as long as it's as-clear-as-possible for everyone!!

**Comment by programming-wolf** [comment]
Alright, I'll adjust the template/file structure later.

**Comment by programming-wolf** [comment]
Like this?

<img width="760" alt="Screenshot 2020-12-14 at 19 35 49" src="https://user-images.githubusercontent.com/30000147/102121021-99437d00-3e43-11eb-9900-47abe86b935d.png">

<img width="773" alt="Screenshot 2020-12-14 at 19 35 38" src="https://user-images.githubusercontent.com/30000147/102121031-9d6f9a80-3e43-11eb-9f2f-945563e20d58.png">
