### ISSUE TITLE
remove term "stereotype" from list of terms in section 2 

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#214]
as this term is not mentioned in any LG

**Comment by programming-wolf** [comment]
I don't find the word "stereotype" anywhere in the curriculum. Can this be closed?

**Comment by gernotstarke** [comment]
imho we SHOULD mention the term, as it is quite useful to connect building blocks to crosscutting concepts.

Let's amend one of the existing LG, e.g. by adding a subgoal (bullet-item)
