### ISSUE TITLE
Allow Deployment of Release Candidate to `gh-pages`

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/curriculum-foundation#215]
We need the possibility to deploy release candidates so that training providers will be able to easily access new release candidates. 

**Proposed solution:** There will be a new directory called `release-candidate` which will contain the most recent release candidate. Upon a new "proper" release, the release candidate will be wiped from `gh-pages`.  
URL: `https://isaqb-org.github.io/curriculum-foundation/release-candidate`

**Comment by gernotstarke** [comment]
sounds like an excellent idea - thanx Ben
