### ISSUE TITLE
get the 2021.1 version on our public website for download...

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#218]
downloading a tagged version gives ALL kinds of files nobody really wants... and imho we're now stable enough to provide a download from https://isaqb-org.github.io/curriculum-foundation/

**Comment by programming-wolf** [comment]
We're (Alex H. and I) already changing release content for the advanced module, so that a PDF is available as direct download and direct link. 

I'll provide a solution in a pull request. Either this week or next week.

**Comment by programming-wolf** [comment]
See [#92](https://github.com/isaqb-org/advanced-template/issues/92) in the advanced template repository.

**Comment by programming-wolf** [comment]
closed by #228
