### ISSUE TITLE
LG 3-2

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#223]
The difference between verbal and written communication needs to be more specific to include their differences, their advantages and disadvantages, and when to use them in different situations. This should be a separate point to the bullet "whether written or verbal communication should be prioritized"

**Comment by feststelltaste** [comment]
Isn't this a topic for the CPSA-A module ADOC?

**Comment by gernotstarke** [comment]
todo @rhoadesre please check if still valid

**Comment by gernotstarke** [comment]
as the curriculum does NOT aim to be a "how-to" or "detailed explanation", I consider the current state good enough.

If you consider the topic relevant, please (@rhoadesre ) open a pull-request in the glossary instead (that's where detailed explanations should go!)
