### ISSUE TITLE
LG 4-4

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#224]
Describe the advantages, disadvantages, and differences between static and dynamic code analysis in more detail.

**Comment by feststelltaste** [comment]
This may overlap with the IMPROVE curriculum:

> - LG 2-6: Code and structural analysis
> - LG 2-7: Runtime analysis

I would recommend going into more details there.

But just mentioning "static and dynamic code analysis" in the Foundation curriculum would be a good improvement IMHO.

**Comment by rhoadesre** [comment]
See #254 
Will be changed to R3

**Comment by alxlo** [comment]
The curriculum is no textbook. That would be a valuable contribution to the glossary!
