### ISSUE TITLE
LG 2-1 (DE): Inconsistent capitalization (Top-down vs. Bottom-Up)

### ISSUE THREAD

**Issue by ulibecker** [isaqb-org/curriculum-foundation#226]

**Comment by gernotstarke** [comment]
Markus, could you come up with a good proposal for:

DE: Top-Down or Top-down (upper-(/lowercase for second term), both in Bottom-Up and Top-Down
EN: Top-down

**Comment by programming-wolf** [comment]
I'd say Top-down and Bottom-up in German.

**Comment by gernotstarke** [comment]
ok for me. Looks way better imho than  "Bottom-Up"...

Do you like to clean that up in the curriculum??

**Comment by programming-wolf** [comment]
Yup, will do.
