### ISSUE TITLE
question: do we need to move from jCenter() to another artifact provider in gradle?

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#232]
https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/#:~:text=JFrog%20has%20announced%20that%20they,(which%20hosted%20Helm%20charts).

**Comment by programming-wolf** [comment]
I already tried a fix in the advanced-template. It worked and I will roll it out to the other curricula this week.
