### ISSUE TITLE
add "release-notes" to build

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#233]
It would be nice if we could build the release-notes (as pdf and/or html) when we build the curriculum...

it's not urgent, but could be useful for our release...

**Comment by programming-wolf** [comment]
If you tag a new release, you can write (a lot of) text as the tag's message. That text will be used as Release Notes in GitHubs releases page. [Have a look at this release as an example.](https://github.com/isaqb-org/curriculum-foundation/releases/tag/2019.2-rev1)

**Comment by gernotstarke** [comment]
I have a curated change log in file "release-docs/2020.1-release-notes.adoc". That spans 100+ lines - maybe too much for a tag-comment...?? or am I wrong?

**Comment by gernotstarke** [comment]
on the other hand... we might try

**Comment by programming-wolf** [comment]
Ah, ok. yes, we could try to add a build step that converts the release notes adoc file into a PDF. Forgot about that. 
However, for a release, only the latest release notes (not the history) is important, so maybe it's not that much text. 😉

**Comment by programming-wolf** [comment]
Would also be great to source the release notes for the GitHub release from that file...

**Comment by gernotstarke** [comment]
for the upcoming 2021.1 release, everything from that curated release notes would be fine...
makes it easier for trainers to adapt their training material/slides...

**Comment by programming-wolf** [comment]
Release notes haven been added manually as PDF. We can adjust the build pipeline to also build the release notes. 🙂

**Comment by programming-wolf** [comment]
You can now do this with CHANGELOG.md. 
Merging #330 added this feature. 🙂
