### ISSUE TITLE
Strange wrong link on mobile page for https://github.com/isaqb-org/curriculum-foundation

### ISSUE THREAD

**Issue by alxlo** [isaqb-org/curriculum-foundation#234]
Mobile page for https://github.com/isaqb-org/curriculum-foundation shows strange link to the mock exam Download. This should not be there, instead link to isaqb-org.github.io/curriculum-foundation

![grafik](https://user-images.githubusercontent.com/581574/107865549-e950b700-6e67-11eb-825a-2325b223a492.png)

**Comment by gernotstarke** [comment]
the link is part of the "about this repo" settings in Github. Changed it to "https://isaqb-org.github.io/"
