### ISSUE TITLE
Publish new releases (and candidates) on  isaqb-org.github.io

### ISSUE THREAD

**Issue by alxlo** [isaqb-org/curriculum-foundation#235]
Please include upcoming release on isaqb-org.github.io/curriculum-foundation

**Comment by programming-wolf** [comment]
The release candidate is already published and available here:
https://isaqb-org.github.io/curriculum-foundation/release-candidate/

**Comment by programming-wolf** [comment]
Don't be confused by the text, it is currently the same index page as for the regular release.

**Comment by gernotstarke** [comment]
closed, as @programming-wolf completed this...
