### ISSUE TITLE
HTML version contains ":" where it shouldn't be 

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#237]
`: Foundation Level` in the heading, the `:` could be removed.

![image](https://user-images.githubusercontent.com/1233990/110587029-60315500-8173-11eb-85cf-2c9c38c70469.png)

**Comment by programming-wolf** [comment]
The character `:` is used to be able to separate main title from subtitle in the PDF document. I don't know (yet) how we can remove that in the html file.

**Comment by programming-wolf** [comment]
Subtitle is currently not supported by asciidoctor in HTML output, see asciidoctor/asciidoctor.org#423

**Comment by gernotstarke** [comment]
also discussed in https://github.com/asciidoctor/asciidoctor/issues/2749

it seems that it can (currently, Nov 2022) only be handled by custom templating or extending asciidoc converters.

Too much effort, too little benefit.

Set this to wontfix
