### ISSUE TITLE
consider replacing SOLID principles

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#243]
imho those principles place an overly large focus on object-orientation.

Maybe we should at least add CUPID, or diminish the importance of object-technology in the curriculum

see e.g.  [CUPID - for joyful coding](https://dannorth.net/2022/02/10/cupid-for-joyful-coding/) or the
[backstory](https://dannorth.net/2021/03/16/cupid-the-back-story/)

**Comment by richard-wallintin** [comment]
When doing trainings for Foundation Level currently, i do mention Dan Norths CUPID, so i would agree with an R3 addition to the curriculum. But as of today, the SOLID principles are too relevant and i believe concrete and helpful.

**Comment by mikesperber** [comment]
This blog post by Martin himself shows that the S (Single-Responsibility) is rather ill-defined:

https://blog.cleancoder.com/uncle-bob/2014/05/08/SingleReponsibilityPrinciple.html

**Comment by rhoadesre** [comment]
In general, I think the SOLID principles (other than Liskov) are still valid - with or without object-orientation. 

I read about the CUPID principles and am not convinced that they should be used as a replacement. The author specifically states that the acronym came first and then the principles (or did I misunderstand this point?). The CUPID principles are interesting and could be added as R3.

**Comment by alxlo** [comment]
IMHO still relevant with varying degree that is currently well indicated in the curriculum.

But I'm in favor of adding CUPID as R3.
