### ISSUE TITLE
Make English headlines consistent in upper / lower style

### ISSUE THREAD

**Issue by StefanZoerner** [isaqb-org/curriculum-foundation#246]
In the English table of contents, the headings are inconsistent with respect to upper and lower case.
Example from the start:

Legal Notice
List of Learning Goals
Introduction
What does a Foundation Level training convey? 
Out of scope
Prerequisites
Structure, duration and teaching methods

I did a little research, and learned that there are no binding rules, but there are styles. In the press, for example, Up-Stype and Down-Style (depending on the newspaper).
https://www.dailywritingtips.com/up-style-and-down-style/

In the Advanced WG we had the same issue, and opted for Up-Style. 

However, hardly any curricula have been adapted to this in our department. We only have a look at new and revised curricula.

**Comment by gernotstarke** [comment]
@alxlo decides capitalization

**Comment by gernotstarke** [comment]
Ok - then we follow the Advanced Level and go for an Up-style:

* uppercase for all substantives and verbs
* prepositions, articles may remain lowercase

**Comment by gernotstarke** [comment]
all changes in uppercase for headings go into the branch `#246-Up-style-for-headings`

**Comment by gernotstarke** [comment]
who wants to do similar things, should install this VS-Code extension:
https://marketplace.visualstudio.com/items?itemName=viablelab.capitalize

**Comment by martinweck** [comment]
Hi @StefanZoerner , hi @gernotstarke ,

I have just found your ticket. I suggest the following pull request: https://github.com/isaqb-org/curriculum-foundation/pull/345. So I simply looked how the text has been written right now and derived from that a hopefully consistent suggestion. Feel free to give comments in the pull request if you prefer another approach.
