### ISSUE TITLE
LG 2-5 generalize discussion about patterns and architectural styles

### ISSUE THREAD

**Issue by richard-wallintin** [isaqb-org/curriculum-foundation#248]
(This as another idea on how to reduce the curriculum scope/depth.)

This goal (2-5) lists a **lot** of super relevant patterns (as R3) and what is left as R1 is layers, microservices, pipes & filters and DI/DiP, which could be considered an "arbitrary" selection. To lift some weight, i propose:

* moving everything to R3 and only keep layering as R1.
  * yes, microservices would not be R1 anymore; since the curriculum tries not to be too narrow on standard 3-tier client server information systems. They are first class citizens in FLEX and CLOUDINFRA advanced modules.
  * i also see no reason to consider pipes & filters more or less relevant than CQRS, Event Sourcing or Hexagonal Architecture
  * DI/DiP is part of goal 2-6, no need for additional exposure here
  * Layered architecture though is a more ubiquituous concept and understanding it is (imo) the basis for understanding more advanced patterns and styles.
* **But** with a broader interpretation of layered architecture: hardware abstraction, phyical **and logical** seprataion of concerns:
  * adding https://martinfowler.com/bliki/PresentationDomainDataLayering.html as relevant link, because of the purely structural nature of layers (independent of deployment/distribution model)
  * and add two-(or-more-)dimensional layering, (technical + domain layering, nicely described by Carola [Lilienthal 2018] 6.3 and likely other sources), opening the mind for more advanced patterns

**Comment by gernotstarke** [comment]
One problem here is that several of the current exam questions relate to questions.

From a didactic viewpoint we like to communication several patterns and principles, not just layers.
