### ISSUE TITLE
LG 4-3: terminology "analysis" vs. "assessment"

### ISSUE THREAD

**Issue by mikesperber** [isaqb-org/curriculum-foundation#249]
LG 4-3 mentions "qualitative analysis" and "qualitative assessment" without saying what the difference between these two is. Moreover, the curriculum mentions "code analysis" - this may be confusing terminology. 

This should be clarified, or the two terms should be unified.

NB: The relvevant "A" in "ATAM" is for "analysis", not "assessment".

**Comment by mahboubagharbi** [comment]
In qualitative architectural assessment, we need both: 
Architecture analysis and assessment. After the analysis, there should be an assessment. However, the exam questions are about analysis. Therefore, I propose to include both analysis and assessment in the syllabus. The difference should be explained here. In the exam questions, we can limit ourselves to the analysis. 
Code analysis is a part of quantitave architecture analysis. This also needs to be made clear. 
If my suggestion is accepted, I would like adjust the syllabus and the exam questions.

**Comment by gernotstarke** [comment]
I personally object to this distinction, at least for foundation: My main reason is that we would need additional time in classes to explain the terms (and we would definitely need to add "evaluation" as a third).

Proposal to keep things simple and aligned with ATAM: Let's stick to "Analysis" only. Whoever needs to differentiate for whatever reasons might do so - but I doubt it adds any value to the curriculum if we include the disctinction to learning goals.

Second proposal: Let's explain the terms in the glossary and/or write a blogpost about the subtle nuances

**Comment by gernotstarke** [comment]
Next comment is about code analysis: This is DEFINITELY not only quantitative - as the compliance to coding style, the identification of potential security issues or other "quality-related" analyses are not about numbers.

**Comment by gernotstarke** [comment]
after discussion with @alxlo @programming-wolf @mikesperber and @gernotstarke we decided to remove the term "assessment" from the curriculum

**Comment by gernotstarke** [comment]
EN: assessment -> analysis
DE: bewertung -> analyse
