### ISSUE TITLE
LG 2-2: Terminology "white box" / "black box"

### ISSUE THREAD

**Issue by mikesperber** [isaqb-org/curriculum-foundation#250]
The usage of "white" and "black" here is potentially biased.  (On the other hand, deeply entrenched in SA architecture.) Here's a reference on the subject:

https://brand.citrix.com/application-guides/writing/unbiased-language/

We may consider replacing them by unbiased terms.

**Comment by gernotstarke** [comment]
I strongly object changing THIS terms here, as neither black- nor whitebox is any better than the other...

therefore, together with @alxlo, we decided to decline this proposal and close the issue.

**Comment by mikesperber** [comment]
Just cleaning up my own note on this, here's the ACM's stance on the subject:

https://www.acm.org/diversity-inclusion/words-matter
