### ISSUE TITLE
LG 1-7: Downgrade or delete

### ISSUE THREAD

**Issue by mikesperber** [isaqb-org/curriculum-foundation#251]
It's unclear what the exact difference between short-term and long-term goals, or what exactly the relevance for the architectural process is. Therefore, downgrade to R3 or (IMHO) delete.

**Comment by gernotstarke** [comment]
@alxlo and @gernotstarke decided to 

* remove the first bullet "explain long-term quality requirements and their differentiation from (short-term) project goals"
* downgrade the whole LG to R2
