### ISSUE TITLE
LZ 1-3 Software architecture in the lifecycle - set to R3 or remove

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#252]
The LZ 1-3 Software architecture in the software lifecycle should be set to R3 or removed. Even less relevant using agile approach

**Comment by gernotstarke** [comment]
The curriculum / LG covers the "software lifecycle", not any "development lifecycle".

After discussion with @alxlo @programming-wolf @mikesperber and @gernotstarke, we decided to leave it R2.

Also in agile approaches, architecture decisions can be long-lasting, therefore in our opinion this LG is important.
