### ISSUE TITLE
Prerequisites (e.g. Development and Test Questions) can be tested

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#257]
Make clear in the curriculum that prerequisites (e.g. Development and Test Questions) can be tested. 
Create associated mock exam questions

**Comment by gernotstarke** [comment]
@rhoadesre - the first line under "prerequisites" contains the exam-relevance!!

otherwise, we add a bullet point "fundamentals of software testing (e.g. unit- and acceptance testing)"

**Comment by alxlo** [comment]
Testing has been added. Exam relevance should have always been clear. The very first line on prerequisites states  "The iSAQB e. V. may check the following prerequisites in certification examinations via corresponding questions."
