### ISSUE TITLE
LG 2-4: Design and implement cross-cutting concepts - Principles

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#258]
It would be helpful to describe specific principles that would improve the implementation for specific cross-cutting concepts, e.g. idempotente IDs, best-practices for logging etc. These should not be implementation-specific (e.g. no frameworks, products, libraries etc.), but more general principles.

**Comment by gernotstarke** [comment]
@rhoadesre please provide example LG formulation for it...

**Comment by gernotstarke** [comment]
See also #259.

**Comment by rhoadesre** [comment]
I don't have specific examples or references; therefore, I closed the issue
