### ISSUE TITLE
Provide proposals what to cut if training last only 3 days instead of 4

### ISSUE THREAD

**Issue by sippsack** [isaqb-org/curriculum-foundation#260]
There are different approaches how to handle all the contents of the curriculum if the training last only 3 days:

* R1 topics are required, R2/R3 is optional and the attendees can choose
* send a reading guide/recommendations to the attendees in advance and treat some of the topics shorter
* ...

Idea: provide different variations as proposals to help trainers by deciding, what to cut

This must not be part of the curriculum, but maybe a blog post or a info at the iSAQB website

**Comment by gernotstarke** [comment]
@sippsack could you come up with a list of proposals for

- topics that could be removed from the curriculum
- topics that could be downgraded from R1/R2 to R3, therefore becoming purely optional

**Comment by gernotstarke** [comment]
after discussion between GS and AL we decided to remove this from the V2023 version.

@sippsack - please provide a wording-proposal for a blogpost, as we currently don't have any other medium where we could publish this.

**Comment by rhoadesre** [comment]
My personal candidates for removal or setting to R3 are as follows. 

1. LG 1-3: Understand software architecture as part of the software lifecycle (R2)
2. LG 1-6: Can explain the correlation between development approaches and software architecture (R1) - Covered in advanced classes
4. LG 1-7: Differentiate between short- and long-term goals (R1)
5. LG 2-1:  top-down and bottom-up approaches to design (R1)
6. LG 2-3: Identify and consider factors influencing software architecture (R1-R3) - make more general
7. LG 3-1: Explain and consider the quality of technical documentation (R1)
8. LG 3-9: Use documentation as written communication (R2)

I'm not saying that these are unimportant, but some are covered in advanced classes and some are simply less important than the other learning goals.

**Comment by gernotstarke** [comment]
* LG 1-3 has been discussed in #252 (and we decided to leave it as-is)
* LG 1-7 has already been adressed in #251 

* reducing LG 1-6 to R2 gets a +1 from me.
 
Personally I consider 2-1, most of 2-3, 3-1 and 3-9 actual core competencies of software architects, and would really like to have those remain R1.

I really doubt that we will come with a consensus on importance of topics, I consider the different customers and projects we're working in the source of that "evil": Most of the stuff in our curriculum **can** be important for some project or team...

Maybe we should keep the ultra-tight schedule - it has worked out for several years now...

**Comment by rhoadesre** [comment]
> Personally I consider 2-1, most of 2-3, 3-1 and 3-9 actual core competencies of software architects, and would really like to have those remain R1.
> 

To be clear, I also consider LG 2-1 and 2-3 core competencies and would leave them as R1. I would just reduce the number of R1 topics. For example, as part of LG 2-1, I was only referring changing "top-down/bottom-up approach" to R3. I would leave the rest of 2-1 I as is. I would also generally leave LG 2-3 as R1, but make it more general and not have so many R1 sub-topics.

LG 3-1 is important, just not as important as LG 3-2. I also emphasize (a lot!) that "form, content, and level of detail [should be] tailored to the stakeholders" in my classes. However, I still consider it a candidate for something that can be demoted to R3.

LG 3-9: Use documentation as written communication is simply too general for me and is already covered by LG 3-2. How would you create a test question for this blanket statement?

**Comment by gernotstarke** [comment]
What about making LG 4-3 and LG 4-4 both R3 only, as "analysis and evaluation" is covered in AWERT and IMPROVE...

most junior architects will not evaluate systems on their own, so imho we could safely defer these topics to the advanced level.

**Comment by mahboubagharbi** [comment]
We should cover in the foundation level the topics that will be asked in any advanced exam, regardless of the modules attended! Example: Quality tree and quality scenarios.

**Comment by gernotstarke** [comment]
Torn between to sides... either 

1. shorten the curriculum, and reduce stress on foundation trainings
OR
2. prepare people for advanced level.

My current opinion is 1 - as only less than 10% of people go for advanced, AND I can expect advanced architects to do some research on required topics.

Plus - quality tree and scenarios are covered in LG 4-2.

**Comment by mahboubagharbi** [comment]
This was just an indication of when to choose between topics. Some examiners point out foundation level topics during the interview. Regardless: I think feedback from the exams sub-working group on the curriculum would be valuable.

**Comment by ulibecker** [comment]
I would like to keep LG 4-3 as (partly) R2, as it currently is. Since we stress the importance of architecturally significant requirements and constraints, participants should have at lease some idea who to evaluate the architecture in that regard.

**Comment by ulibecker** [comment]
In addition, you can get advanced-level certified without attending AWERT and IMPROVE. An advanced-level certified architect should have learned at least the foundations of architecture evaluation.

**Comment by gernotstarke** [comment]
As I mentioned above, I'm clearly torn between two sides... In advanced exams, people have to know more than what's covered in FL, e.g. cloud scaling in some exams.

The foundation should NOT be considered sufficient to pass an advanced exam - but what the title says - a foundation where additional knowledge can be built upon.

We should have a working-group meeting for that discussion!!

**Comment by programming-wolf** [comment]
I'm also in favour of a working group meeting to discuss this. 

However, I also think that analysis/assessment of software architecture should remain in the curriculum. People might never get in touch with that topic in their day-to-day job, so at least pointing them towards that area should be part of the curriculum. Doesn't have to be ATAM, can be Mini quality attribute workshop, or just the basic concept of evaluating an architecture based on a few aspects.

**Comment by mahboubagharbi** [comment]
I suggest less design patterns but more focus on the architecture themes. I believe that the themes: 

    LG 1-3: Understand software architecture as part of the software lifecycle (R2)
    LG 2-1: top-down and bottom-up approaches to design (R1)
    LG 2-3: Identify and consider factors influencing software architecture (R1-R3) 
    LG 3-9: Use documentation as written communication (R2)

Absolutely should remain in the curriculum. 

Candidates for removal or setting to R3 are as follows: 
    LG 1-6: Can explain the correlation between development approaches and software architecture (R1) 
    LG 1-7: Differentiate between short- and long-term goals (R1)
    LG 3-1: Explain and consider the quality of technical documentation (R1)

I am in favor of a streamlined curriculum that includes more time for hands-on group work. The participants would like to experience more practice than theory in the training. Most have already read many books.

**Comment by mikesperber** [comment]
>     1. decide in 2023 how and where to streamline, and have another release 2024 (breaking our 2-year release cycle)

I'm all for that.

**Comment by sippsack** [comment]
Sorry, I'm late to this lively discussion. I didn't find any notifications in my inbox (maybe they have been in spam and are gone now). I have to check my github settings.

Thanks for all your suggestions. I'll try to consolidate them and come up with a wording proposal as Gernot asked for in October.

We can discuss it further in a face2face meeting. I am very curious to see if we can find an agreement.

**Comment by sippsack** [comment]
There won't be a face2face meeting in near future, I think. Therefore I will plan a few short remote meetings with two or three of you to discuss all the suggestions.

**Comment by mahboubagharbi** [comment]
Hello Falk, 

The discussion was a while ago ;-). I now suggest we start with the new curriculum and gain experience with it. At the end of summer / beginning of autumn we should take up the topic again. 

Regards, Mahbouba

**Comment by gernotstarke** [comment]
+1

**Comment by sippsack** [comment]
At least I get mail notifications for this issue now. I'll set a reminder in my calendar.

**Comment by rhoadesre** [comment]
+1

**Comment by gernotstarke** [comment]
I close this issue - as we shall not mix curriculum with training-organization:

In the curriculum, we concentrate ONLY on learning goals and terminology.
We leave it to trainers and/or training organizations to map this curriculum on their training
schedule - wether it's 3 days, 4 or even longer.
