### ISSUE TITLE
Different meanings for "qualitative assessment"

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#261]
The term "qualitative assessment" has two definitions and it is not clear which is meant in the curriculum. This should also be defined in the iSAQB glossary.

Possible meanings:
1) Qualitative assessment is the assessment of the architecture based on the quality attributes
2) Qualitative assessment is the subjective assessment of the architecture based on observation, interviews etc., which are not based on quantified information

**Comment by gernotstarke** [comment]
see also #249, we will remove the term "assessment" from the curriculum, and replace it by "analysis".

In German: Ersetze Bewertung durch Analyse

**Comment by gernotstarke** [comment]
completed
