### ISSUE TITLE
Cleanup Literature references

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#262]
see also #185

**Comment by mikesperber** [comment]
@gernotstarke Is there anything to do here?

**Comment by gernotstarke** [comment]
check if important new books are missing...

otherwise, this can also be closed. You decide.

**Comment by gernotstarke** [comment]
Just checked, imho our list is complete enough. If specific entries are missing, somebody needs to create specific issues for these!
