### ISSUE TITLE
functional and technical architectures (fachlich vs technisch)

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#263]
The terms "functional and technical" are used in multiple places in the curriculum. These terms should be clearly defined (in curriculum and/or glossary). It should also be decided if the topics should be exam relevant or not.
The topics occur in:
- "relevant terms" of "2. Design and development of software architectures"
- LG 2-2: Design software architectures
- LG 3-5: Explain and apply context view of systems

**Comment by gernotstarke** [comment]
LG 3-5 already adressed
LG 2-2 remove term "functional and technical architectures" from relevant-terms, otherwise leave LG 2-2 untouched

**Comment by gernotstarke** [comment]
LG 2-2: does not contain the terms "technical"
LG 3-5: differentiates between technical and business context (which is imho ok, terms need to be explained in glossary)

therefore, nothing to do.
