### ISSUE TITLE
LG 2-5: Add "Clean Architecture" (and related Onion-Arc, Hexagonal-Arch) to Ports-and-Adapters

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#265]
leave as R3

**Comment by mikesperber** [comment]
Also related: "Functional Core, Imperative Shell". Lots of articles on the web on this, here's one:

https://www.kennethlange.com/functional-core-imperative-shell/

**Comment by gernotstarke** [comment]
todo: mention term in LG 2-5 and add link to kennethlange-reference

**Comment by mikesperber** [comment]
@gernotstarke did this in b0e4fffce6cf920f3717499b8b9c1a046d59b517 (thx!), so I think this one can be closed.
