### ISSUE TITLE
create curated changelog for/of V2023

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#276]
see the [wiki](https://github.com/isaqb-org/curriculum-foundation/wiki), https://github.com/isaqb-org/curriculum-foundation/wiki

**Comment by programming-wolf** [comment]
You can write the Changelog now into CHANGELOG.md, it will be used for the release notes in GitHub. 
You can use markdown formatting.

**Comment by gernotstarke** [comment]
first version with most important changes has been written...
