### ISSUE TITLE
Formulate explicit criteria for examination questions

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#277]
remark: That discussion should be public - in contrast to the examination content!

Nevertheless - the starting point lies **within** iSAQB infrastructure: https://nextcloud.isaqb.org/apps/files/?dir=/foundation&openfile=47956

**Comment by alxlo** [comment]
Important, but IMHO currently not in scope for the curriculum.
Do we *want* to cover this topic in the curriculum?

**Comment by gernotstarke** [comment]
Criteria are not critical and don't give away answers.

But its beyond our current scope. Let's close the issue.
