### ISSUE TITLE
LG 1-10: Add machine-learning/AI and Cloud-native to system types

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#278]
both types of system radically differ from traditional approaches - and should at least be mentioned.

It's R3, therefore not critical for the examination.

**Comment by mikesperber** [comment]
I have to ask the naive question: How are they different?

The architecture of the  ML/AI projects I'm familiar with is determined by factors other than the ML/AI.

With "cloud-native", I think the term requires some definition. Are we talking about "AWS lambda" type architecture? PaaS?

**Comment by gernotstarke** [comment]
ML/AI: 
* Neural networks can be (and are sometimes) constantly trained, therefore behavior of such systems might change dramatically over time
* Decisions or proposals by ML are often not deterministic, and depend on training and training data
* Decisions might be biased, unfair or even wrong, depending on training data
* It's more difficult to deploy new versions, as you have additional dependencies
* Testing ML is way more difficult

Most likely organizations today deploy hybrid systems, consisting of a combination of traditional and ML software...

**Comment by gernotstarke** [comment]
Cloud-native: https://12factor.net/, completely vendor- and tool agnostic.

**Comment by mikesperber** [comment]
Fair enough, I'm all for it.

I should mention that when our clients say "cloud-native", they *always* mean the exact opposite, namely to couple the software architecture body and soul to cloud-provider-provided services. So we should specify what we mean.

**Comment by gernotstarke** [comment]
so for cloud-native, let's stick to the 12-factor definition, imho that's vendor-neutral (enough), there's even a https://www.cncf.io/ cloud native computing foundation, which makes for a nice reference together with 12factor.net

**Comment by gernotstarke** [comment]
For me it would be ok to include a more verbose description of the different types of it-systems, or at least provide these definitions within our glossary and then cross-reference from the curriculum.
