### ISSUE TITLE
Re-introduce some occurrences of term "quality"

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#283]
although we accepted PR #274 (from @mikesperber ) I suggest to re-introduce the term "quality" in a few LGs
(my own fault to accept the PR without checking close enough)

* LG 1-4
* LG 2-2

Opinions wanted :-)

**Comment by mikesperber** [comment]
The usage in LG 1-4 did not align with ISO 25010, so I'm against that.

I have no strong objection to re-introducing it in 2-2.

**Comment by gernotstarke** [comment]
done for 2-2. But I don't understand why you think that using the term in LG 1-4 it conflicts with ISO 25010...

**Comment by gernotstarke** [comment]
compromise for LG 1-4: I added a reference to LG 4-3 and LG 4-4
