### ISSUE TITLE
LG 2-3 (DE) one more potential gendering issue ("Kunde") 

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#291]
@programming-wolf (head of the diversity working group), please help:

"Kunde" is male, and mentioned in LG 2-3 (we could use Kund:in or switch to plural)

**Comment by programming-wolf** [comment]
Plural would have to be Kund:innen, too. 😉
I don't know the exact current wording, but I'd say let's go with plural, "Kund:innen", since we're also using "Architekt:innen", for example.

**Comment by StefanZoerner** [comment]
Don't think so. In this specific case, "Kunde" is an organization, not a person. 

Quote:
> Organisationsstruktur des Entwicklungsteams und des Kunden (R1)

I would have suggested "Kundenorganisation", but that duplicates the "organization" from "Organisationsstruktur".

**Comment by programming-wolf** [comment]
Well, can we just use "Firma" in this case?

**Comment by gernotstarke** [comment]
I really welcome input from the Advanced-Level Group(s), @StefanZoerner, highly appreciated.

"Firma" leaves out at least NGO's,  open source organizations and private persons. These might be the minority of "Kund:innen".

I go for "Auftraggeber:innen"

**Comment by mahboubagharbi** [comment]
Wie wäre es mit "Bedarfsträger"?

**Comment by gernotstarke** [comment]
ist maskulin, und klingt für mich gestelzt und wie aus dem Gesetzbuch :-(

**Comment by mahboubagharbi** [comment]
Ja. Ich finde "Kunde" am besten und aus meiner Sicht müssen wir die weibliche Form nicht nutzen.

**Comment by programming-wolf** [comment]
Dann wäre ich dafür, "Kundin" zu benutzen, da "Die Organisation".

**Comment by StefanZoerner** [comment]
I agree with Mahbouba and would say "Kunde". We also say "Kunde", even if it is Allianz Versicherung, for example. I imagine that is a special case. As with "Gast", for example. 

"Auftraggeber:innen" I also find ok, but it would be something different for me. Because it emphasizes the individuals (which might be ok though)

**Comment by gernotstarke** [comment]
ok - ich habe das auf Plural umformuliert, lautet jetzt "Organisationsstruktur von Entwicklungsteams und Kunden"

**Comment by programming-wolf** [comment]
Was ist mit "Auftraggebende"?

**Comment by gernotstarke** [comment]
done, PR geändert
