### ISSUE TITLE
References: New editions for [Bass+ 2012], [Lilienthal 2018], [Zörner 2015]

### ISSUE THREAD

**Issue by StefanZoerner** [isaqb-org/curriculum-foundation#297]
New editions have been published for some books.

[Bass+ 2012], new:
[Bass+ 2021] Len Bass, Paul Clements, Rick Kazman: Software Architecture in Practice. 4th Edition, Addison Wesley 2021.

[Lilienthal 2018], new:
[Lilienthal 2019] Carola Lilienthal: Langlebige Softwarearchitekuren. 3. Auflage, dpunkt Verlag 2019.

[Zörner 2015], new:
[Zörner 2021] Stefan Zörner: Softwarearchitekturen dokumentieren und kommunizieren. 3. Auflage, Carl Hanser Verlag 2021.

**Comment by gernotstarke** [comment]
added this to V2023

**Comment by mikesperber** [comment]
See above PR, that does exactly this.
