### ISSUE TITLE
LG 2-2: translation of "fachlich" / "domain-related"

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#303]
The following two lines are not consistently translated.
- "separate technical and domain-related elements of architectures and justify these decisions"
- "fachliche und technische Bestandteile in Architekturen trennen und diese Trennung begründen"
 
Proposed change to the German version: 
- "domänen-spezifische und technische Bestandteile in Architekturen trennen und diese Trennung begründen"

I prefer to change the German wording because I think changing the English version instead would lead to more confusion (e.g., "functional" or "busineses-related").

**Comment by gernotstarke** [comment]
PR #305 fixed this, so I close the issue
