### ISSUE TITLE
LG 1-6 demote to R2 (development approach and software architecture)

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#314]
as discussed in #260

**Comment by gernotstarke** [comment]
opinions?

**Comment by ulibecker** [comment]
Demoting to R2 is fine for me, but otherwise leave it as it is.

**Comment by alxlo** [comment]
> opinions?

Not strong ones.  I agree with @ulibecker

**Comment by mahboubagharbi** [comment]
> opinions?

ok

**Comment by rhoadesre** [comment]
Does demoting this to R2 save us any time in the class? It still could be exam-relevant.

**Comment by gernotstarke** [comment]
it does not necessarily save time, I personally spend MORE time on R1 topics than R2 (and tell people that certain R2 topics might occur in exam questions although we didn't cover those in trainings in-depth).

**Comment by gernotstarke** [comment]
do we get a majority do downgrade LG 1-6 to R3 (with consequences on the exam questions)?

**Comment by ulibecker** [comment]
-1
