### ISSUE TITLE
update reference ISO 25010 

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#317]
the ISO standard has been updated Nov 2022, I will crosscheck definitions and update the references accordingly

**Comment by ulibecker** [comment]
ISO 25010:2011 is still valid according to https://www.iso.org/standard/35733.html. Any idea when the successor will be released? Is it relevant for the upcoming curriculum release?

**Comment by gernotstarke** [comment]
https://www.iso.org/obp/ui#iso:std:iso-iec:25010:dis:ed-2:v1:en

> This second edition of ISO/IEC 25010 cancels and replaces the first edition of [ISO/IEC 25010:2011](https://www.iso.org/obp/ui#iso:std:iso-iec:25010:ed-1:en), which has been technically revised.

I assume that the original homepage has not yet been updated. Imho the updated version is MUCH better than the 2011 version (it includes safety, finally...)

Therefore I consider it relevant for the upcoming release...

**Comment by gernotstarke** [comment]
The page:
https://www.iso.org/standard/78176.html

is labeled "Preview" - but I consider it a vast improvement over the old ("productive") version from 2011, e.g. it now contains "safety" as a top-level attribute

**Comment by ulibecker** [comment]
Yeah, that is always a discussion point why safety only shows up in the "Quality in Use" model... still https://www.iso.org/standard/78176.html lists the status as "Stage 40.20", which means it has some way to go until it is officially released. So not even sure what year it will be, ISO standards take a lot of time... As we do not go into a lot of details about ISO 25010 in the curriculum, I think we don't have a strong dependency on the details of the standard. We could update the reference with a minor release when the new version is actually released.

**Comment by gernotstarke** [comment]
I'm quite happy with the additional (and imho improved) _content_ of this draft,
and will definitely update my slides and training material accordingly...

**Comment by gernotstarke** [comment]
added reference to ISO terms (which are free to read online), linked to this reference in LG 4-1

**Comment by gernotstarke** [comment]
see #327
