### ISSUE TITLE
LG 3-2 potential translation issue

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#319]
From @alxlo 

>"die Zugänglichkeit der Dokumentation" i would translate as "the accessibility of the documentation". 

See discussion here: https://github.com/isaqb-org/curriculum-foundation/pull/315

**Comment by Hruschka** [comment]
+1 for alxlo

**Comment by rhoadesre** [comment]
+1

**Comment by programming-wolf** [comment]
closed with #325
