### ISSUE TITLE
LG 2-3 clarify term „influencing factor“

### ISSUE THREAD

**Issue by hoch4** [isaqb-org/curriculum-foundation#320]
The term “influencing factors” should be clarified.

Based on the German version of the curriculum you may think, that influencing factors are a synonym for  constraints:
> Softwarearchitekt:innen können **Einflussfaktoren (Randbedingungen)** als Einschränkungen der Entwurfsfreiheit erarbeiten und berücksichtigen

From the English version one could conclude that influencing factors are something else than constraints: 
> Software architects are able to gather and consider c**onstraints and influencing factors** that restrict their decisions.

As far as I interpret the learning goal, the term “influencing factor” is a generic term for all influences: functional requirements, quality requirements, constraints (organizational, technical), trends, ...

**Comment by gernotstarke** [comment]
The title is completely misleading, the sub-goals are ok. Will change the title of the LG to:

DE: "Anforderungen erheben und berücksichtigen" (as "Anforderungen" includes "Randbedingungen")
EN: "Elicit and consider requirements"
