### ISSUE TITLE
where to put references?

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#34]
(1) shall we have a list of references at the end, 
or 
(2) shall we reference our [official references collection](https://leanpub.com/isaqbreferences) at https://leanpub.com/isaqbreferences

The latter would remove redundancy but make it a little more difficult for readers of the curriculum... any opinion?

---
#page:02-design/99-design-references.adoc

**Comment by p-goetz** [comment]
I personally tend to avoiding duplications, but that might be too developery of me. If we do that I think we should still have a section "References" that links to leanpub.

**Comment by programming-wolf** [comment]
Having the (big) references chapter at the end of the curriculum allows us to reference them (pun intended) from the "references" section of each chapter, so that a reader can click on one and is automatically moved to the particular entry in the last chapter.

**Comment by gernotstarke** [comment]
close this issue, we keep references (duplicated!!) at the end of the curriculum.

Usability is a higher priority than maintenance effort.
