### ISSUE TITLE
LG 4-1: add "e.g." to ISO-25010, and quote additional sources

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#357]
old:

* the concept of quality and quality characteristics (based on [ISO 25010]) 
* generic quality models (such as [ISO 25010])

new:
* the concept of quality and quality characteristics (based on e.g. [ISO 25010] or [Bass+2021]) 
* generic quality models (such as [ISO 25010], [Bass+2021], [Q42])

**Comment by gernotstarke** [comment]
prerequisite: [Q42] has been added to references:

* Q42 - The arc42 Quality Model, https://quality.arc42.org

**Comment by gernotstarke** [comment]
@mikesperber could you please ack or disagree with this... (it's the last issue before we release 2023...)

**Comment by alxlo** [comment]
I support this proposal.

**Comment by rhoadesre** [comment]
I'm fine with the new formulation

**Comment by mikesperber** [comment]
> @mikesperber could you please ack or disagree with this... (it's the last issue before we release 2023...)

Agree.
