### ISSUE TITLE
Fuzzy terminology in eng and german ("fachlich vs. domänenspezifisch)

### ISSUE THREAD

**Issue by Stephan673** [isaqb-org/curriculum-foundation#368]
LG 2-2 Deu/Eng

separate technical and domain-related elements of architectures and justify these decisions

This seems ok, but in the German Version we can find

fachliche und technische Bestandteile in Architekturen trennen und diese Trennung begründen
domänenspezifische und technische Bestandteile in Architekturen trennen und diese Trennung
begründen

For one of these sentences is no equivalent in the eng version.
Or in other words: What should be the difference of "fachlich" and "domänenspezifisch"? 
For me its the same.

KR
Stephan

**Comment by sippsack** [comment]
Thanks for your feedback. This seems like a copy/paste error and we should stick with "domänenspezifische und technische Bestandteile in Architekturen trennen und diese Trennung begründen" as in the english version

**Comment by Stephan673** [comment]
Hi,

thank you. Now its clear.

KR
Stephan

Von: Falk Sippach ***@***.***>
Gesendet: Mittwoch, 8. März 2023 09:33
An: isaqb-org/curriculum-foundation ***@***.***>
Cc: Stephan Christmann ***@***.***>; Author ***@***.***>
Betreff: Re: [isaqb-org/curriculum-foundation] Fuzzy terminology in eng and german ("fachlich vs. domänenspezifisch) (Issue #368)


Thanks for your feedback. This seems like a copy/paste error and we should stick with "domänenspezifische und technische Bestandteile in Architekturen trennen und diese Trennung begründen" as in the english version
