### ISSUE TITLE
Curriculum Structure - Align with Didactial Path (was: Trennung des Kapitals Qualität in "Qualitätsanforderungen" und "Architekturbewertung")

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#37]
Die Durchführung von den zwei Aktivitäten, "Qualitätsanforderungen klären" und "Architekturen Bewerten" sind sehr unterschiedlich und findet zu unterschiedlichen Zeitpunkten statt. Es wäre hilfreich die Themen in zwei Kapiteln zu trennen, sodass sie auch separat beschrieben und behandelt werden können.

**Comment by gernotstarke** [comment]
es sind ja nur 4 Lernziele - ich fände das etwas zu "klein" im Gegensatz zu den übrigen Teilen des Lehrplans, wenn wir diese vier noch auf 2x2 auftrennen würden.

**Comment by rhoadesre** [comment]
Ich habe den Kapitel noch mal angeschaut. Ich finde es gar nicht so schlimm, wenn es nur 2 LZ je Thema gibt. Die Lernhziele sind groß genug, dass sie getrennt behandelt werden können. Außerdem bin ich nach wie vor der Meinung, dass sie sehr unterschiedliche Themen sind, die auch zu unterschiedlichen Zeitpunkten behandelt werden.

**Comment by alxlo** [comment]
Hallo,

On 22.04.19 20:45, Roger Rhoades wrote:
> Ich habe den Kapitel noch mal angeschaut. Ich finde es gar nicht so
> schlimm, wenn es nur 2 LZ je Thema gibt. Die Lernhziele sind groß genug,
> dass sie getrennt behandelt werden können. Außerdem bin ich nach wie vor
> der Meinung, dass sie sehr unterschiedliche Themen sind, die auch zu
> unterschiedlichen Zeitpunkten behandelt werden.

And we have precedent. Das Werkzeugkapitel hatte auch nur zwei LZ.

Ich sehe in wenigen, klar definierten Lernzielen nicht unbedingt einen
Schwachpunkt.


Viele Grüße,

Alexander

**Comment by gernotstarke** [comment]
Ich finde, das sollten wir in der Gruppe (MV?) mal zusammen diskutieren. Aktuell befinden wir uns halt mitten in einer Abstimmung - da wäre es etwas komisch, wenn wir jetzt eine größere strukturelle Änderung vornehmen würden, oder?

**Comment by gernotstarke** [comment]
Status 16. Mai 2019 (MV): Gruppe hat beschlossen, das aktuell NICHT zu trennen, sondern ggfs. für 5.x oder später im Rahmen der generellen Struktur in grösserem Kontext zu diskutieren.

**Comment by mikesperber** [comment]
Das Thema "Qualität" war für uns auch das Hauptproblem beim Design unserer Foundation-Schulung.

Daß "Qualitätsanforderungen" und "Architekturbewertung" sich in einem gemeinsamen Abschnitt befinden, finden wir genau wie Roger problematisch. 

Das zugrundeliegende Problem sehen wir aber leicht anders: Das Thema "Qualitätsanforderung" taucht im Curriculum sehr oft auf - viel öfter als "Nicht-Qualitätsanforderung". Die Abgrenzung beider Arten von Anforderungen ist problematisch und m.E. nicht hilfreich.

Vor allem aber verdienen unserer Ansicht nach die "Nicht-Qualitätsanforderungen" ebenfalls adäquate Abdeckung im Curriculum. Dann würden aus den beiden Themen nämlich "Anforderungsmanagement" und "Architekturbewertung" und es würde (hoffentlich) noch offensichtlicher, daß beide nicht unter das gleiche LZ gehören.

**Comment by alxlo** [comment]
Volle Zustimmung an @mikesperber. Im Foliensatz ist das schon soweit berücksichtigt, dass es ein Kapitel "From Requirements and Influencing Factors (=context, external constraints) to Quality Goals and Design Constraints" gibt, was recht weit vorn einsortiert ist. Qualitätsanforderungen und -modelle erst ganz zum Schluß zusammen mit der Architekturbewertung zu bringen ist deutlich zu spät. Außerdem müssen wir bei allen Anforderungen sauber unterscheiden: beziehen sie sich auf das IT-System, auf die Architektur oder auf den Entwicklungsprozess. Die bloße Unterscheidung in FA und QA greift IMHO zu kurz.

Ich bin ein großer Verfechter des Modells von Hofmeister et al [1], da es eine weitgehendere Unterscheidung trifft und aussagt, das aus Anforderungen an das IT-System und Kontext (mandatierte Designentscheidungen, Anforderungen an das Projekt, ...) die architekturrelevanten Anforderungen abgeleitet werden.

[1] [Hof2007] Hofmeister, C., Kruchten, P., Nord, R. L., Obbink, H., Ran, A., & America, P. (2007). A general model of software architecture design derived from five industrial approaches. Journal of Systems and Software, 80(1), 10

**Comment by gernotstarke** [comment]
postponed,  (as discussed in FLWG-Conference-Aug-8th-2020)

**Comment by alxlo** [comment]
**State of discussion at 2022/05**

- LZ 4-1 and 4-2 are closely related to LZ 2-3 but appear very late in the curriculum.
- Trainers **can and should** choose to teach LZ 4-1 and LZ 4-2 early in the course
- However, quite a number of slide decks deal with this topic very late in the course for a number of (valid) reasons. And let their didactic
- This is not good.

- This could be mitigated by structuring the curriculum along a more appropriate didactic path (possibly there are other similar problems elsewhere in the curriculum).
- Restructuring the curriculum is costly

**Comment by alxlo** [comment]
### Update on Curriculum Structure Proposal

- With commit [ad2ba40 ](https://github.com/isaqb-org/curriculum-foundation/commit/ad2ba40b8b67fae086225715a278847a41aaa51e) we've sorted things inside Chapter 4
(Software Architecture and Quality --> Analysis and Assessment)
- With commit https://github.com/isaqb-org/curriculum-foundation/commit/ad2ba40b8b67fae086225715a278847a41aaa51e we've sorted the LGs into a new chapter structure according to our meeting in Munich (February 2024). This was intended as a first proposal and **we didn't** ...
  - discuss the sequence of LGs inside those chapters yet
  - whether we are really satisfied with the new places for LGs
  - which LGs to merge/consolidate/eliminate

Please find attached a visualization of those changes so far and a second visualization of @gernotstarke and @alxlo 's proposal how to continue from there as the result of our workshop in Dresden on 2024-04-08.  

[2024-04-08_a_Curriculum_2025_Structure_commit_798e052.pdf](https://github.com/isaqb-org/curriculum-foundation/files/14944393/2024-04-08_a_Curriculum_2025_Structure_commit_798e052.pdf)

[2024-04-08_b_Curriculum_2025_Structure_proposal_after_workshop.pdf](https://github.com/isaqb-org/curriculum-foundation/files/14944396/2024-04-08_b_Curriculum_2025_Structure_proposal_after_workshop.pdf)

**Comment by gernotstarke** [comment]
done with FLWG meeting May 2nd 2024 (Stuttgart)
