### ISSUE TITLE
Why was "functional architecture" deleted?

### ISSUE THREAD

**Issue by Stephan673** [isaqb-org/curriculum-foundation#371]
Hi,

I do not understand, why the concept and terminology of a functional/technical architecture (fachliche/technische Architektur) was deleted (Chapter 2. Relevant terms).

The 2 step concept where the functional architecture will be created/structured first to get a keen understanding of the problem space/domain (what should the system do) and a second step of technical architecture (how should it be technically realized) is essential.
Why was that deleted? 

Thanks
Stephan

**Comment by mikesperber** [comment]
The relevant PR is #304, which contains some discussion.

PS: I'll add that "functional architecture" clashes with the Advanced FUNAR curriculum titled "Functional Software Architecture".

**Comment by Stephan673** [comment]
Hi,

ahhh...i understand. I agree. 
However, the concept is therefore also lost.
Why not to call it "domain-specific-architecture" or "business-architecture"?

**Comment by gernotstarke** [comment]
The collection of "relevant terms" shall collect terms that appear in learning goals...

The term "functional architecture" does not appear in any LG, therefore mentioning it would be misleading.

The distinction between "domain" and "technology" is covered in "separation of concerns", e.g. LG 2-2 and LG 2-6.
