### ISSUE TITLE
LG 02-02 (V2025) LG 2-3: Remaining translation inconsistency "factors" vs "requirements"

### ISSUE THREAD

**Issue by ulibecker** [isaqb-org/curriculum-foundation#377]
The title of LG 2-3 still contains a translation inconsistency:

German: Anforderungen klären und berücksichtigen können
English: Identify and Consider Factors Influencing Software Architecture

Proposal: Change English LG Title to "Clarify and Consider Requirements"

**Comment by sippsack** [comment]
This was already adressed in #369. But this got bigger and is targeted for after release v2023. 

I suggested fixing the inconsistency the other way around:

"Einflüße auf Softwarearchitektur klären und berücksichtigen."

**Comment by gernotstarke** [comment]
duplicate, therefore closing this one
