### ISSUE TITLE
LG 2-5 (DE version), potentially misleading formulation

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#380]
current:
```
Observer (Beobachter): ein Produzent von Werten benachrichtigt eine zentrale Vermittlungsstelle, bei der sich Interessenten (Consumer) registrieren können, um über Änderungen benachrichtigt zu werden.
```
sounds like the observer is the producer... but in reality it's the consumer that's observing something.
Proposal:

Observer (Beobachter): ein Produzent von Werten benachrichtigt eine zentrale Vermittlungsstelle, bei der sich Interessenten (Observer, Beobachter, Consumer) registrieren können, um über Änderungen benachrichtigt zu werden.

**Comment by mahboubagharbi** [comment]
Ja Gernot, du hast recht 👍

**Comment by ulibecker** [comment]
What is the source of the "zentrale Vermittlungsstelle" / "switchboard"? IMO this is just one possible implementation. Proposal:

Observer (Beobachter): ein Interessent (Observer, Beobachter, Consumer) registriert sich, um bei Änderungen eines Objekts benachrichtigt zu werden
Observer: an interested party (observer, consumer) registers to be notified of changes to an object
