### ISSUE TITLE
Definition of "Qualitative"

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#389]
I think there is an ambiguity relating to the term "qualitative", as in "qualitative analysis". 

There are several different meanings in different sources and we should specify to which we are referring to when we refer to "qualitative".

**Measurement of Quality**
- "of, relating to, or involving quality or kind"
- "relating to how good or bad something is"
- "pertaining to or concerned with quality or qualities."

**Subjective information**
- "based on information that cannot be easily measured, such as people's opinions and feelings, rather than on information that can be shown in numbers"

**Characteristics**
- "Anything that's qualitative has to do with the characteristics or features of something, rather than its quantity"
- "descriptions or distinctions are based on some quality or characteristic rather than on some quantity or measured value."

**Comment by mikesperber** [comment]
@rhoadesre I agree. In PR #388, I tried to specify what the intended meaning is. (There aren't any other uses of the word.)
