### ISSUE TITLE
LG 01-05 (V2925) Delete LG "Understand Software Architecture as Part of the Software Lifecycle" or rename and move to chapter 2.

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#392]
- This is a good candidate to delete from the curriculum. In my opinion, the content doesn't have much to do with the software lifecycle and this relation only causes confusion, especially in agile environments. 
- If this learning goals should be kept, then change the name to "Understand how Changes to the Influencing Factors have Consequences on the Software Architecture" and move to chapter 2. The content can remain unchanged.

**Comment by gernotstarke** [comment]
FLWG:

* delete V23-LG-1-3
