### ISSUE TITLE
LG 01-06 (V2025) Delete LG "Differentiate Types of IT Systems"

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#393]
This seems to be a random set of types of systems that also overlap with one another.
What characteristics make these systems different from one another?
Why do architects need to differentiate between these types of systems?

**Comment by alxlo** [comment]
Maybe integrate this with LG 02-02: Identify and Consider Factors Influencing Software Architecture (R1-R3), former LG 2-3

**Comment by mikesperber** [comment]
+1 @rhoadesre

**Comment by gernotstarke** [comment]
I'd like to keep these terms ("batch-system, interactive-system, mobile-system...") in the curriculum, as they can have major impact, e.g. on technology stacks/choices.

Younger people often don't know the term "batch" any longer, but it's still relevant in practice.

Therefore, keep the terms, but include the LG into LG-02-02, previously 2-3.

**Comment by mikesperber** [comment]
If we keep them, we need to at least have an idea as to how the distinction is architecturally relevant - ideally with published references, alternatively with an entry in the glossary. (I sure don't.)

**Comment by rhoadesre** [comment]
I would like to make this topic at least an R3 then.

**Comment by gernotstarke** [comment]
it's R3 since ages...

**Comment by gernotstarke** [comment]
FLWG decided to delete

**Comment by mikesperber** [comment]
Done per above commit.
