### ISSUE TITLE
Rename Chapter 2 "Software Architecture and Requirements" to "Requirements and Constraints"

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#394]
The content of the new "Requirements" chapter goes beyond just requirements to include stakeholder concerns (new) and constraints (currently called influencing factors), as well as trends and business and project goals.

**Comment by alxlo** [comment]
What do you consider "external" and from which perspective? (Organizational or system)

**Comment by rhoadesre** [comment]
> What do you consider "external" and from which perspective? (Organizational or system)

We can delete "external". I was referring to things that are not in our responsibility or control, e.g. requirements, laws and regulations, etc.

**Comment by mikesperber** [comment]
I'd classify all of these as "requirements".

**Comment by rhoadesre** [comment]
Summary: all requirements are stakeholder concerns or constraints, but not constraints and stakeholder concerns are required / requirements.

Stakeholder concerns and constraints are not necessarily required, but could have an impact on the architecture. The stakeholder concerns and constraints may not even be specified, still have an impact on the architecture. For example, a large, conservative company has a very big organizational hierarchy. This will probably not be specified, but still has an impact, for example, on the time it takes to make decisions. Stakeholder concerns may not even be conscious concerns. For example, a developer fears that they may lose their job if an old system is replaced with new technologies. They may not even be aware that they have this fear, but it still impacts us because they may not be as willing to support our work. They may even consciously or unconsciously work against us.

**Comment by mikesperber** [comment]
I'm fuzzy on the language here. What does "constraints are not [...] required" mean? It sounds to me as though it's OK to ignore them.

**Comment by gernotstarke** [comment]
FLWG: Requirements and Influencing Factors

**Comment by sippsack** [comment]
FLWG: we discussed again and decided on: "Requirements and Constraints"

**Comment by gernotstarke** [comment]
changed the issues' title to reflect the decision!

**Comment by gernotstarke** [comment]
The chapter naming is now "requirements and constraints", but the folder is called "02-requirements" to allow shorter references within adoc.
