### ISSUE TITLE
LG 02-02 (V2025) Rename and restructure LG "Identify and Consider Factors Influencing Software Architecture" to "Identify External Constraints and their Impact on the Software Architecture"

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#396]
- The entire chapter (should) cover different influencing factors on the software architecture, including requirements, stakeholder concerns, and constraints.
- Change "Software architects are able to clarify and consider requirements (including constraints that restrict their decisions). They understand that their decisions can lead to additional requirements (including constraints) on the system being designed, its architecture, or the development process." to "Software architects are able to clarify and consider constraints that impact the architecture being designed or the design and development process. Architects understand that their decisions may also have an impact on the constraints."
- Remove "Product-related requirements such as functional and quality requirements". These are now addressed in a separate learning goal.
- Reduce the details of the constraints and / or drastically reduce the number of constraints that are exam-relevant.
- The section referring to trends can either be kept under constraints or moved to their own learning goal (R3).

**Comment by gernotstarke** [comment]
@rhoadesre please check

**Comment by rhoadesre** [comment]
FLWG: Rename to heading to "Identify and Consider Requirements and Constraints (R1-R3)"

**Comment by gernotstarke** [comment]
added constraints to title
