### ISSUE TITLE
Separate the learning goals pertaining to architecture principles and architecture patterns into its own chapter.

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#398]
Separating architecture principles and architecture patterns into its own chapter helps to reduce the size of the chapter relating to architecture design. Furthermore, unlike the other topics in the architecture design chapter, there are "catalogs" of both principles and patterns in the internet that can be used as input to the design decisions.

**Comment by gernotstarke** [comment]
conflicts with the agreed-upon new structure (architecture-activities).

Content belongs to chapter  3 (Design and Development of Software Architectures)

**Comment by rhoadesre** [comment]
> conflicts with the agreed-upon new structure (architecture-activities).
> 
> Content belongs to chapter 3 (Design and Development of Software Architectures)

Isn't that just a matter of wording to convert them into activities? The chapters could be called "Selecting and using design patterns" / "Selecting and using architecture principles". Admittedly, they would be subsets of the design process.
