### ISSUE TITLE
setup automatic build 

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#4]
with travis, circle-ci or a similar.

**Comment by p-goetz** [comment]
@gernotstarke, this repository is not open source as far as I understand. That means that we might need a paid plan with the mentioned CI providers. Do you have experience which we should use? If not I will start evaluation and comparison.

**Comment by gernotstarke** [comment]
open source with restricted commit/push access…

open-source CAN contain copyrighted content. Imho we can therefore start with a free plan!

Members of the FLWG will get write/commit/push access and will be able to accept/deny Pull Requests.

ok?

Gernot

**Comment by p-goetz** [comment]
Done with Travis CI. The build is being triggered with every push to master and will create a Draft release in GitHub that is visible to collaborators. We can also add final releases by updating .travis.yml
