### ISSUE TITLE
LG 03-11 (V2025) Combine the learning goal regarding deployment principles with the other learning goal regarding principles

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#401]
Combine the learning goal "Know Fundamental Principles of Software Deployment" with the other learning goal relating to principles. Keep these principles as R3.

**Comment by alxlo** [comment]
IMHO Deployment should become part of LG 03-08 [previously LG 2-04]: Design and Implement Cross-Cutting Concepts (R1)

**Comment by rhoadesre** [comment]
2024-05-02: FWG
- The two learning goals will remain separate, but the LG regarding deployment will be renamed so that primary topics isn't about principles, but about deployment in general

**Comment by gernotstarke** [comment]
has been done
