### ISSUE TITLE
LG 03-08 (V2025) Rename "Cross-Cutting Concepts" to "Cross-Cutting Concerns".

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#402]
In English, "Cross-Cutting Concerns" is **_far_** more common.

**Comment by rhoadesre** [comment]
FYI: 

I searched the books that I own and found dozens of books that mention "cross-cutting concerns" at least once. 

The only books I found with "cross-cutting concepts" are the books from Gernot Starke. 

A couple of books referred to them with different terms such as "cross-cutting architecture characteristics" or "cross-cutting requirements".

The books that I found that mentioned "cross-cutting concerns" multiple times or even had chapters or sections dedicated to cross-cutting concerns are the following:

Architecture Patterns by Pethuru Raj
Automative Embedded Systems Handbook by Nicolas Navet
Basiswissen Für Softwarearchitekten - Gharbi, Starke
Bridging the Gap between Requirements Engineering and Software Architecture - Azadeh Alebrahim
C4 Model by Simon Brown
Clean Architecture by Robert C. Martin
Clean Code by Robert C. Martin
Cloud Native Patterns by Cornelia Davis
Continuous Architecture in Practices by Murat Erder (refers to them mostly as Cross-Cutting Requirements)
Fundamentals of Software Architecture by Neal Ford (refers to them mostly as Cross-Cutting Architecture Characteristics)
Mastering API Architecture by James Gough
Microservices in Action by Morgan Bruce
Microservices Patterns by Chris Richardson
Minimalist Architecture by Bredemeyer
Software Architect's Handbook by Joseph Ingeno
Software Architecture for Busy Developers by Stephane Eyskens
Software Architecture for Developers by Simon Brown
Software Architecture in Practices by Len Bass
Software Architecture The Hard Parts by Neal Ford
Spring Microservices in Action by John Carnell
Strategic Monoliths and Microservces by Vaughn Vernon

**Comment by gernotstarke** [comment]
FLWG: replace concepts by concerns where wording is appropriate.

DE. Querschnittsthemen

**Comment by gernotstarke** [comment]
done with commit by @mikesperber

**Comment by mikesperber** [comment]
Done as per above commit.

**Comment by gernotstarke** [comment]
bad German wording, see #456
