### ISSUE TITLE
LG 03-11 und LG 03-12 (V2025) Combine learning goals "Can Explain the Correlation between Development Approaches and Software Architecture" and "Select and Use Approaches and Heuristics for Architecture Development".

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#403]
- Either combine these two learning goals or separate them so that one is focused on the impact of the iterative approach on software architecture and the other contains the other approaches. 
- Personally, I think all of the approaches should be R3 goals. The agile and DDD approaches are covered by the respective advanced classes. The other approaches are very subjective or, in my opinion, not concrete enough to form a basis for developing a software architecture. 
- It would be really helpful to find resources that describe concrete approaches specifically for developing software architectures, but I'm not aware of any specific sources.

**Comment by gernotstarke** [comment]
FLWG:
* move content of v23-LG-2-1 to V23-LG-1-6 concerning "iterative, incremental"
* remove iterative from v23-LG-2-1
