### ISSUE TITLE
LG 04-04 und LG 04-05 (V2025) Expand on LG "Explain and use Architectural Views" (some points are already in the curriculum) and consolidate LG "Explain and Apply Context View of Systems" into this learning goal.

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#404]
**Proposed new text:**

- Software architects are able to use the following architecture views:
  - Context View
    - Describes the external view of the system, including external interfaces to neighboring systems, users, inputs, and outputs
  - Building Block View
    - Describes the internal view of the system, including internal building blocks (components, packages, data structures, libraries, frameworks, etc.), relationships between those building blocks, building block structures and decomposition, etc.
  - Runtime View
    - Describes the dynamic behavior of the system and the interaction between building blocks at runtime.
  - Deployment View
    - Describes the hardware and technical infrastructure as well as the mapping between software buidling blocks and deployment artefacts onto the infrastructure.
- Software architects understand that additional views or a combination of views can be necessary to communicate the architecture to the stakeholders and satisfy their concerns, for example:
  - Additional views, e.g., Data view, Security view, Interface view, etc.
  - View combinations, e.g., Building Block and Runtime views, Context and Deployment views, etc. 
- Software architects are able to differentiate between business and technical views of the system. They understand that the responsibility for the business view of the system may differ depending on the organizational environment (e.g., project and roles).

**Comment by gernotstarke** [comment]
FLWG: @gernotstarke proposes a formulation for the LG and adds reference(s), e.g. woods/rozanski, see #422

**Comment by gernotstarke** [comment]
This will be the new **LG-04-05**, and the current LG-04-06 will be merged into LG-04-05.

(as 4-04 is already taken by 404...)

The other numbers in 04 will be squeezed.
