### ISSUE TITLE
LG 1-8: remove third sub-goal "can formulate implicitly..."

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#408]
in my opinion this formulation somewhat contradicts the goal itself.

Removal would make the whole LG better, imho.

**Comment by mikesperber** [comment]
@gernotstarke Could you be more specific as two which wording you want to remove? LG 1-8 has only two sub-goals AFAICS and I can't find "formulate implicitly" anywhere.

**Comment by gernotstarke** [comment]
sorry - that was a version conflict between my (local) build and the official version. Closing issue.
