### ISSUE TITLE
LG 03-04 ?? (V2025) rewrite the LGs for coupling

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#415]
differentiate between at least the following categories of coupling:

* static and dynamic coupling, as explained in [Ford+21]
* efferent and afferent coupling
* other types of coupling (e.g. hardware/infrastructure, temporal, data, data-structure, content etc)

**Comment by mikesperber** [comment]
@gernotstarke What Is [Ford+21]?

**Comment by mikesperber** [comment]
Aren't efferent and afferent coupling *metrics*?

https://en.wikipedia.org/wiki/Software_package_metrics

**Comment by mikesperber** [comment]
I'm all for clarifying what we mean by "different types of coupling"

**Comment by gernotstarke** [comment]
> Aren't efferent and afferent coupling _metrics_?
> 
> https://en.wikipedia.org/wiki/Software_package_metrics

Yes Mike, one can measure these types of coupling (incoming, outgoing)... at least in theory. In practice, static versions of both can be measured, if they occur at runtime, you can only count calls in your logfile :-)

I like the distinction "who depends on me" and "who am I dependent on"...

**Comment by gernotstarke** [comment]
> @gernotstarke What Is [Ford+21]?

"**The Hard Parts**": [Ford+21] Neal Ford, Mark Richards, Pramod Sadalage und Zhamak Dehghani: Software Architecture: The Hard Parts. Modern Trade-Off Analyses for Distributed Architectures. OReilly 2021.

**Comment by alxlo** [comment]
> I like the distinction "who depends on me" and "who am I dependent on"...

Furthermore I like the distinctions:

- When does this dependency has to be fulfilled? (binding, compile time vs run time)
- Is this dependency visible in code? (depending on chosen implementation techniques)
- Is this dependency aligned with the actual dependency from the domain? (if applicable)
- What is the **mode** of this dependency? (time, cause-effect, structure, technology, organizational, technology, ...)
- Is it uni or bi-directional?
- Is it "strong" or "weak"? (Yes, that's hard to quantify. But most people will agree that inheritance and structural coupling are "strong" while coupling by events/messaging is "weak".)
- maybe some more ...

**Comment by mikesperber** [comment]
What would we suggest people *do* with this distinction?

**Comment by alxlo** [comment]
> What would we suggest people _do_ with this distinction?

Let them consider how this kind of coupling affects the qualities (especially maintainability, flexibility, understandability, testability, and analyzability) of their software system and its architecture and how changing them could benefit in achieving desired qualities or at least what kind of trade-offs they pose.

**Comment by gernotstarke** [comment]
those Microservice fanboys who still believe that getting rid of compile-time dependencies will make their lives easier... because they forgot to consider the consequences on dynamic coupling.

**Comment by mikesperber** [comment]
FLWG: Do this, with @mikesperber 's suggestion
