### ISSUE TITLE
LG-05-02: List specific architecture metrics

### ISSUE THREAD

**Issue by mikesperber** [isaqb-org/curriculum-foundation#431]
Candidates:

- number of static dependencies
- size and number of interfaces
- number of building blocks involved in changes
- number and span of cyclical dependencies
- number of architecture-pattern violations

**Comment by mikesperber** [comment]
Cf. book on [Ford 21] ("The Hard Parts").

**Comment by rhoadesre** [comment]
A couple of more ideas from: 
https://medium.com/oolooroo/metrics-for-software-architects-and-designers-25b736a17a99

Average Component Dependency (ACD): Measures how many other components a given component depends on. Lower values are preferred as they suggest a more modular architecture.

Propagation Cost (PC): Quantifies how a change in one component might propagate to other components. Ideally, this should be minimized to ensure localized changes. 
[Roger] Not sure how this would be measured other than through dependencies

Structural Debt Index (SDI): A composite metric that captures the overall architectural debt. Higher SDI values can hint at increased maintenance costs in the future.
- [Roger] Not sure how this would be measured, other than e.g., number, effort, or story points of backlog items pertaining to architecture debt

Maintainability Index (MI): An amalgamation of various metrics like cyclomatic complexity, lines of code, and comments. MI offers a snapshot of the code’s maintainability. Higher values are better, with values below 10 indicating low maintainability.

Cyclomatic Complexity: Measures the number of linearly independent paths through a program’s source code, providing insight into the code’s testability and maintainability.

Depth of Inheritance: Reflects the inheritance levels in object-oriented programs. A deeper inheritance tree might lead to more complexity and reduced modularity.

**Comment by mikesperber** [comment]
FLWG meeting on May 21 agreed that longer lists of metrics should go in the glossary, and clarified the list in the above PR #450.

@rhoadesre Could you review?

**Comment by rhoadesre** [comment]
> FLWG meeting on May 21 agreed that longer lists of metrics should go in the glossary, and clarified the list in the above PR #450.
> 
> @rhoadesre Could you review?

I'm confused. Exactly what should I review?

**Comment by mikesperber** [comment]
> I'm confused. Exactly what should I review?

#450

**Comment by mikesperber** [comment]
@gernotstarke, @rhoadesre Can we close this? PR #450 was merged a while ago.

**Comment by gernotstarke** [comment]
yes
