### ISSUE TITLE
add references for API patterns and API design

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#436]
Especially the pattern collection from Prof. Zimmermann et. al seems worth adding.

**Comment by gernotstarke** [comment]
* Zimmermann+22
* Geeway-2021

**Comment by mikesperber** [comment]
A few references were removed, notably Newman's book and the CUPID blog post. Rationale?

**Comment by gernotstarke** [comment]
I'll check - that was an error and NOT deliberate... both references are useful imho.

**Comment by gernotstarke** [comment]
both CUPID and Sam Newman are still present in the references. Therefore, I close this issue as resolved.

**Comment by mikesperber** [comment]
> both CUPID and Sam Newman are still present in the references. Therefore, I close this issue as resolved.

Ah, sorry - I confused the AsciiDoc dash at the beginning of the line with a minus sign from a patch.
