### ISSUE TITLE
add a "DRAFT" section on the public download site

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#441]
let's create a draft- or "upcoming" section on the public.isaqb.org, graphically distinguished from the other downloads.

In AsciiDoc, there's a nice admonition feature, which we could use.

**Comment by programming-wolf** [comment]
We can link to the release candidate site, which already exists. ☺️ (IF you build a new release candidate)

**Comment by programming-wolf** [comment]
But I'm not sure if that's information people are that much interested in? Might be that there is no target audience for this feature.

**Comment by gernotstarke** [comment]
about 100+ trainers for Foundation level, and they all should be able to download draft versions as early as possible...
I thought that the public.isaqb.org would be the perfect URL for that purpose.

I just hat Mirko send out an advance-notice with our change-schedule to TP and trainers...
the next installment of our progress-reports will be a graphical overview, which could also be contained
in the draft-section of that site...

**Comment by programming-wolf** [comment]
Ok perfect. Then we'll blow up the release candidate page of the foundation level with all infos and images and link there from the public page.

**Comment by gernotstarke** [comment]
@programming-wolf - I need a little support here. We want to give interested people a chance to preview our upcoming changes, without officially releasing stuff yet.

something like:

```
==== Current Official Version 2023 (valid from April 1st, 2023)
* https://public.isaqb.org/curriculum-foundation/[**Foundation Level Curriculum** (PDF and html)]

==== Preview of Upcoming Version 2025 (DRAFT)
This is a preview of the upcoming version 2025. Please expect changes, structurally stable version can be expected around October 2024.
* <no idea where to link to...>

```

**Comment by programming-wolf** [comment]
Yup, I'll do it tomorrow.

**Comment by gernotstarke** [comment]
or we schedule a brief zoom-meeting on Friday 26th
