### ISSUE TITLE
create a graphical overview of changes between 2023 and 2025

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#442]
@alxlo has done a fantastic job in preparing this - but we need to update to the latest version, create a pdf / svg / png from it and include it in our migration guide #443

**Comment by gernotstarke** [comment]
comments welcome!

**Comment by programming-wolf** [comment]
Hm. I looked at it and here's my first impression:

- it is _huge_ I can't grasp the content by just looking at it, I have to zoom in, and then I barely see anything else. 
- To reduce the size of the image, maybe you can leave out all the chapters that didn't change anyway? That'd be 15+ items less. 
- It would be great to have all boxes at the same size, left aligned, for a much calmer and clearer image

Positives: It's great to see how all the chapters changed, moved, etc. I'm sure that it will help training providers a lot to redesign their slide decks.

**Comment by gernotstarke** [comment]
![Image](https://github.com/user-attachments/assets/8c9697fb-c282-4e63-bf02-ad4526efa682)

**Comment by gernotstarke** [comment]
awaiting feedback from trainers - therefore keeping issue open

**Comment by sippsack** [comment]
I had some concerns (formatting, missing notation, …) with the first version but the second version from today looks very good now.

**Comment by gernotstarke** [comment]
Then let's call it "good enough for now"
