### ISSUE TITLE
LG 1-3 Replace "Software Lifecycle" with "Software Development Lifecycle"

### ISSUE THREAD

**Issue by michaelpog** [isaqb-org/curriculum-foundation#444]
In my view, the term "Software Lifecycle" is ambiguous.
Software Development Lifecycle (SDLC) is much more common in the industry and usually implies **all** the phases from planning, design, implementation, testing, and evolution, which is what a software architect is involved in.

When I read this title, I asked myself why that author specifically chose the wording "Software Lifecycle" instead of SDLC.
What is the importance of this distinction for a candidate for this training?
As a candidate who took this training and as a trainer, it threw me off and created unnecessary confusion.

I suggest replacing "Software Lifecycle" with "Software Development Lifecycle" to make it clear and unambiguous.

**Comment by mahboubagharbi** [comment]
I have a different perspective. The software life cycle includes production, acceptance, and maintenance, which are not always part of the software development process....

**Comment by Hruschka** [comment]
+1Product Lifecycle would be an even more modern word.Von meinem iPhone gesendetAm 07.05.2024 um 20:14 schrieb Mahbouba Gharbi ***@***.***>:﻿
I have a different perspective. The software life cycle includes production, acceptance, and maintenance, which are not always part of the software development process....

**Comment by michaelpog** [comment]
Thanks for sharing your perspectives.
According to [AWS documentation on SDLC](https://aws.amazon.com/what-is/sdlc/#:~:text=The%20software%20development%20lifecycle%20(SDLC,expectations%20during%20production%20and%20beyond.) SDLC includes: Plan, Design, Implement, Test, Deploy, Maintain.

According to [Wikipedia - The phases of SDLC](https://en.wikipedia.org/wiki/Systems_development_life_cycle#Phases) the phases of SDLC are: System investigation, Analysis, Design, Testing, Training and transition, Operations and maintenance, Evaluation.

In fact, every time I do a search for Software Lifecycle, the results I find are for the term Software Development Life Cycle.

So my point is what you guys think of "Software Lifecycle" is actually called SDLC, but the phases are the same.

@Hruschka I don't know if the product lifecycle is the same. This can be easily confused with Product life-cycle management (PLM) which is very far from what we're discussing.

**Comment by michaelpog** [comment]
@alxlo I appreciate you sharing this paper [this paper](https://www.researchgate.net/publication/220662759_Software_Evolution_and_the_Staged_Model_of_the_Software_Lifecycle), I am aware of it.

This is indeed the **only** resource I've found that talks about "Software Lifecycle".
It is an interesting academic model. 

According to this paper, the phases of the Software Lifecycle are **Initial development**, **Evolution**, **Servicing**,  **Phase-out**, and **Closedown**.

Since there's no other mention in the curriculum about SDLC, is this what we want to teach our trainees instead of the SDLC phases of:" Plan, Design, Implement, Test, Deploy, Maintain."?

In that case, what is the role of a software architect in the **Servicing**, **Phase-out**, and **Close-down** phases that is so significant that it is an R2 for a practicing professional for software architecture?

Even if we go by this model only, which I want to point out is not an industry-accepted standard/model, the only phases that an architect is involved (in my opinion) are the **initial development** and **evolution**, which are, in fact, the equivalent of SDLC which I mentioned earlier.

**Comment by alxlo** [comment]
In my courses I like to point out the distinction between the SDLC and the SLC from this paper, especially pointing out the different perspectives and time-frames. 
When I get the authors right, the SLC also results in a succession of evolution phases (given the software system remains economically viable). And they explicitly state that architects are involved in all stages 


Am 7. Mai 2024 23:46:05 MESZ schrieb Michael Pogrebinsky ***@***.***>:
>@alxlo thanks for joining in.
>I appreciate you sharing this paper [this paper](https://www.researchgate.net/publication/220662759_Software_Evolution_and_the_Staged_Model_of_the_Software_Lifecycle), I am aware of it.
>
>This is indeed the **only** resource I've found that talks about "Software Lifecycle".
>It is an interesting academic model. 
>
>According to this paper, the phases of the Software Lifecycle are **Initial development**, **Evolution**, **Servicing**,  **Phase-out**, and **Closedown**.
>
>Since there's no other mention in the curriculum about SDLC, is this what we want to teach our trainees instead of the SDLC phases of:" Plan, Design, Implement, Test, Deploy, Maintain."?
>
>In that case, what is the role of a software architect in the **Servicing**, **Phase-out**, and **Close-down** phases that is so significant that it is an R2 for a practicing professional for software architecture?
>
>Even if we go by this model only, which I want to point out is not an industry-accepted standard/model, the only phases that an architect is involved (in my opinion) are the **initial development** and **evolution**, which are, in fact, the equivalent of SDLC which I mentioned earlier.
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/isaqb-org/curriculum-foundation/issues/444#issuecomment-2099362254
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by michaelpog** [comment]
@alxlo, yes, I remember. 
You present it very nicely.
I think there's definitely value in pointing out the distinction between the SDLC and the SLC in this paper.
I have absolutely no objection to broadening the horizons of students.

Going back to my original question, though:
Given that the Learning Goal is "Understand Software Architecture as Part of the Software Lifecycle", and the term SDLC is not mentioned anywhere, it appears that the concept of SDLC is out of scope for the training for CPSA-F, even though it is a widely accepted, well-understood in the industry and in by all definitions involves all the phases that @Hruschka and @mahboubagharbi mentioned.

At the same time, based on this title, it appears that the concept of SLC is an integral part of the curriculum, and this paper is the source to which we want to refer students.
Setting aside what you or I choose to teach, my question is, "Is this the consensus in iSAQB" that SDLC is out and SCL (and the above-mentioned paper are in)?
Is everyone on board with this?

Otherwise, if we want to teach the role of software architects in the phases that @Hruschka, @mahboubagharbi, and I mentioned, then we should rename this goal to reflect that we are talking about SDLC instead.
@alxlo, you could still continue teaching the same way you do, pointing out those differences between one in-scope and another out-of-scope. There's no impact on your training.
Thoughts?

**Comment by alxlo** [comment]
This LG has been removed from the curriculum. 
See #392 and commit 7ee0dec

@michaelpog can we close this issue?
