### ISSUE TITLE
Improve and align wording of LG 03-09 - "Cross-Cutting Concerns" vs. "Querschnittsthemen"

### ISSUE THREAD

**Issue by alxlo** [isaqb-org/curriculum-foundation#456]
currently
DE: "Querschnittsthemen entwerfen und umsetzen"
EN: "Design and Implement Cross-Cutting Concerns"

Both are not quite to the point and also quite different. The German version looks very weird to me. Architekten entwerfen keine Querschnittsthemen. Sie entwicklen querschnittliche Konzepte um Lösungen für Querschnittsbelange umzusetzen. (just IMHO, möglicherweise habe ich die Diskussion dazu verpasst)

Architects also do not just "design Cross-Cutting Concerns". The identify or CCC and design cross-cutting concepts, (also IMHO, also maybe I've missed the discussion here).

**Comment by gernotstarke** [comment]
in #402 we decided to:

* replace concepts by concerns where wording is appropriate.
* replace "concepts for crosscutting concerns"

To align the German version:
* Architekten identifizieren Themen (Anliegen, Belange), die querschnittlich gelöst werden sollten. EN: "concerns". 
* Querschnittskonzepte sind Lösungen für diese querschnittlichen Themen (Belange, Anliegen)

In the German text we use "Querschnittsthemen" or "querschnittliche Themen", "Querschnittskonzepte" or "querschnittliche Konzepte".

(discussed and decided June 20th 2024 by @alxlo, @Hruschka and @gernotstarke )
