### ISSUE TITLE
Bug in readme.adoc: Link to "copyrighted work" does not work

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#483]
There is a link in the readme "this is copyrighted work", but the link leads to 404.

**Comment by programming-wolf** [comment]
I'll fix it as soon as we merge your branch that's restructuring the README.

**Comment by gernotstarke** [comment]
readme should now be ok, see PR #486 ... you could merge that.

**Comment by alxlo** [comment]
was fixed with #486, close
