### ISSUE TITLE
LG 1-06 add authorative reference(s) for LG 1-06 (data modelling)

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#511]
Please, @mikesperber and @skogsbaer , propose one or a few references for data modelling in your sense,
especially for sum and product.

My proposal would be a book or article which adresses practical aspects and is _general purpose_, not a theoretical treatment.

E.g. https://www.turingtaco.com/algebraic-data-types-structuring-data-in-functional-programming/ is a counter-example
from my point of view, as I consider it overly specific for our purpose in foundation-level. I wouldn't want that as a reference in foundation.

**Comment by gernotstarke** [comment]
would be fine for me. Could you add these to the references too, please?

**Comment by mikesperber** [comment]
@gernotstarke They are already in the references, PR #516 adds links to the LG itself.

**Comment by ulibecker** [comment]
Do we have a more specific reference for this? I find both "How to Design Programs" and "Schreibe Dein Programm!" very broad and not that helpful if one wants to figure out what is meant by "products and sums" in this context.

**Comment by ulibecker** [comment]
Maybe a glossary entry would be more helpful than a book reference in that case

**Comment by skogsbaer** [comment]
There exists a glossary entry for sums and products in the new glossary. @mikesperber and myself are writting a blog entry about sums and products. We could add a reference to that.

**Comment by mikesperber** [comment]
> There exists a glossary entry for sums and products in the new glossary. @mikesperber and myself are writting a blog entry about sums and products. We could add a reference to that.

You can check out here how that's shaping up:

https://github.com/skogsbaer/sum-product

**Comment by gernotstarke** [comment]
added Kleppmann too... best book on data, imho.

PR #571
