### ISSUE TITLE
unify anchor-definitions for Learning-Goals between DE and EN

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#518]
In DE, learning goals have anchors like [[LZ-03-07]] (with a "Z"),
in EN, it is [[LG-03-07]].

When hyperlinking between LGs, and/or linking to specific LGs from outside (e.g. glossary),
this can lead to confusion.

Proposal: Unify these anchors to the EN-version: LG-03-07.

**Comment by gernotstarke** [comment]
I'm just refering to FOUNDATION. We have a few reasons for hyperlinks there, starting from inter-LG-refs,  glossary AND exam questions...

**Comment by alxlo** [comment]
Especially from Exam questions. This is no big issue, but it would simplify things when references do not depend on the language of the learning goal.
