### ISSUE TITLE
Remove "previously" / "ehemaliges" from the Learning Goals

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#537]
In all chapters, we should delete the text “[previously LG...]” text. I would rather have this documented as part of the change history that we publish.

By the way, in LG 01-03 in the English version, "ehemaliges LG 1-4" is used instead of "previously LG 1-4".

**Comment by alxlo** [comment]
Gernot and I talked about this and very much believe that this will help the transition to the new curriculum. So we would like to keep it at least until mid 2025 when everyone is settled in with the new version. In later revisions we should remove them.

**Comment by alxlo** [comment]
Also see Decision 002 - https://github.com/isaqb-org/curriculum-foundation/blob/main/documentation/decisions/002-Keep_old_LG_numbers_in_2025_curriculum_for_reference.md

**Comment by rhoadesre** [comment]
I think the information is important to make available. I just think it should be contained in a different document.
