### ISSUE TITLE
Chapter 1: Delete "Types of IT Systems" from the "Relevant Terms"

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#538]
"types of IT systems (embedded systems; real-time systems; information systems etc.)" should be deleted because we deleted the corresponding learning goal completely.

**Comment by alxlo** [comment]
100% agree, there is also a question in the mock exam that corresponds to these terms and should be removed.

**Comment by gernotstarke** [comment]
has already been fixed with bcee445086d894edeeff22ee854cd0543eacd6af
