### ISSUE TITLE
LG 01-03: "and refine them if necessary" change or delete.

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#539]
I know we've talked about this ad nauseum, but I'm going to give it one last try...  :-)

I would like to change the "clarify and scrutinize requirements and constraints, and refine them if necessary ..." to "clarify and scrutinize requirements and constraints, and refine them with the responsible people if necessary ...".

I still strongly believe that we should not refine them. If we do this, there is a risk that we will adapt the intention of the requirements. I'm perfectly happy with working with the people who are responsible for the business requirements (e.g., product owner, business analyst, customer, project manager, etc.) to refine them.

**Comment by gernotstarke** [comment]
Roger, in a better world you HAVE a person responsible for requirements. It seems I often work in a mediocre world, where nobody (!) feels RESPONSIBLE for requirements.

I'm completely with you: IF such people exist, we should collaborate and cooperate with these. But can the iSAQB take this assumption?

What about:

>Clarify and scrutinize requirements and constraints, and refine them. 
>That should be done in cooperation with the responsible people, if possible.

**Comment by rhoadesre** [comment]
> Roger, in a better world you HAVE a person responsible for requirements. It seems I often work in a mediocre world, where nobody (!) feels RESPONSIBLE for requirements.
> 
> I'm completely with you: IF such people exist, we should collaborate and cooperate with these. But can the iSAQB take this assumption?
> 

There's always someone responsible, even if it's the architect. Whether they think or feel that they are responsible for them, is another matter. :-) 
I also separate the person from the role. Maybe the architect refines the requirements; but when they do this, it's the same person fulfilling two different roles.

> Clarify and scrutinize requirements and constraints, and refine them.
> That should be done in cooperation with the responsible people, if possible.

That is pretty much what I wanted to say. I would change your wording slightly. The following statement eliminates the issue of responsibility and stresses more of the coordination and agreement with other stakeholders, regardless of who actually makes the changes.

> Clarify and scrutinize the requirements and constraints. Coordinate and agree on any necessary refinements with the corresponding stakeholders.

> Anforderungen und Randbedingungen klären und hinterfragen. Notwendige Verfeinerungen sollen mit den entsprechenden Stakeholdern koordiniert und abgestimmt werden.
