### ISSUE TITLE
LZ  02-01 - change wording slightly to be clearer

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#541]
In der Anliegen Tabelle für den Stakeholder "Entwicklungsteam" steht "technologische Einschränkungen". Was sind "technologische Einschränkungen"? Ist damit die Softwarearchitektur-Vorgaben an die Entwickler gemeint, oder die Rahmenbedingungen von anderen Stakeholdern bzgl. Technologien (z.B. der Unternehmensarchitekt gibt vor, dass Java verwendet werden muss).  Ich präferiere entweder "Softwarearchitekturvorgaben" oder "technische Rahmenbedingungen". Ich glaube, dass "technische Rahmenbedingungen" gemeint ist. 

Es wäre hilfreich ein Beispiel davon auch zu geben, wie oben.

**Comment by gernotstarke** [comment]
added _technical requirements and constraints_ to development team.

Re-sorted table to have development team prior to project management!

**Comment by gernotstarke** [comment]
see PR #574
