### ISSUE TITLE
LZ 02-01: Prüfungsrelevanz der kurz- und langfristigen Ziele runtersetzen

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#542]
Ich würde lieber, dass das Thema bzgl. der Unterscheidung zwischen kurz- und langfristigen Zielen auf maximal R2 und bevorzugt auf R3 gesetzt wird. 

Das Thema ist definitiv wichtig, aber für mich sind die anderen Themen im Lehrplan deutlich wichtiger.

(ich glaube, wir haben das Thema schon besprochen, ich finde den Issue nicht).

**Comment by gernotstarke** [comment]
In addition I have the problem that the terms "short-term" and "long-term" are under-defined and vague.

Reduced to R2 for now.

**Comment by gernotstarke** [comment]
it was #397
