### ISSUE TITLE
LZ 02-02: Architekturentscheidungen führen zu Anforderungen??

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#543]
Ich glaube, ein konkretes Beispiel bzgl der folgenden Aussage ist notwendig: "Sie wissen, dass ihre Entscheidungen zu zusätzlichen Anforderungen führen können." 

Anforderungen sind per Definition Forderungen an uns (und anderen). Wie können Architkten Entscheidungen treffen, die zu weiteren Anforderungen an Architekten führen? Das verstehe ich nicht. Oder ist hier gemeint, dass die "Entscheidungen zu Vorgaben an die Implementierung führen können"?

**Comment by alxlo** [comment]
I somehow remember that we've already had that discussion.  IMHO architects definitely come up with additional requirements on the system and its architecture by considering context (stakeholder concerns like the PO requirements but also the capabilities of the developers). In what category would you put something like "Because we decided to use X for logging by the request of the customer (external requirement), no component shall issue more than n log events per second. (requirement we came up with)."
I'm quite sure that @rhoadesre and I had this discussion while talking about this illustration.
 
![image](https://github.com/user-attachments/assets/0dabfa24-d8fc-4b2a-9411-981174456541)

**Comment by rhoadesre** [comment]
I think the problem is that there is some confusion between the business requirements that come from the customers and architecture decisions or implementation (a.k.a. technical) requirements that must be implemented by the implementation team. 

Differentiating between business requirements and implementation requirements is important for traceability and clarity. What is the origin of this requirement and the reasoning behind it? In fact, I prefer to use the term "requirement" strictly for business requirements from the customer and other terms "implementation requirement", e.g., "design specification", "architecture decision", etc. for clarity.  I am; however, open to use the terms "business requirement" and "implementation requirement" as long as the meaning is clear and used consistently.

Given your example:

- The customer doesn't typically require logging. What is behind the requirement for logging that the customer really wants? They may want to ensure that all changes can be tracked to specific users (security). They may want to ensure that bugs can be solved quickly (maintainability). The use of logging is a decision by the architect to fulfill the customer requirements, and depending on the customer intent, different solutions could be implemented. I may be splitting hairs here, but it's my experience that business requirements from the customer are typically too system-oriented and it's important to discover what the customer really wants. By doing so, the best implementation solution becomes clearer.

- If the architect decides that "no component shall issue more than n log events per second", why is that? Is there a technical limitation? Is this an architecture decision, an implementation requirement, or both? Are they synonymous? It is certainly / probably not a business requirement.

To answer your questions above, "In what category would we put something like ...."? This is an architecture decision required to fulfill a business requirement. I'm open to discussing if architecture decisions are implementation (or technical) requirements, but it should be clear if it is a business requirement from the customer or an implementation requirement from the architect.

**Comment by rhoadesre** [comment]
I'd still prefer to delete the line from the curriculum, but I'd be fine with the following:

> They are able to clarify **business** requirements and constraints and take them into account in the architectural design and development process. They know that their decisions can lead to additional **implementation** requirements.

**Comment by dkraemer-anderScore** [comment]
I fully agree that 'implementation requirements' must not be confused with (business) requirements. While the first emerge from architecture, the latter are it's inputs. Therefore, I prefer the terms 'architecture decision' or 'design specification', too.

**Comment by rhoadesre** [comment]
I wanted to make a concrete suggestion in English and German. Ironically, when I entered the following in DeepL
> "Sie wissen, dass ihre Entscheidungen zu Vorgaben an die Implementierung führen können"
I got back the following:
> “They know that their decisions can lead to implementation requirements”

:-)

**Comment by rhoadesre** [comment]
Is everyone OK with the following suggestion?
German:
> "Sie wissen, dass ihre Entscheidungen zu Architekturvorgaben an die Implementierung führen können."
English
> "They know that their decisions can lead to architectural guidelines or specifications for the implementation."

**Comment by alxlo** [comment]
I really like @rhoadesre approach to differentiate business and implementation requirements and would like to add that there might also be design requirements. However the term "implementation requirements" might be confusing. Does it pose requirements on the implementation process, the implementation results, or both?

We also should keep in mind, that our (iSAQB) use of those terms when we come up with a clear terminology might not be equal to how people in practice apply those terms. What we do is and should be "normative" (describing how those terms should be used) but it should also be "descriptive" (describing how those terms are used).

**Comment by rhoadesre** [comment]
> Do [implementation requirements] pose requirements on the implementation process, the implementation results, or both?

The original intention was requirements on the implementation results, but I see no reason why it couldn't be both.

**Comment by ulibecker** [comment]
I find the term "implementation requirements" too narrow. An architectural decision for a system can have strong influence on subsystem requirements, and I would not call these "implementation requirements". I am not optimistic that we can come up with wording for requirements that is applicable for all kinds of domains. What I think is generally true is that the feedback by architects can lead to requirement changes, and that architectural decisions have an impact on derived requirements.

**Comment by Hruschka** [comment]
Requirements are requirements are requirements. We should not introduce terms like implementation requirements, etc.

There are three processes that you can do with (vague) functional and quality requirements: You can DECOMPOSE a complex requirement into more primitive ones (e.g. epics into features or stories), or you can DETAIL them. This just means clarification WITHOUT design decisions. Or you can DERIVE more precise requirements from them. Derivation always include design decisions (note: I do not want to call them architectural decisions. Any stakeholder can participate in the process of DERIVING, not only the development team). 

 An example: Originally someone asked for access control or access restriction to a product. Somebody is now deriving a concrete way to ensure access control (e.g. fingerprint scan). Fingerprint scan is now a functional requirement derived from a vague quality requirement. 

These processes of either detailling requirements or deriving requirements are described in detail (including a meta-model and many examples) in [Hatley, Hruschka, Pirbhai: Process for System Architecture and Requirements Engineering, Dorset House] page 24 ff.

So let us talk about "derived requirements" and not "implementation requirements". (Any requirement is a requirement for implementation, even the product goals. Otherwise I would not ask for it.)

**Comment by alxlo** [comment]
> I am not optimistic that we can come up with wording for requirements that is applicable for all kinds of domains. 

Neither am I. As much as I like the idea.

> What I think is generally true is that feedback given by architects can lead to requirement changes, and that architectural decisions have an impact on derived requirements.

+1 from me here.

**Comment by rhoadesre** [comment]
@Hruschka: so, I read much of your book.  :-)  

First, a philosophical comment, **for which I don't need a reply**. In your book, you differentiate between the "what" and the "how". 

"The system requirements model is a technology-independent model of the problem the system is to solve. It represents the 'what'. The system architecture model is a technology-dependent model of the solution to the problem. It represents the 'how'.". 

I would agree and would state that the customers (or their representatives) should define the "what" and the architects the "how". 

However, it is not always clear distinction. Using your example above, is the "Fingerprint scan" a "What" or a "How"? I think there's arguments either way.

**Comment by rhoadesre** [comment]
@Hruschka: 
In your book you also differentiate between "required capabilities" and "required constraints". 

If I understood correctly (a big if), this can be related back to our topic in this discussion. The original statement in the curriculum is not clear to me. I would like to add clarity.  What do you think about the following proposal:

Original: 
> They know that their decisions can lead to additional requirements.

Proposed change:
> They know that their design decisions lead to required constraints on the system.

And we provide a reference to your book.

**Comment by Hruschka** [comment]
@rhoadesre: No, Roger. I have given up in the strict distinction between requirements capabilities and required constraints. The first group are the things stakeholder really want from the system, the second are restrictions that stakeholder give you about the solution (e.. organizational or technical constraints). The distinction is useful, but vague. Now I say - in a provocative way - constraints are requirements from stakeholders you hate! Is obeying the speed limit on the motorway a safety requirement or just a (useless) constraint from the ministery of traffic?
As you mentioned: The distinction between what and how is also useful, but vague. In my previous example: If you want access control (and have no opinion about how to achieve it), then fingerprint scan is a derived required for one possible solultion to access control. There are other alternatives. Access control is the WHAT, finger print already a HOW. But if your stakeholder insists on fingerprint, the this is the WHAT - and you have to implement it.

**Comment by rhoadesre** [comment]
I'd still like to add some clarity to the statement in the curriculum. Any suggestions for a concreate formulation?

What about simply:
> They know that their design decisions lead to constraints on the system to be implemented.

In this case, the architects are the "stakeholders that the [implementers / developers) hate"!  :-)

**Comment by Hruschka** [comment]
@rhoadesre: Don't use the word constraint in this sentence (Constraints are defined as requirements that limit the solution space, usually coming from the "outside", not from the development team). Yes, if the CTO makes a decision: We use Microsoft technology, this is a constraint for all development teams (that don't find a good excuse). If the architect decides to use Kafka as MOM, this is a simple architecture decision, which is from then on binding for all developers. 

Better: "They know that their design decisions may lead to derived requirements."

Derived requirements may be 
- new or more precise functionality
- new or more precise quality requirements
- new or more precise constraints.

**Comment by kraemerdr** [comment]
> If the architect decides to use Kafka as MOM, this is a simple architecture decision, which is from then on binding for all developers.

Sounds very much like a (derived) constraint for them. ;-)

If we settle on the architect being able to introduce new requirements, I would really like to differentiate between the ones initially provided from the customer and those resulting from architecture decisions, because of the aspects @rhoadesre mentioned earlier. Therefore, I suggest keeping the term 'derived requirements'. In short:

> They know that their design decisions may lead to derived requirements such as new or more precise functionality, quality requirements or constraints.

**Comment by gernotstarke** [comment]
@alxlo and myself condensed this discussion to the following proposal:

>EN: They understand that their decisions may introduce new requirements or necessitate changes to existing requirements.

>DE: Sie verstehen, dass ihre Entscheidungen zu zusätzlichen Anforderungen führen oder Änderungen an bestehenden Anforderungen erforderlich machen können.
