### ISSUE TITLE
LZ 02-03 Eliminate redundant sentences

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#544]
LZ 02-03 Qualitäten eines Softwaresystems verstehen und erklären

Die Sätze " dass manche Kategorisierungen zwischen Funktionalität und Qualität unterscheiden" und " manche Kategorisierungen zwischen 'Qualitätsanforderungen' und funktionalen Anforderungen unterscheiden, wie zum Beispiel IREB [IREB Foundation] (R1)" sind für mich ähnlich genug, dass der este Satz gelöchst werden kann bzw. soll.

**Comment by gernotstarke** [comment]
From my point of view having both parts clearly shows that the distinction is valid for BOTH 

- requirements and
- a more general notion

Therefore I'd vote for leaving the sentence _as is_ with both clauses.

**Comment by rhoadesre** [comment]
OK.
