### ISSUE TITLE
LG 02-03: remove quotes around Quality Requirements

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#545]
Why are “quality requirements” in the sentence "some categorizations distinguish between 'quality requirements' and functional requirements, e.g. IREB "in quotation marks? 

In any case, the quotation marks should be removed. It seems as if it is meant ironically.

**Comment by gernotstarke** [comment]
the final part of the introductory sentence is currently and might lead to confusion:

> that the term "quality" is used differently in different contexts - referring to "excellence" in the context of quality management, and referring to a specific property (of a software system) in others (and in this section) 

Proposed improvement:

> that the term "quality" is used differently in different contexts, referring to 
> - referring to "excellence" in the context of quality management, and 
> - referring to a "specific property (of a software system)" in others.
>
> This learning goal refers to the latter.
