### ISSUE TITLE
Is a new learning goal in chapter 4 (Communication) required for data models?

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#547]
The importance of data models was added as a new learning goal (LG 01-06), but is not mentioned in Chapter 4 regarding communication. 

What is the opinion of others?

**Comment by gernotstarke** [comment]
My opinion: I can communicate (and specify) a data model similar to any other (static) architecture view, therefore I don't see the NEED for additional treatment of data in section 4.

A simple option: Add ER-diagrams to the list in LG-04-03.

Will open a PR for that.

**Comment by rhoadesre** [comment]
OK. Good idea.
