### ISSUE TITLE
LG 04-04 - Missing name and the content is also not understandable

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#549]
Is this learning goal really called "Learning goal not found" / "Lernziel nicht gefunden"?  :-)

I don't understand the content of this learning goal either. “Software architects are able to gracefully deal with unexpected situations”. 

As the learning objective is currently formulated, it is more of a soft-skills topic and is far too abstract for me. 

What is actually trying to be conveyed?
1) “The software architecture approach can gracefully handle unexpected situations or errors”? If that is the point, then the learning objective belongs more in Chapter 3 “Design and development of software architectures”. 
2) "Software architects themselves should be able to handle unexpected situations". Yes, the point is valid, but too abstract and not helpful. 

I would rather simply delete this learning objective.

**Comment by gernotstarke** [comment]
**[404 is the http status code for "not found".](https://en.wikipedia.org/wiki/HTTP_404)**

And yes, the LG title had been chosen deliberately during our joint meeting in Stuttgart.

I am happy with have just a little geek humor in the otherwise relatively boring curriculum.
