### ISSUE TITLE
LG 04-05 should specifically state that additional views can be helpful

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#550]
Please add a point, at least as R3, that “Additional views can be used as needed to address the fulfillment of stakeholder concerns and requirements, such as data view, technology view, security view, etc.”

**Comment by gernotstarke** [comment]
The only reference I found is <<<rozanskiwoods>>, and they are using the term "viewpoints".
Their examples include functional, information, concurrency, development etc. viewpoints.

I add these as examples.

@rhoadesre

**Comment by Hruschka** [comment]
I would have replaces the word "funktional" in German by "funktionale Sicherheit".
In the English version the - don't work.  You gotta write functional safety view, information view, operational view or user-interface view.

**Comment by gernotstarke** [comment]
actually, Rozanski-Woods explicitly use "functional viewpoint" (which I consider more of a requirements topic...)

But good idea, the example is better.

**Comment by rhoadesre** [comment]
> I would have replaces the word "funktional" in German by "funktionale Sicherheit". In the English version the - don't work. You gotta write functional safety view, information view, operational view or user-interface view.

What is "functional security"? Are you referring to "functional safety" is described here?
https://en.wikipedia.org/wiki/Functional_safety

Maybe just remove the word "functional"?
