### ISSUE TITLE
References: critical problem: Backlinks from ref to learning goals

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#561]
In the references section, certain entries are formated as hyperlinks, back-linking to pages within the curriculum.
That is irritating for those references that are used within different learning goals (like Bass+2021).

I suggest to remove these backlinks altogether.

![Image](https://github.com/user-attachments/assets/c92d12c9-6dba-438a-94bc-711a5fec19bb)

**Comment by programming-wolf** [comment]
This is default behaviour of asciidoc. If a reference is referenced somewhere, the link is created automatically.

**Comment by gernotstarke** [comment]
I consider that to be problematic in case of references like <<bass>>, which is referenced in at least 8 learning goals. The backlink leads only to the first occurence.

**Comment by gernotstarke** [comment]
there is no simple fix for this problem in asciidoc. Therefore I close the issue as `wontfix`
