### ISSUE TITLE
LG-03-07, add additional options for implementing interfaces

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#564]
I stumbled upon our overly restricted list of options for implementing interfaces (we have only REST and SOAP)...

Let's add a more systematic categorization 

- Transport 
http, socket, binary, message-brokers

- Communication Style
** sync (rpc, service-oriented, REST), async (messaging, pub-sub), file-based
** unicast, multicast

- General Approach
REST, GraphQL, gRPC, SOAP

- Use Cases
Client-Server, web-API, streaming and real-time data, async microservices, IoT 

I don't want to include all of these topics, help wanted...

**Comment by rhoadesre** [comment]
I like the idea of categorizing the types of interfaces, but I'm not sure if it's possible. 
I haven't found any good sources that people tend to agree on. There are a bunch of articles and books that categorize them differently, e.g., internal, external, operating system, public, partner, web, etc. etc. None of which I find particularly helpful.

The only thing I could think of that may make sense is not to assign interfaces to categories, but to list characteristics that differentiate the different types of interfaces. The interfaces would fulfill multiple characteristics, e.g., a REST interface is both synchronous and point-to-point, and operates at the HTTP level.

Characteristics:
- Transport Layers (Application layer, Presentation layer, Session layer, ...)
- Point-to-Point vs. Multipoint
- Data (e.g., shared database or files) vs. Presentation (e.g., screen scraping) vs. Application (e.g., Rest) vs ...
- Internal vs. external (e.g., Partner) vs. public (e.g., Internet)
- local vs. remote
- sync vs async
- binary (machine readable) vs text (readable by a person)
- stateless vs. stateful
- streaming vs ????
- programming-language specific and generic
- ...

After that simply list the types of interfaces that you noted, e.g., ReST, Messaging, GraphQL, gRPC, SOAP, database or file sharing, screen scraping, etc.

The most important is to recognize what characteristics a specific type of interface fulfills and relate that back to what characteristics and types of interfaces are required to fulfill the requirements and constraints.

**Comment by dkraemer-anderScore** [comment]
Assigning interfaces one or multiple characteristics in order to relate them to specific requirements or constraints is a nice idea. I am even fine with including all of the examples listed as long as they are declared R3. Otherwise we need to make a selection indeed.

**Comment by gernotstarke** [comment]
Gave it a try, please have a look at #639

**Comment by gernotstarke** [comment]
added a new branch and a new PR, as the old one was too difficult to review. Please see #659

**Comment by rhoadesre** [comment]
Ich hätte gesagt, mit #659 geschlossen.
