### ISSUE TITLE
LG-04-09 remove FMC

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#575]
in the list of documentation notations (UML, C4, arc42) we still have FMC (_fundamental modeling notation_),
which I consider not relevant for our purposes.

A few years ago (in 2020) we discussed both RM/ODP and FMC in #130 and decided to keep FMC.

What's your opinion?

**Comment by rhoadesre** [comment]
I personally would like to see it removed. I've personally never seen it used in projects.
But wasn't there some kind of relationship with SAP? Is it used often by SAP-Architects?

**Comment by gernotstarke** [comment]
A variant of FMC is said to be used SAP-internally. From my perspective, no reason to include it in the curriculum.
