### ISSUE TITLE
LG-03-04 DRY missing from list of principles

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#578]
the current version omits the DRY principle.

We have at least one mock-exam question regarding DRY, and I consider it a relevant topic. Can be R3.

Your opinion?

**Comment by ulibecker** [comment]
Fine for me, we then should also add the potential trade-offs with regard to coupling

**Comment by sippsack** [comment]
I agree, we should add DRY principle again. And we should make it R2 if there is also an exam question (not sure about that).

**Comment by dkraemer-anderScore** [comment]
In my trainings I usually teach DRY together with WET, so it becomes obvious that reusage is not necessarily the way to go in each and every situation. I would keep it at least as R3.

**Comment by rhoadesre** [comment]
> In my trainings I usually teach DRY together with WET, so it becomes obvious that reusage is not necessarily the way to go in each and every situation. I would keep it at least as R3.

+1
