### ISSUE TITLE
LG 03-08 Should Include Dependency Injection explicitly

### ISSUE THREAD

**Issue by michaelpog** [isaqb-org/curriculum-foundation#582]
It appears that LG 03-08 explicitly mentions three patterns: Layer, Pipes and Filters and Microservices.
However, Dependency Injection is also indirectly mentioned as R1 in LG 03-06.
I think it would be better to mention Dependency Injection as one of the patterns in LG-08, explicitly.
Right now it's kind of buried in 03-06.

**Comment by gernotstarke** [comment]
Right - D-Injection is mentioned in 03-06 as one option to achieve D-Inversion. In my opinion the cohesion between injection and inversion is higher, so I consider it better to put those two together in a single LG.

**Comment by rhoadesre** [comment]
It wouldn't hurt to list it under 03-08 as well as 03-06. I agree with @michaelpog, it is "buried" in the 03-06 and not clear, if it is exam-relevant.

**Comment by gernotstarke** [comment]
see PR #629

**Comment by rhoadesre** [comment]
Changes committed
