### ISSUE TITLE
LG-03-04 re-introduce SOLID

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#594]
from an iSAQB internal slack channel, asked by @michaelpog:

>I see that SOLID principles were entirely removed. In other words even the mention of the term SOLID was removed and instead just the Open/closed principle, Dependency inversion principle were left as standalone principles.
>I wanted to understand why the decision was made to completely drop the term SOLID which is very commonly used in software engineering and architecture, instead of simply keeping the SOLID principles as they are but expanding the R3 to SRP and ISP. 
>This way I would have still had the ability to choose to teach those topics as R3, and also inform my students about the term SOLID.
>On that note, I would also like to know why the decision was made to drop those 2 principles (SRP and ISP) entirely?
>SRP is very applicable to many levels of abstraction and is such a common principle. It used used anywhere from methods and class to larger components like Microservices, or low level components like drivers in the OS, pipes in the pipes in filters pattern etc.
>Similarly ISP is also very important principle for designing interfaces.

**Comment by gernotstarke** [comment]
@michaelpog thanx for starting this discussion.

My take on SOLID:  It's overrated.
I personally consider SOLID to be mostly valid for purely object-oriented systems, and they have been written by Robert C. Martin exactly as programming advice for OO. He as copied the underlying abstraction and modularization ideas from others, and partially simply rephrased them (e.g. SRP -> re-phrased from the way older separation-of-concern.)

IRP is actually a very BAD advice for many kind of APIs nowadays, and even for many OO systems it can lead to bloated interfaces.

LSP has been under dispute here - it's origin in "implementation inheritance" is nowadays considered harmful or at least not generally _good_.

OCP is highly useful and valid - even for non OO-systems.

In addition, I consider the author Robert C. Martin  a highly contoverse public figure. I personally see his many sexist and chauvinistic comments and talks a no-go for him to be quoted or cited in our curriculum. That's my personal opinion.

**Comment by sippsack** [comment]
I am ambivalent and have the same feelings as @michaelpog. I also miss this omnipresent SOLID. On the other side I must agree to @gernotstarke and as iSAQB we have a responsibility to question existing knowledge and not forever follow questionable defacto standards.

**Comment by rhoadesre** [comment]
@gernotstarke 
> IRP is actually a very BAD advice for many kind of APIs nowadays, and even for many OO systems it can lead to bloated interfaces.
> 
Do you mean SRP in this sentence?

**Comment by dkraemer-anderScore** [comment]
My guess was ISP :-D

**Comment by michaelpog** [comment]
Just to restate my questions as my take on this.

I don't have any questions about LSP, it was already R3, and I'm OK with it staying this way.

I think putting aside Robert C. Martin's personality, I would advocate for at least having SOLID as R3.

It's a very well known set of principles. Many people use OOP so even only OOP principles are relevant IMHO, but most SOLID principles are applicable beyond OOP.

I would feel not at ease if my students took a Software Architecture training, earned a certificate and went on to their workplace or job interview without knowing about SOLID principles, or not even being familiar with that term.

**Comment by gernotstarke** [comment]
I have to acknowledge that SOLID is a widespread term, contentwise it had its merits back in the 1990's for improving C++ programming.

So let's add it back to the LG with R3.

I opened a branch for it: 594-question-regarding-solid-again

One open question is under what category to put SOLID , or if we shall open a new category...

**Comment by gernotstarke** [comment]
PR is open
