### ISSUE TITLE
LG 03-01: achieve AND improve qualities 

### ISSUE THREAD

**Issue by dkraemer-anderScore** [isaqb-org/curriculum-foundation#599]
Alt: "verstehen, dass architektonische Aktivitäten davon geleitet werden sollten, spezifische Qualitäten zu
verbessern"

Neu: "verstehen, dass architektonische Aktivitäten davon geleitet werden sollten, spezifische Qualitäten zu
erreichen bzw. zu verbessern"

**Comment by rhoadesre** [comment]
+1
