### ISSUE TITLE
assign uniqe ID to every learning goal

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#6]
prerequisite for #2.

Convention: We'll assign an anchor to every learning goal, both in DE and EN versions,
using the asciidoc "[[anchorname]]" notation.

Example:

[[lg-2-6]]
==== LG 2-6: Explain and use design principles (R1)

Problem:
We need a UNIQE id, and in combined DE+EN output artifacts this anchor isn't uniqe...

**Comment by gernotstarke** [comment]
one solution: have separate id's for DE and EN
    
    [[lz-2-5]]
    ==== LZ 2-5 Deutsches Lernziel

    [[lg-2-5]]
    ==== LG 2-5 English learning goal

**Comment by rdmueller** [comment]
would it make sense to implement this with a `replaceAll`-regexp?

**Comment by gernotstarke** [comment]
you mean a regex-replace in a fancy (regex-capable) text editor? Yes, would make perfect sense.

Before I tackle that, please let me verify that the way I want to cross-reference these LG's really works with the proposed ID's...

**Comment by rdmueller** [comment]
Now that I've thought a bit more about it, I though of a asciidoctor preprocessor which adds the anchors (or replaces them if necessary)
this way, the anchors would be automatically set and the files would not be touched...

**Comment by gernotstarke** [comment]
Ralf, thanx for your input.

I'd personally modify the files instead of complicating the build process... Otherwise the casual reader of the github-plain version won't see the ID's...

**Comment by p-goetz** [comment]
+1 for a simple solution. 
I will be working on the repo tonight and will look into it.

**Comment by gernotstarke** [comment]
the [[LG-2-3]] approach worked fine for a few test cases, I'll incorporate that into the existing LG's asap. @Peter - if you start from section 5 backwards, I'll start from section 1 downwards...

**Comment by alxlo** [comment]
Ich bekomme einen Build-Fehler:
`Feb 25, 2019 5:29:27 PM uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb initialize_section
WARNUNG: 02-design/LZ-2-05.adoc: line 25: id assigned to section already in use: LG-2-5
`

**Comment by alxlo** [comment]
After reviewing the discussion above, I would very much vote against having separate IDs for the same learning goal in diffferent languages. It is semantically the same learning goal, there are just different renditions (that is languages) for the same learning goal.

**Comment by gernotstarke** [comment]
gib' mir bitte in paar Minuten, muss noch was anderes fertigstellen. Vermutlich ID doppelt vergeben, und der AsciiDoc Prozessor merkt das.

Du musst die EN-Lernziele mit LG, die deutschen mit LZ benennen :-)

**Comment by gernotstarke** [comment]
yes, but: lass' uns um 17:50 schon starten, dann erkläre ich Dir warum ich das momentan vorschlage.
Technisch fällt mir momemtan nix anderes ein.

**Comment by gernotstarke** [comment]
the idea of having another "include-switch" that ALWAYS includes the ID-Tag from learning goals
does NOT work, as there are numerous adoc-files with other text than learning-goals... which also have an include-configuration, but shouldn't have an ID.

I personally give up here - let's use the simple anchor solution for now.

**Comment by p-goetz** [comment]
Added anchors to all learning goals.
