### ISSUE TITLE
LG 03-04: add additional reason/goal for LSP

### ISSUE THREAD

**Issue by kraemerdr** [isaqb-org/curriculum-foundation#600]
Aus meiner Sicht ist das primäre Ziel hinter dem LSP weniger "Konsistenz und konzeptionelle Integrität", sondern eher Robustheit (daher auch Teil von SOLID). Wenn sich konkrete Bausteine an die Schnittstellenverträge ihrer Abstraktionen halten, ist weniger unerwartetes (und damit in aller Regel fehlerverursachendes) Verhalten zu erwarten.

Den Aspekt der Robustheit würde ich also zumindest ergänzen:
"Liskov’sches Substitutionsprinzip [Liskov 1994] als eine Möglichkeit, Konsistenz, konzeptionelle Integrität und Robustheit zu erreichen (R3)."

**Comment by gernotstarke** [comment]
That's a good argument - although I still see LSP as a purely OO topic.

**Comment by mahboubagharbi** [comment]
LSP:semantische Integrität und Konsistenz 😉

**Comment by dkraemer-anderScore** [comment]
> That's a good argument - although I still see LSP as a purely OO topic.

Although I have to admit being a huge fan of LSP, I fully agree and would even be fine with removing it from an architecture (!) training altogether. However, if we decide to keep it, linking it to robustness at least provides a justification for its selection.

**Comment by alxlo** [comment]
I'm fine with keeping it as R3, although it will not get a (full) slide in my slide deck as exposing the audience to _"Let ⁠ ϕ ( x ) be a property provable about objects ⁠ x of type T. Then ⁠ ϕ ( y ) should be true for objects ⁠ y  of type S where S is a subtype of T."_  leads to a VERY hard and immediate shut down of at least 50% of the participants in my class room. Especially if they don't have an OOP background.

> although I still see LSP as a purely OO topic.

**au contraire ;-)**

Elaborating on behavioral subtyping and that you do not want to care about possible "VIP behaviour" of your specializations/implementations is something that (almost) everyone can relate to and that works fine without OOP and also on multiple levels of architectural design and IMHO conceptually relates strongly to backward compatibility.

**Comment by mikesperber** [comment]
The original paper is about type safety, so it is up to us to speculate on the architectural implications of this.

SOLID's take on LSP is that it's about consistency:

https://blog.cleancoder.com/uncle-bob/2020/10/18/Solid-Relevance.html

I'm unsure what "robustness" means in this context, so I'm mildly opposed to adding it.

**Comment by dkraemer-anderScore** [comment]
In this case robustness corresponds to the absence of unexpected (and therefore potentially erroneous) behavior that results from components violating the interface contracts given by their abstractions. Example: read-only implementations of the List interface in Java that cause UnsupportedOperationExceptions in arbitrary parts of the code.

**Comment by mikesperber** [comment]
> In this case robustness corresponds to the absence of unexpected (and therefore potentially erroneous) behavior that results from components violating the interface contracts given by their abstractions. Example: read-only implementations of the List interface in Java that cause UnsupportedOperationExceptions in arbitrary parts of the code.

Then "robustness" is not the right word. (Cf. [https://en.wikipedia.org/wiki/Robustness](Wikipedia)), which is about reaction to change. The correct term would be "type safety" or "type soundness".

**Comment by kraemerdr** [comment]
From my perspective robustness is not limited to change, but rather describes the ability to continue operations under difficult circumstances (as described in the German version of the Wikipedia article you referenced):

> In der Informatik und Softwareentwicklung bedeutet der Begriff „Robustheit“ die Eigenschaft eines Verfahrens, auch unter ungünstigen Bedingungen noch zuverlässig zu funktionieren.

Avoiding unexpected behavior due to conformity to specified interfaces supports this goal. Type safety on the other hand is more a means than a goal IMHO.

**Comment by mikesperber** [comment]
> From my perspective robustness is not necessarily limited to change, but rather describes the ability to continue operations under difficult circumstances (as described in the German version of the Wikipedia article you referenced):

OK - but what are the "difficult circumstances" in this context?

**Comment by gernotstarke** [comment]
We are discussing an R3-topic here, just to put the length of the discussion in some context.

I conclude by proposing the following compromise:

> DE: "Liskov’sches Substitutionsprinzip als eine Möglichkeit, Konsistenz, konzeptionelle Integrität und Robustheit (im Sinne von Typsicherheit) zu erreichen (R3)."

> EN: “Liskov's Substitution Principle as a way to achieve consistency, conceptual integrity and robustness (in the sense of type safety) (R3).

**Comment by mistertakai** [comment]
Since y'all are talking about qualities, imho the ISO 25010:2023 qualities indirectly influenced by Liskov's principle would be faultlessness, modularity and testability.

**Comment by gernotstarke** [comment]
As these were not requested to be added by anyone from the FLWG members, I decide to close the issue. Seems the current formulation is good enough for most.

**Comment by kraemerdr** [comment]
> OK - but what are the "difficult circumstances" in this context?
@mikesperber Generally not knowing how a concrete implementation behind an interface will actually behave at runtime. As long as the former adheres to LSP, at least interface contract violations (unexpected behavior up to killing the whole system) are not to be expected.

However, this is my personal take on LSP based on various observations in practice. If someone does not feel comfortable with this addition, we may well leave it out.

**Comment by mikesperber** [comment]
> > OK - but what are the "difficult circumstances" in this context?
> 
> @mikesperber Generally not knowing how a concrete implementation behind an interface will actually behave at runtime.

This makes no sense in this context: LSP constrains the implementation behind an interface, so you *do* know how it behaves.

**Comment by kraemerdr** [comment]
Yes, _**if**_ the implementation adheres to LSP. That's exactly my point here.

**Comment by mikesperber** [comment]
@kraemerdr It doesn't seem we're getting anywhere: I asked earlier what the "difficult circumstances" were where the LSP somehow ensures robustness. 

You replied "Generally not knowing how a concrete implementation behind an interface will actually behave at runtime". But the point of the LSP is that it gives guarantees about runtime behavior - beyond those guarantees, it gives you nothing. (And it also doesn't tell you how to achieve qualities such as robustness.)

Then you followed up with "if the implementation adheres to LSP" - but the premise of that thread was that the implementation adheres to LSP.

So I don't know what to tell you.

**Comment by kraemerdr** [comment]
> but the premise of that thread was that the implementation adheres to LSP
But it was not the premise of my argumentation. I think this point is the source of our confusion.

My argumentation is:
Having interfaces as abstractions, implementation behavior is generally unknown by design (difficult circumstances).**If**, however,  we can rely on LSP conformant implementations (and therefore at least interface compliant runtime behavior), critical behavior is at least less likely to occur. As a consequence the application as a whole is more likely to remain operations (-> robustness).

**Comment by mikesperber** [comment]
This is true to the extent that "robustness" is among the properties formulated under the umbrella of LSP. But this degenerates immediately to "if the specification says the application must be robust, and the application adheres to the specification, the application is more robust". (And, of course, this could be done for *any* quality, so robustness doesn't stand out.)
As the original paper about LSP is about type safety - you'd have to encode robustness in the types, which is not completely out of the question, but would be quite atypical.

**Comment by kraemerdr** [comment]
> This is true to the extent that "robustness" is among the properties formulated under the umbrella of LSP. But this degenerates immediately to "if the specification says the application must be robust, and the application adheres to the specification, the application is more robust".

If it is not (since robustness is not the **original** intent of LSP), the argumentation just goes "if the specification says that implementation behavior must be coherent to well-defined interfaces, and the application adheres to the specification, the application is more robust.". This is true from my personal experience, whether or not we link it to LSP in the end.

> As the original paper about LSP is about type safety - you'd have to encode robustness in the types, which is not completely out of the question, but would be quite atypical.

To this I agree, which is why I did not base my argumentation on type safety. If you insist on it, robustness is indeed difficult to argue.

**Comment by mikesperber** [comment]
Post-hoc adding another pretty good write-up on LSP:

https://www.hillelwayne.com/post/lsp/
