### ISSUE TITLE
LG 03-09: Explain why Design-Patterns are relevant

### ISSUE THREAD

**Issue by dkraemer-anderScore** [isaqb-org/curriculum-foundation#601]
In meinen Trainings werfen die Teilnehmer regelmäßig die Frage auf, warum sie sich als Architekten eigentlich mit *Entwurfs-*mustern beschäftigen sollten. Diese Fragestellung würde ich daher gerne explizit aufnehmen:

Alt: "Sie können mehrere der folgenden Entwurfsmuster erklären, ihre Relevanz für konkrete Systeme erklären und
Beispiele nennen."

Neu: "Sie können mehrere der folgenden Entwurfsmuster beschreiben, ihre Relevanz für die Architektur und konkrete Systeme erklären sowie Beispiele nennen."

**Comment by gernotstarke** [comment]
I really like that proposal.

**Comment by gernotstarke** [comment]
done.
