### ISSUE TITLE
LG 05-01: Lernziel klarstellen

### ISSUE THREAD

**Issue by dkraemer-anderScore** [isaqb-org/curriculum-foundation#602]
Folgende Formulierung verstehe ich nicht:

_Softwarearchitekt:innen verstehen, dass es verschiedene mögliche Gründe gibt, um eine
Architekturanalyse durchzuführen, zum Beispiel:
[...]
die Anliegen der Stakeholder bezüglich der Architektur angehen_

Was ist damit gemeint?

**Comment by rhoadesre** [comment]
Wäre der folgende Satz klarer?
sichstellen, dass die Stakeholder-Anliegen adressiert sind?

**Comment by dkraemer-anderScore** [comment]
So ist er zumindest besser verständlich. Man könnte daraus aber möglicherweise herauslesen, dass eine Architektur **sämtliche** Stakeholder-Anliegen adressieren sollte. Noch besser fände ich daher:

"überprüfen, inwiefern Stakeholder-Anliegen adressiert sind".

**Comment by gernotstarke** [comment]
EN: verify that architecturally relevant stakeholder concerns are addressed
DE: * überprüfen, inwiefern architekturrelevante Stakeholderanforderungen berücksichtigt sind

done, see PR #620

**Comment by dkraemer-anderScore** [comment]
"verify _**that**_ architecturally relevant stakeholder concerns are addressed" suffers from the same potential misunderstanding as "sichstellen, **_dass_** die Stakeholder-Anliegen adressiert sind". Therefore, I rather suggest something like "check to what extent architecture-relevant stakeholder concerns are taken into account", i.e. a direct translation of "überprüfen, inwiefern architekturrelevante Stakeholderanforderungen berücksichtigt sind".

**Comment by rhoadesre** [comment]
> "verify _**that**_ architecturally relevant stakeholder concerns are addressed" suffers from the same potential misunderstanding as "sichstellen, **_dass_** die Stakeholder-Anliegen adressiert sind". Therefore, I rather suggest something like "check to what extent architecture-relevant stakeholder concerns are taken into account", i.e. a direct translation of "überprüfen, inwiefern architekturrelevante Stakeholderanforderungen berücksichtigt sind".

I don't understand the difference. For me, it has the same meaning, but the proposal from Daniel is a more accurate translation of the German version.

Small change proposal: Use "verify" instead of "check".

**Comment by rhoadesre** [comment]
I guess I wonder what you're trying to achieve or avoid. 
"Verify that the ... concerns are addressed" state  that you ensure that they are addressed, if they are not addressed. 
"Verify to what extent ... concerns are addressed" only checks if they are addressed or not, but doesn't do anything if they are not addressed.

**Comment by dkraemer-anderScore** [comment]
Basically I wanted to point out that it is neither desirable nor possible for architects to ensure (all) stakeholder concerns are addressed. Instead, they should focus on specified requirements.
