### ISSUE TITLE
LG 03-04: Principle of Least Astonishment (POLA)

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/curriculum-foundation#605]
I didn't know the term `principle of least surprise` but only `principle of least astonishment` [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) (I know that Wikipedia isn't the best option). 

I saw that it is mentioned as `principle of least surprise` on wikipedia as well, but they mostly talk about POLA there. Shall we change it in our curriculum to POLA, too?

**Comment by ulibecker** [comment]
After doing some research, I found both terms to be used similarly often. Strangely, the German Wikipedia article "Principle of least surprise" corresponds to the English Wikipedia article "Principle of least astonishment". So, for me both would be fine.

**Comment by gernotstarke** [comment]
Will add both terms.

**Comment by gernotstarke** [comment]
see PR #628
