### ISSUE TITLE
Architecture decisions vs. Design decisions

### ISSUE THREAD

**Issue by ulibecker** [isaqb-org/curriculum-foundation#606]
We use both the terms "architecture decision" and "design decision". I think that this is not a deliberate distinction, but that they are used as synonyms. For clarity and to prevent confusion, we should settle on just one term. I suggest architecture decisions. Opinions?

**Comment by gernotstarke** [comment]
thanx for this observation - architecture decision sounds better for me too.

**Comment by gernotstarke** [comment]
PR approved and merged
