### ISSUE TITLE
Abschnitt "Voraussetzungen": Redundanz

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#62]
Redundanz: „Erfahrung in arbeitsteiliger Softwareentwicklung“ wird in diesem Abschnitt doppelt genannt. Vgl. Punkt 1 und Punkt 14. Unter Punkt 1 wird es als notwendig gekennzeichnet und unter Punkt 14 als „hilfreich“. Was ist korrekt?

**Comment by alxlo** [comment]
@alxlo hält das für _notwendig_

**Comment by gernotstarke** [comment]
Du meinst das doppelte Erwähnen von "arbeitsteiliger SW-Entwicklung", oder?

ich sehe das auch als sooo wichtig, dass wir's doppelt erwähnen können.

**Comment by alxlo** [comment]
Eine Deduplizierung halte ich schon für sinnvoll. Dennoch sollte betont werden, dass Erfahrungen in arbeitsteiliger Sofftwareentwicklung eine sehr, sehr, sehr notwendige Voraussetzung für das Training ist. Ansonsten ist nahezu kein Problembewusstsein für wesentliche Teile des Lehrstoffes vorhanden.

**Comment by gernotstarke** [comment]
Vorschlag zur Formulierung?
