### ISSUE TITLE
LG 03-06: Confusing/unclear wording

### ISSUE THREAD

**Issue by ulibecker** [isaqb-org/curriculum-foundation#625]
Under "can differentiate between at least the following categories of coupling:", the final bullet point lists "other types of coupling". It makes no sense to me to first set the focus on "at least the following categories", and then include basically "everything else". So I would remove that last bullet point.

Also, another bullet point in this learning goals states "can use such types of coupling...", where it is unclear to what "such" refers I that context. I suggest to write "can use different types of coupling..."

Opinions?

**Comment by rhoadesre** [comment]
> "can differentiate between at least the following categories of coupling:" ... So I would remove that last bullet point. 

I like having the different types of coupling, but not all of them need to be exam relevant. I suggest keeping the additional types of coupling, but making them R3. Concretely, I suggest:
> can differentiation between different types of coupling, for example:
> - static and dynamic coupling
> - efferent and afferent coupling
> - specific types of coupling (e.g. hardware/infrastructure, temporal, data, data structure etc.) (R3)

> Also, another bullet point in this learning goals states "can use such types of coupling...", where it is unclear to what "such" refers I that context. I suggest to write "can use different types of coupling..."

I think this statement is generally confusing. How do you use coupling in a targeted manner? I suggest to separate the two points and clarify the one point, as follows:
> - can assess the consequences of such dependencies
> - can specifically decide to increase coupling to fulfill requirements or constraints

**Comment by ulibecker** [comment]
There is a more extensive list of different types of coupling anyway: "know and understand different types of dependencies of building blocks (e.g. coupling via use/delegation, messaging/events, composition, creation, inheritance, temporal coupling, coupling via data, data types or hardware". So I think this would be redundant.

Regarding the second point, I agree that this is confusing. What I think is being meant here is that there is a conscious decision on the dependencies and the kind of coupling.
