### ISSUE TITLE
Inkonsistenz: Zeichensetzung bei den Lernzielen scheint im ganzen Dokument nicht konsistent zu sein

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#64]
vereinheitlichen:

nach den Unterpunkten bei Lernzielen entweder ; oder , oder nichts...

**Comment by gernotstarke** [comment]
I vote for the ";" at the end of bullet list entry.

no real bug, and might be deferred up to V 5.0 or even later.

Looking for volunteers here.

**Comment by alxlo** [comment]
Soll es lediglich einheitlich sein oder soll es (IMHO wichtiger) korrekt sein.
- [Kleiner Crashkurs: Satzzeichen nach Stichpunkten](https://www.textskizzen.de/satzzeichen-nach-stichpunkten/)
- [Rechtschreibung bei Stichpunkten: Die wichtigsten Regeln im Überblick](https://www.textskizzen.de/stichpunkte-rechtschreibregeln/)

**Comment by gernotstarke** [comment]
danke Alex. Wenn ich diese Quellen richtig verstehe, sollten wir in den Aufzählungen generell auf Satzzeichen am Ende der "Bullet-Sätze" verzichten.

Da wir ja ohnehin schon bei RC-4 sind, können wir das auch angehen...

Wie immer - Hilfe erwünscht.

**Comment by gernotstarke** [comment]
fixed #64 (removed trailing ";" from bullet list items)
