### ISSUE TITLE
LG 04-07: Cross-cutting concerns vs cross-cutting concepts

### ISSUE THREAD

**Issue by ulibecker** [isaqb-org/curriculum-foundation#640]
IMO cross-cutting concept and cross-cutting concerns are not synonymous:

* Cross-cutting concern corresponds to an aspect
* A solution concept for a cross-cutting concern corresponds to cross-cutting concept

**Comment by gernotstarke** [comment]
what is an aspect? Seems everybody in the FLWG has their own semantics of concerns, concepts, aspects (or even principles...)

**Comment by gernotstarke** [comment]
I mark this a "question".

**Comment by ulibecker** [comment]
A long-standing topic, indeed :-) My main point is not to introduce the term aspect, that was already there, and I would not object to removing it. My issue is having cross-cutting concerns and cross-cutting concepts named as synonyms. For me, cross-cutting concern is more related to the problem space, whereas cross-cutting concept would be a solution concept for a cross-cutting concern.

**Comment by rhoadesre** [comment]
I do agree with Uli. It would be clearer. In the literature, I haven't seen a differentiation between the two terms. 
More importantly, the differentiation is made in the German version, but not in the English version. 
For consistency reasons, we should decide one way or another and be consistent in the wording. 

Generally, I prefer separating "concerns" and "concepts", but I don't have a strong opinion either way.

**Comment by gernotstarke** [comment]
Then what about dropping the _aspect_ and making the distinction between problem and solution space clear.

Maybe that would resolve the issue once and for all :-)

**Comment by gernotstarke** [comment]
My proposal:

For the Foundation Level Curriculum we use the terms in the following way:

* Crosscutting **concerns**: A topic from the _problem space_, that _concerns_ multiple parts, elements, processes, activities or stakeholders of the system.
* Crosscutting **concepts**: A _solution approach_ that is (likely) used in several places, components, processes of the system, or is used by several stakeholders.

We drop the term _aspect_ as we consider it under-defined.
In addition, more synonyms make life harder, not better.

**Comment by rhoadesre** [comment]
Proposed change to LG 04-07:

>  Software architects are able to adequately document and communicate typical cross-cutting concerns (e. g., persistence, workflow management, UI, deployment/integration, logging), and their corresponding implementation concepts.

**Comment by rhoadesre** [comment]
> Proposed change to LG 04-07:
> 
> > Software architects are able to adequately document and communicate typical cross-cutting concerns (e. g., persistence, workflow management, UI, deployment/integration, logging), and their corresponding implementation concepts.

Proposal for corresponding changes in LG 04-07. Only the changes are referenced here. The other content remains the same.: 
> explain the significance of {glossary_url}cross-cutting-concerns[cross-cutting concerns], , for example persistence, communication, GUI, error handling, concurrency, energy efficiency
> ...
> design cross-cutting concepts that provide the solution approach for the corresponding cross-cutting concerns

**Comment by rhoadesre** [comment]
Didn't see that there was already a change for LG 04-07. 
To be consistent, we should change LG 03-10 accordingly.

**Comment by rhoadesre** [comment]
> Didn't see that there was already a change for LG 04-07. To be consistent, we should change LG 03-10 accordingly.

I'll create a new issue so that we can close this one.
