### ISSUE TITLE
Check consistency between LG titles and the graphical overview of changes between 2023 and 2025

### ISSUE THREAD

**Issue by sippsack** [isaqb-org/curriculum-foundation#667]
e. g. "LG 01-07: Importance of Data and Data Models (R2)" is still "LG 01-07: Importance and Design of Data Models (R2)"

**Comment by sippsack** [comment]
I will check all LG's when we have finalized the curriculum and update the graphical overview.

**Comment by gernotstarke** [comment]
fixed, PR created

**Comment by sippsack** [comment]
I would leave it still open to check consistency between curriculum and graphical overview just before the final release.
