### ISSUE TITLE
Wording in "Prerequisites"

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#69]
Vorschlag von Sevda Cagirici:
Den folgenden Satz „Insbesondere bilden substanzielle praktischen Erfahrungen aus der Softwareentwicklung im Team eine wichtige Voraussetzung zum Verständnis des…“ umändern in „Insbesondere bilden praktische Erfahrungen aus der Softwareentwicklung im Team eine substanzielle und wichtige Voraussetzung zum Verständnis des…“. 

---
#page:00-preamble/03-prerequisites.adoc

**Comment by alxlo** [comment]
Dagegen :-)
Die Erfahrungen sollten "substanziell" sein im Sinne von "ich habe tatsächlich an einem größeren Softwareprojekt gearbeitet".  Dass diese Voraussetzung wichtig ist brauchen wir nicht zweimal zu betonen wie es der Vorschlag von @gernotstarke vorsieht.

**Comment by gernotstarke** [comment]
ok - verstehe ich.
