### ISSUE TITLE
add reference to glossary

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#7]
Include a visible/prominent reference to our glossary, so that readers of the curriculum are directed towards it!

**Comment by p-goetz** [comment]
This could be something for an index page (#9) that offers some overview information. I will create that and we can then check if it suits our needs.

**Comment by gernotstarke** [comment]
Peter, I re-open this - as I meant to include the glossary-reference in the curriculum itself.

It's perfect that you included the link on the index page.

**Comment by gernotstarke** [comment]
this actually is a duplicate to #52 - I'll close this one here
