### ISSUE TITLE
migrate from Netlify to github-pages 

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#92]
[x] introduce a (technical) github user id for the build (isaqb-curriculum-admin)
[ ] migrate to github pages
[ ] setup custom domain

**Comment by aheusingfeld** [comment]
FYI As we're already using the [deploy plugin for Github Releases](https://github.com/isaqb-org/curriculum-foundation/blob/master/.travis.yml), I will use the [gradle-git-publish](https://github.com/ajoberstar/gradle-git-publish) plugin - as we do in aim42 - to copy the build result to Github Pages. This also brings along the flexibility that we can modify some of the files in a second step.

**Comment by aheusingfeld** [comment]
Here are the steps that I took:

1. Create a Personal Access Token
-> Login as isaqbcurriculum@gmail.com and go to https://github.com/settings/tokens

2. Store the Access Token in an encrypted Travis Build Var
travis encrypt GH_PAGES=31ecf58927e158ab1eb43204835cfc0a0690c2b3 --add
-> see 9218a11fa425c1e42acf1517fc30ca6a91c808e6


3. Update gradle build files
a) 9aa07e3fb45298b02002391f4f4c4b75768164d4
b) a6903d1c189d3498c7bd88b753e95b6f0cfbe721
c) 37660234f094e815d2add0e22e703ff97d90a288

4. Test it locally 
...by running `./gradlew clean renderNoRemarksDE publish --stacktrace`

Once the project is configured (https://github.com/isaqb-org/curriculum-foundation/settings) to use the Github Pages from the `gh-pages` branch, we should see the page at https://isaqb-org.github.io/curriculum-foundation

**Comment by aheusingfeld** [comment]
With #96 fixed, publishing works. Unfortunately @gernotstarke included the version number into the published files which not only broke Github Releases but the links in index.html don’t work anymore either

**Comment by gernotstarke** [comment]
can we collect some opinions here: Who thinks version numbers in filenames are

[+] ... a good idea
[-] ... a BAD idea and should be removed.

@programming-wolf @aheusingfeld @pgh @alxlo @p-goetz

**Comment by programming-wolf** [comment]
Bad to very bad idea from an end user‘s perspective. They just want the file, version is in the name.  
If you have a folder with all the versions of the file (and possible RCs and drafts for comparison), it’s of course easier to open the file you want.

**Comment by Hruschka** [comment]
+
Peter

Von meinem iPhone gesendet

**Comment by gernotstarke** [comment]
I consider this feature-complete and close THIS issue.
