### ISSUE TITLE
decide on curriculum domain name

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#93]
curriculum.isaqb.org as top-level "overview page" for all curricula

have subdomains for all (generated) advanced curricula:

improve-curriculum.isaqb.org
flex-curriculum.isaqb.org

or any other idea?

We need to coordinate/clarify with isaqb-infrastructure group (Marc Giersch) and Mirko!

**Comment by gernotstarke** [comment]
I don't know if it's possible to have a single domain (curriculum.isaqb.org) and link to all generated artifacts from there...

I assume it'll be a little overhead for iSAQB admins to create a subdomain for every curriculum...

your opinions, please: @programming-wolf @aheusingfeld @pgh @p-goetz @StefanZoerner

**Comment by p-goetz** [comment]
I think if we can host a static page at curriculum.isaqb.org that we are able to edit, we could add links to new curriculae if we need them. 
We wouldn't have nice-looking direct URLs to our respective curriculae, but I think that would be all right.

**Comment by gernotstarke** [comment]
or, for example: 

- curriculum.isaqb.org/foundation/index.html
- curriculum.isaqb.org/improve/index.html
...

@aheusingfeld in case you proceed on github pages generation, can you check if that's achievable?

**Comment by aheusingfeld** [comment]
See my comment in https://github.com/isaqb-org/curriculum-foundation/issues/92#issuecomment-509407364, Github Pages are automatically published under the `https://<group-name>.github.io/<repo-name>/` e.g. https://isaqb-org.github.io/curriculum-foundation. We can 
a) configure our own CNAME if we want to or 
b) publish everything to explicitly named folders in a https://github.com/isaqb-org/isaqb-org.github.io/ repository
