### ISSUE TITLE
create overview/entry page isaqb-org.github.io/index.html

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#95]
was müssen/können wir tun, um auf isaqb-org.github.io noch eine index.html mit Verweisen auf die einzelnen Lehrpläne zu bekommen?

**Comment by p-goetz** [comment]
I have found an article about this: https://www.freecodecamp.org/news/publishing-an-organization-homepage-on-github-pages-347dbd700f4e/
Will try to implement that.

**Comment by aheusingfeld** [comment]
As I said, it‘s a matter of creating a https://github.com/isaqb-org/isaqb-org.github.io repo and adding the pages to the master branch. Example is https://github.com/aim42/aim42.github.io! The difficulty is more that Gernot wanted to have the curriculae in subfolders with special names i.e. subfolder name != repo name.

**Comment by p-goetz** [comment]
Maybe I am missing something. I have created such a repository (didn't see that you mentioned this somewhere) and added a static index.html. I think from there we can link to anywhere else (manually). Since the amount of curriculae won't grow quickly this might be a good enough solution from my point of view.

**Comment by aheusingfeld** [comment]
As a starting point, that should be ok. I thought that the curriculae will anyway be linked directly on/from isaqb.org that‘s why I didn‘t consider it too urgent.

**Comment by gernotstarke** [comment]
I'm sorry to complain here - but none of versions hyperlinked on https://isaqb-org.github.io/curriculum-foundation/ is actually working :-(

What can/shall we do fix the links (is it enough to remove the version id from the filename?)??

@aheusingfeld - thanx for support.

(you're right - it's not super-urgent, but as this is the first curriculum to "go live" from github, we should strive for a smooth user experience...)

**Comment by gernotstarke** [comment]
> As I said, it‘s a matter of creating a https://github.com/isaqb-org/isaqb-org.github.io repo and adding the pages to the master branch. Example is https://github.com/aim42/aim42.github.io! The difficulty is more that Gernot wanted to have the curriculae in subfolders with special names i.e. subfolder name != repo name.

Having different folder names is important for the various upcoming advanced-level curricula!!

Another idea (if feasible) would be to integrate all these in a single github page with sub-pages - but I've no idea how to implement that :-(

**Comment by aheusingfeld** [comment]
Subfolders are not an issue in general. The complexity arises if the subfolder name shall be different from the repo-name. Keeping them equal is absolutely straight forward as you have seen with https://github.com/isaqb-org/curriculum-foundation/issues/92#issuecomment-509935887 i.e. https://isaqb-org.github.io/curriculum-foundation/
