### ISSUE TITLE
Publishing does not work in Travis CI

### ISSUE THREAD

**Issue by aheusingfeld** [isaqb-org/curriculum-foundation#96]
When executing “./gradlew publish” locally, artifacts from the /build folder are correctly pushed to the gh-pages branch. When Travis CI executes this, the builds ends with

> Task :curriculum-foundation:gitPublishCommit UP-TO-DATE
> Task :curriculum-foundation:gitPublishPush SKIPPED
> Task :publish

The result is that the changes are not pushed to the gh-pages branch

**Comment by aheusingfeld** [comment]
When checking the output of https://travis-ci.org/isaqb-org/curriculum-foundation I noticed that the resulting filename still has the RC3 even though the document.version contains a different version

**Comment by aheusingfeld** [comment]
Updating the CopySpec worked. Publishing works fine now

**Comment by programming-wolf** [comment]
Why did you remove both .gitignore and .gitmodules files? To my mind, they have to be there.

**Comment by aheusingfeld** [comment]
1. Reopening this issue means that the problem defined in the ticket still persists. I assume we both agree that this is not the case, so I will close it again
2. I removed them from the gh-pages branch only because they didn’t add any value but were copied there by accident. Keep in mind that the gh-pages  branch contains hand-picked files from the build result and is only expected to be modified by Travis CI builds.

If you feel strong reasoning to add a .gitignore file for gh-pages, please open a PR to advocate so
