### ISSUE TITLE
need to adjust timing of sections - currently too long!

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#99]
In v4 des Lehrplans hatten wir folgende Zeitaufteilung vorgeschlagen:

Grundlagen | 120
Entwurf und Entwicklung | 390
Beschreibung und Kommunikation | 240
Architektur und Qualität | 90
Werkzeuge | 45
Beispiele | 60
Summe:  945 min

Im aktuellen V5 (RC-4) kommen wir auf:

Grundlagen | 120
Entwurf und Entwicklung | 450
Beschreibung und Kommunikation | 300
Architektur und Qualität | 120
Beispiele | 90
Summe: 1080min

das sollten wir justieren, damit wir nachmittags am dritten Tag noch die Prüfung "unterkriegen".

**Comment by gernotstarke** [comment]
wäre schön, wenn wir insgesamt auf vielleicht 1000 min kommen, dann sollte das passen.

**Comment by programming-wolf** [comment]
Du meintest am 4. Tag, oder? Sind die Werkzeuge dann aufgeteilt auf die anderen Kapitel?

**Comment by gernotstarke** [comment]
Werkzeuge sind komplett entfallen. Und der Foundation-Kurs ist auf 3-Tage (minimal-Dauer) konzipiert. Einige Anbieter machen 4-Tage, um mehr Zeit für Übungen+Diskussionen zu haben.

**Comment by programming-wolf** [comment]
Ja, ich kann nicht rechnen. 1080 sind 18 Stunden also drei Tage, mein Fehler.

Keine Werkzeuge mehr 😢

**Comment by alxlo** [comment]
> Architektur und Qualität | 90
> Werkzeuge | 45
> Beispiele | 60

Der neueste "offiziell verlinkte" [ Lehrplan 4.2 von 2017](https://www.isaqb.org/wp-content/uploads/2017/11/isaqb-Lehrplan-foundation-v4-2-2017-DE_new.pd) sah hier IMHO etwas andere Werte vor. Ich fasse das mal zusammen:


| Abschnitt   | V4.2           | V5 (RC-4) | Delta |
| ------------- |  -------------:| -------------:| -----:|
| Einführung | 15     | n/a | -15|
| Grundlage   | 120 |120 |0|
| Entwurf und Entwicklung | 390 | 450 | 60 |
| Beschreibung + Kommunikation | 240 | 300 | 60 |
| Architektur + Qualität | 120 | 120 | 0 |
| Werkzeuge | 60 | n/a | -60 |
| Beispiel  | 45 | 90 | 45 |
| **Summe** | **1080** | **990** | **90**

**Comment by Hruschka** [comment]
Vorschlag: 

> Grundlagen | 120
> Entwurf und Entwicklung | 420
> Beschreibung und Kommunikation | 240
> Architektur und Qualität | 120
> Beispiele | 90
> 
> Summe: 990 min = 16,5 Stunden +1,5 Prüfung = 18 Stunden = 3 Tage
> 

Peter

Atlantic Systems Guild
Langenbruchweg 71
D-52080 Aachen
Phone: ++49 (0) 172 - 241 1656
www.b-agile.de

Meine Neuauflage des Buches über Business Analysis und Requirements. Mehr dazu: https://www.amazon.de/Business-Analysis-Requirements-Engineering-nachhaltig/dp/3446455892/ref=sr_1_2?ie=UTF8&qid=1550229441&sr=8-2

**Comment by gernotstarke** [comment]
@alex dann stimmt in 4.2 das Pie-Chart nicht mit den Angaben in den Tabellen überein... (was gut sein kann, das hat imho nie jemand überprüft)

**Comment by alxlo** [comment]
Ich schlage vor, dass wir insgesamt wieder auf 990 Minuten kommen, das hat den geringsten Impact auf die Zeitraster der Trainer. Die Prüfung an Tag 3 weiter nach hinten zu schieben ist organisatorisch problematisch, auf die anderen Tage je 45 Minuten draufzupacken auch, da entweder Pausen wegfallen oder sich ggfs. bereits angekündigte Zeiten ändern.

Full Disclosure: Das betrifft auch mich. Zumindest mir wäre das am liebsten,

**Comment by gernotstarke** [comment]
finde Peters Vorschlag gut - und 990 als Trainingszeit sollte für Anbieter akzeptabel 
sein!

**Comment by alxlo** [comment]
Ich hätte folgenden Vorschlag:
Grundlagen | 120 (120+0)
Entwurf und Entwicklung | 420 (330+90)
Beschreibung und Kommunikation | 260 (180+80)
Architektur und Qualität | 120 (60 +60)
Beispiele | 70 (70+0)

Summe: 990

**Comment by alxlo** [comment]
Mit Peters Vorschlag kann ich aber auch gut leben. Wie kommen wir zu einer Abstimmung?

**Comment by gernotstarke** [comment]
Da die Zeiten rein EMPFEHLUNGEN sind, schlage ich die "geradere" Version vor,
260 und 70 erscheinen mir als Zeitvorschläge zu "krumm" (sorry, Alex).

Also - Vorsitzender der FLWG entscheidet.

Danke euch für's mitstimmen.

Jetzt bleibt bestimmt bei MIR hängen, das einzupflegen, oder hat jemand heute noch Zeit?

[ ] Tabellen
[ ] Pie-Chart DE
[ ] Pie-Chart EN
[ ] abschliessende Kontrolle

**Comment by programming-wolf** [comment]
Kann ich übernehmen.

**Comment by gernotstarke** [comment]
dann sehr gerne Ben - ich habe das PieChart.xlsx angepasst.

Das Diagramm brauchen wir imho gar nicht neu zu exportieren, weil dort ja keine Zahlen dran stehen.

**Comment by programming-wolf** [comment]
Wie setzen sich die Zeiten zusammen? Meine Vermutung: 

 Grundlagen | 120 **(120 + 0)**
 Entwurf und Entwicklung | 420 **(330 + 90)**
 Beschreibung und Kommunikation | 240 **(180 + 60)**
 Architektur und Qualität | 120 **(60 + 60)**
 Beispiele | 90 **(90 + 0)**

Ist das so korrekt?

**Comment by gernotstarke** [comment]
genau Ben, so isses.

**Comment by programming-wolf** [comment]
Alles klar. Dann habe ich das so (hoffentlich überall) eingetragen. 
Hab die Tabellen im Excel angeschaut, die Charts neu erstellt (sehen doch ein bisschen anders aus), die gewünschten Tabellen aus #100 eingetragen sowie die Tabellen der einzelnen Kapitel angepasst (wo nötig).

**Comment by rhoadesre** [comment]
Hallo zusammen, 


Grüße aus Kroatien. Ich bin im Urlaub und habe die Emails überflogen. 




Ich finde den Vorschlag für die Aufteilung gut und es ist gut, dass ihr die Grafik im Lehrplan entsprechend ändert. Danke.




Aber wie kommt ihr überhaupt auf die Zahlen? Anzahl bzw. Dauer aller Themen pro Kapitel?




Meine Erfahrung nach, wenn ich mich auf den Themen im Lehrplan konzentriere, verbringe ich viel mehr Zeit mit der Kombination "Dokumentation und Kommunikation" und "Architektur und Qualität" als mit "Entwurf und Entwicklung". 




Ich wollte irgendwann das Problematik mit euch diskutieren, da mein Gefühl ist, dass es nicht genug Fokus auf "Entwurf und Entwicklung" im Lehrplan bzw. in den Prüfungsfragen im Vergleich mit den anderen Themen gibt. 




Die Aufteilung finde ich als Empfehlung gut, aber wir sollten die Themen noch mal überprüfen, um sicherzustellen, dass sie zur Zeitaufteilung wirklich passen, vor allem in der Aufteilung der Prüfungsfragen.




Viele Grüße,




Roger




Viele Grüße,




Roger E. Rhoades


+49 152 53 44 33 55







On Fri, Aug 16, 2019 at 2:50 PM +0200, "Ben" <notifications@github.com> wrote:












Alles klar. Dann habe ich das so (hoffentlich überall) eingetragen.


Hab die Tabellen im Excel angeschaut, die Charts neu erstellt (sehen doch ein bisschen anders aus), die gewünschten Tabellen aus #100 eingetragen sowie die Tabellen der einzelnen Kapitel angepasst (wo nötig).

**Comment by gernotstarke** [comment]
closed for now - timing is good enough for V5 release. Further discussion about modifications will be done in another issue.
